"""DataFusion-native seed templates — portable SQL stressing DF-weak
surfaces (set-op ALL multiplicity, generated cols, list concat NULL,
correlated subqueries, recursive CTE naming) plus generic edges that
port cleanly to the other engines.
"""
from __future__ import annotations

DF_TEMPLATES: list[tuple[str, list[str], str]] = [
    # set-op ALL multiplicity / NULL matching
    ("except_all_dup",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1),(1),(2),(2),(2),(3)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (1),(2)"],
     "SELECT x, count(*) c FROM (SELECT x FROM t EXCEPT ALL SELECT x FROM u) s GROUP BY x ORDER BY x"),
    ("except_all_null",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (NULL),(NULL),(1)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (NULL)"],
     "SELECT x, count(*) FROM (SELECT x FROM t EXCEPT ALL SELECT x FROM u) s GROUP BY x ORDER BY x"),
    ("intersect_all_dup",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1),(1),(1),(2)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (1),(1)"],
     "SELECT x, count(*) FROM (SELECT x FROM t INTERSECT ALL SELECT x FROM u) s GROUP BY x ORDER BY x"),
    ("intersect_all_null",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (NULL),(NULL),(1)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (NULL),(1)"],
     "SELECT x, count(*) FROM (SELECT x FROM t INTERSECT ALL SELECT x FROM u) s GROUP BY x ORDER BY x"),
    ("union_all_vs_union",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1),(1),(NULL)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (1),(NULL)"],
     "SELECT count(*) FROM (SELECT x FROM t UNION ALL SELECT x FROM u) s"),
    ("union_distinct_null",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (NULL),(1)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (NULL),(2)"],
     "SELECT x FROM t UNION SELECT x FROM u ORDER BY x"),
    # generated columns
    ("gen_col_read",
     ["CREATE TABLE g(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g(a) VALUES (1),(2),(3)"],
     "SELECT a, b FROM g ORDER BY a"),
    ("gen_col_join",
     ["CREATE TABLE g(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g(a) VALUES (1),(2)",
      "CREATE TABLE h(b INT)", "INSERT INTO h VALUES (2),(4)"],
     "SELECT g.a FROM g JOIN h ON g.b = h.b ORDER BY g.a"),
    ("gen_col_where",
     ["CREATE TABLE g(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g(a) VALUES (1),(2),(3)"],
     "SELECT a FROM g WHERE b > 2 ORDER BY a"),
    # list || NULL propagation
    ("list_concat_null",
     ["CREATE TABLE t(a INT, l INT[])", "INSERT INTO t VALUES (1,[1,2]),(2,NULL)"],
     "SELECT a, l || [9] FROM t ORDER BY a"),
    ("list_concat_null_rev",
     ["CREATE TABLE t(a INT, l INT[])", "INSERT INTO t VALUES (1,[1,2]),(2,NULL)"],
     "SELECT a, [9] || l FROM t ORDER BY a"),
    # correlated scalar in SELECT (analyzer reject class)
    ("corr_scalar_select",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(a INT, w INT)", "INSERT INTO u VALUES (1,5)"],
     "SELECT a, (SELECT w FROM u WHERE u.a = t.a) FROM t ORDER BY a"),
    ("corr_scalar_agg",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(a INT, w INT)", "INSERT INTO u VALUES (1,5),(2,7)"],
     "SELECT a, (SELECT max(w) FROM u WHERE u.a <= t.a) FROM t ORDER BY a"),
    # recursive CTE column naming
    ("recursive_named_col",
     [],
     "WITH RECURSIVE t(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM t WHERE n < 5) SELECT sum(n) FROM t"),
    ("recursive_two_col",
     [],
     "WITH RECURSIVE t(n, d) AS (SELECT 1, 0 UNION ALL SELECT n+1, d+1 FROM t WHERE n < 4) SELECT max(n), max(d) FROM t"),
    # window functions
    ("win_frame_rows",
     ["CREATE TABLE t(a INT, v INT)", "INSERT INTO t VALUES (1,10),(1,20),(2,30)"],
     "SELECT a, v, sum(v) OVER (PARTITION BY a ORDER BY v ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) s FROM t ORDER BY a, v"),
    ("win_range",
     ["CREATE TABLE t(a INT, v INT)", "INSERT INTO t VALUES (1,10),(1,20),(1,20),(2,30)"],
     "SELECT v, count(*) OVER (ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM t ORDER BY v"),
    ("win_ntile",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2),(3),(4),(5)"],
     "SELECT a, ntile(2) OVER (ORDER BY a) FROM t ORDER BY a"),
    # DISTINCT aggregates + FILTER
    ("agg_distinct",
     ["CREATE TABLE t(g INT, v INT)", "INSERT INTO t VALUES (1,1),(1,1),(1,2),(2,3)"],
     "SELECT g, count(DISTINCT v), sum(DISTINCT v) FROM t GROUP BY g ORDER BY g"),
    ("agg_filter",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2),(3)"],
     "SELECT count(*) FILTER (WHERE a>1), sum(a) FILTER (WHERE a<=2) FROM t"),
    # CASE / COALESCE type mixing
    ("coalesce_mixed",
     ["CREATE TABLE t(a INT, f DOUBLE)", "INSERT INTO t VALUES (NULL,1.5),(2,0.0)"],
     "SELECT coalesce(a, f) FROM t ORDER BY coalesce(a, f)"),
    # scalar subquery no row -> NULL
    ("scalar_norow",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1)"],
     "SELECT a, (SELECT max(a) FROM t WHERE a > 5) FROM t"),
    # GROUPING SETS
    ("grouping_sets",
     ["CREATE TABLE t(a INT, b INT, v INT)", "INSERT INTO t VALUES (1,1,10),(1,2,20),(2,1,30)"],
     "SELECT a, b, sum(v) FROM t GROUP BY GROUPING SETS ((a,b),(a),()) ORDER BY a NULLS LAST, b NULLS LAST"),
    # ---- round 2 ----------------------------------------------------
    # set-op chains and NULL edge cases (DF-A/B root area neighbours)
    ("except_plain_null",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (NULL),(1)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (1)"],
     "SELECT x FROM t EXCEPT SELECT x FROM u ORDER BY x"),
    ("intersect_plain_null",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (NULL),(NULL),(1)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (NULL)"],
     "SELECT x FROM t INTERSECT SELECT x FROM u ORDER BY x"),
    ("except_chain",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1),(1),(2)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (1)"],
     "SELECT x FROM t EXCEPT ALL SELECT x FROM u EXCEPT ALL SELECT 2 ORDER BY x"),
    ("union_except_mix",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (2),(3)"],
     "SELECT x FROM t UNION ALL SELECT x FROM u EXCEPT SELECT 3 ORDER BY x"),
    ("intersect_except_mix",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1),(2),(3)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (2),(3)"],
     "SELECT x FROM t INTERSECT SELECT x FROM u EXCEPT ALL SELECT 3 ORDER BY x"),
    # in/subquery over NULL
    ("in_null_rhs",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (2),(NULL)"],
     "SELECT x FROM t WHERE x IN (SELECT x FROM u) ORDER BY x"),
    ("not_in_null_rhs",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(x INT)", "INSERT INTO u VALUES (2),(NULL)"],
     "SELECT x FROM t WHERE x NOT IN (SELECT x FROM u) ORDER BY x"),
    ("exists_empty",
     ["CREATE TABLE t(x INT)", "INSERT INTO t VALUES (1)",
      "CREATE TABLE u(x INT)"],
     "SELECT x FROM t WHERE EXISTS (SELECT 1 FROM u) ORDER BY x"),
    # join semantics
    ("self_join_using",
     ["CREATE TABLE t(a INT, b INT)", "INSERT INTO t VALUES (1,10),(2,20)"],
     "SELECT x.b, y.b FROM t x JOIN t y USING(a) ORDER BY x.b"),
    ("full_join_both",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(a INT)", "INSERT INTO u VALUES (2),(3)"],
     "SELECT t.a, u.a FROM t FULL JOIN u ON t.a = u.a ORDER BY 1, 2"),
    ("cross_join_filter",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(b INT)", "INSERT INTO u VALUES (1),(2)"],
     "SELECT count(*) FROM t, u WHERE t.a = u.b"),
    # window edge cases beyond frames
    ("win_dup_order",
     ["CREATE TABLE t(v INT)", "INSERT INTO t VALUES (10),(10),(20)"],
     "SELECT v, rank() OVER (ORDER BY v), dense_rank() OVER (ORDER BY v), row_number() OVER (ORDER BY v) FROM t ORDER BY v"),
    ("win_empty_over",
     ["CREATE TABLE t(v INT)", "INSERT INTO t VALUES (1),(2)"],
     "SELECT v, sum(v) OVER (), row_number() OVER () FROM t ORDER BY v"),
    ("win_filter_arg",
     ["CREATE TABLE t(g INT, v INT)", "INSERT INTO t VALUES (1,1),(1,2),(2,3)"],
     "SELECT g, v, sum(v) FILTER (WHERE v>1) OVER (PARTITION BY g) FROM t ORDER BY g, v"),
    # aggregate edge cases
    ("count_distinct_null",
     ["CREATE TABLE t(v INT)", "INSERT INTO t VALUES (NULL),(NULL),(1)"],
     "SELECT count(DISTINCT v), count(*), count(v) FROM t"),
    ("group_by_null",
     ["CREATE TABLE t(g INT, v INT)", "INSERT INTO t VALUES (NULL,1),(NULL,2),(1,3)"],
     "SELECT g, sum(v) FROM t GROUP BY g ORDER BY g NULLS LAST"),
    ("avg_int",
     ["CREATE TABLE t(v INT)", "INSERT INTO t VALUES (1),(2)"],
     "SELECT avg(v), sum(v) * 1.0 / count(*) FROM t"),
    ("string_agg_order",
     ["CREATE TABLE t(g INT, v VARCHAR)", "INSERT INTO t VALUES (1,'b'),(1,'a'),(1,'c')"],
     "SELECT g, string_agg(v, ',' ORDER BY v DESC) FROM t GROUP BY g ORDER BY g"),
    # LIMIT/OFFSET/TOP-K interaction
    ("limit_offset",
     ["CREATE TABLE t(v INT)", "INSERT INTO t VALUES (1),(2),(3),(4),(5)"],
     "SELECT v FROM t ORDER BY v LIMIT 2 OFFSET 2"),
    ("limit0",
     ["CREATE TABLE t(v INT)", "INSERT INTO t VALUES (1)"],
     "SELECT v FROM t ORDER BY v LIMIT 0"),
    ("order_by_expr_alias",
     ["CREATE TABLE t(v INT)", "INSERT INTO t VALUES (2),(1)"],
     "SELECT v + 1 AS w FROM t ORDER BY w"),
    # correlated EXISTS in various positions
    ("corr_exists_not",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(a INT)", "INSERT INTO u VALUES (1)"],
     "SELECT a FROM t WHERE NOT EXISTS (SELECT 1 FROM u WHERE u.a = t.a) ORDER BY a"),
    ("corr_exists_or",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(a INT)", "INSERT INTO u VALUES (1)"],
     "SELECT a FROM t WHERE a = 99 OR EXISTS (SELECT 1 FROM u WHERE u.a = t.a) ORDER BY a"),
    ("corr_exists_agg",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(a INT)", "INSERT INTO u VALUES (1),(2),(2)"],
     "SELECT a FROM t WHERE (SELECT count(*) FROM u WHERE u.a = t.a) > 1 ORDER BY a"),
    # case/coalesce more
    ("case_null_result",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)"],
     "SELECT CASE WHEN a > 1 THEN a END FROM t ORDER BY a"),
    ("coalesce_allnull",
     ["CREATE TABLE t(a INT, b INT)", "INSERT INTO t VALUES (NULL,NULL)"],
     "SELECT coalesce(a, b, 42) FROM t"),
    ("nullif_eq",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (0),(1)"],
     "SELECT a, nullif(a, 1) FROM t ORDER BY a"),
    # distinct + order
    ("distinct_order_expr",
     ["CREATE TABLE t(a INT, b INT)", "INSERT INTO t VALUES (1,2),(1,1),(2,3)"],
     "SELECT DISTINCT a FROM t ORDER BY a DESC"),
    # BETWEEN SYMMETRIC / IS DISTINCT FROM
    ("between_sym",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(5),(9)"],
     "SELECT a FROM t WHERE a BETWEEN 3 AND 9 ORDER BY a"),
    ("is_distinct",
     ["CREATE TABLE t(a INT, b INT)", "INSERT INTO t VALUES (1,1),(1,2),(NULL,NULL),(NULL,1)"],
     "SELECT a, b, a IS DISTINCT FROM b FROM t ORDER BY a NULLS LAST, b NULLS LAST"),
    # nested CTE + outer ref
    ("cte_nested_ref",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2)"],
     "WITH c1 AS (SELECT max(a) m FROM t) SELECT a, (SELECT m FROM c1) FROM t ORDER BY a"),
    ("cte_twice_ref",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (1),(2),(3)"],
     "WITH c AS (SELECT a, a*2 AS d FROM t) SELECT x.a, y.d FROM c x JOIN c y ON x.a = y.a ORDER BY x.a"),
    # EXPLAIN-shaped: HAVING on alias / ordinal
    ("having_alias",
     ["CREATE TABLE t(g INT, v INT)", "INSERT INTO t VALUES (1,5),(1,15),(2,7)"],
     "SELECT g, sum(v) s FROM t GROUP BY g HAVING s > 10 ORDER BY g"),
    # boolean aggregates
    ("bool_agg",
     ["CREATE TABLE t(b BOOLEAN)", "INSERT INTO t VALUES (true),(false),(NULL)"],
     "SELECT bool_and(b), bool_or(b) FROM t"),
    # arithmetic edge
    ("int_div_zero_guard",
     ["CREATE TABLE t(a INT, b INT)", "INSERT INTO t VALUES (10,0),(10,2)"],
     "SELECT a, b, CASE WHEN b<>0 THEN a/b ELSE NULL END FROM t ORDER BY a"),
    ("mod_zero",
     ["CREATE TABLE t(a INT)", "INSERT INTO t VALUES (5),(0)"],
     "SELECT a, 5 % nullif(a,0) FROM t ORDER BY a"),
]


def as_seeds():
    return [{"setup_sqls": s, "query": q,
             "source": f"df_target:{n}#{i}", "engine": "datafusion"}
            for i, (n, s, q) in enumerate(DF_TEMPLATES)]
