"""Edge-construct corpus for the internal-error scan.

Constructs absent from the regression-derived seed pool: XML functions,
jsonpath edges, ranges/multiranges, interval/timestamp overflow, numeric
precision limits, format()/text edges, array slice/ordinality edges, window
frame-exclusion modes, obscure type I/O (bit/bytea/macaddr/inet/money/
pg_lsn/send-recv), system introspection on weird input, WITH RECURSIVE /
CYCLE / SEARCH, CTE materialization, LATERAL, TABLESAMPLE.

Ordinary ERRORs are expected and ignored by the scan — the oracle is
internal-class errors (XX000, TRAP/PANIC, assert, crash) only. Builds are
--without-libxml/--without-icu so XML/ICU probes exercise the
not-supported error path. Same contract as pg_targets.py:
{surface, setup_sqls, query, note}; queries deterministic.
"""

from __future__ import annotations

PG_EDGE_TEMPLATES: list[tuple[str, list[str], str, str]] = [
    # ------------------------------------------------------------ XML
    ("xml", [], "SELECT xpath('//a[', '<a><b>1</b></a>')",
     "malformed xpath expr"),
    ("xml", [], "SELECT * FROM XMLTABLE('/a/b' PASSING '<a><b>1</b></a>' "
     "COLUMNS v text PATH '.')", "XMLTABLE basic"),
    ("xml", [], "SELECT xmlelement(name a, xmlattributes(1 AS x), "
     "xmlelement(name b, 'y'))", "nested xmlelement"),
    ("xml", [], "SELECT xmlparse(document '<a>')", "malformed doc parse"),
    ("xml", [], "SELECT * FROM XMLTABLE('*' PASSING '<a/>' COLUMNS id "
     "FOR ORDINALITY, v text NOT NULL PATH '@v')",
     "XMLTABLE ordinality + NOT NULL col"),
    ("xml", [], "SELECT xmlforest(NULL::int, 'x', NULL::text)",
     "xmlforest nulls"),
    # ----------------------------------------------------------- JSON
    ("jsonb_path", [], "SELECT jsonb_path_query('{\"a\":1}', 'strict $.a')",
     "strict mode member"),
    ("jsonb_path", [], "SELECT jsonb_path_query('{\"a\":1}', '$.a[')",
     "malformed jsonpath"),
    ("jsonb_path", [],
     "SELECT jsonb_path_query('{\"d\":\"2024-13-45\"}', '$.d.datetime()')",
     "datetime() on invalid date"),
    ("jsonb_path", [],
     "SELECT jsonb_path_query('{\"d\":\"10:20:30\"}', "
     "'$.d.datetime(\"HH24:MI:SS\")')", "datetime() with template"),
    ("jsonb_path", [],
     "SELECT jsonb_path_query('[\"abc\"]', 'lax $[*] ? (@ like_regex \"^[a\")')",
     "malformed regex in like_regex"),
    ("jsonb_path", [],
     "SELECT jsonb_path_query('\"9999999999999999999999\"', '$.bigint()')",
     "bigint() overflow"),
    ("jsonb_path", [],
     "SELECT jsonb_path_query('[0.1, 0.2]', 'lax $[*].double()')",
     "double() over array"),
    ("jsonb_path", [], "SELECT jsonb_path_query('{\"a\":1}', '$.keyvalue()')",
     "keyvalue() on object"),
    ("jsonb_path", [], "SELECT jsonb_path_query('42', '$.string()')",
     "string() on number"),
    ("jsonb_path", [],
     "SELECT jsonb_path_query_tz('{\"d\":\"2024-01-01 10:00:00+05\"}', "
     "'$.d.datetime()')", "query_tz datetime (PG17+)"),
    ("jsonb_path", [],
     "SELECT jsonb_path_exists('{\"a\":\"x\"}', "
     "'$.a == \"x\".datetime(\"yyyy\")')", "datetime() on non-date"),
    ("jsonb_ops", [], "SELECT '{\"a\":{\"b\":{\"c\":42}}}'::jsonb -> 'a' "
     "->> 'b' ->> 'c'", "chained -> / ->>"),
    ("jsonb_ops", [], "SELECT '[1,2,3]'::jsonb -> -5, '[1,2,3]'::jsonb ->> -1",
     "negative array subscripts"),
    ("jsonb_ops", [], "SELECT * FROM jsonb_each('5')", "each on scalar"),
    ("jsonb_ops", [],
     "SELECT jsonb_extract_path_text('{\"a\":null}', 'a', 'b')",
     "extract path through null"),
    ("jsonb_ops", ["CREATE TYPE jj AS (x int, y text)"],
     "SELECT * FROM jsonb_populate_record('{}'::jj, '{\"x\":\"noint\"}')",
     "populate_record type error path"),
    ("jsonb_ops", [], "SELECT jsonb_set('{\"a\":[1,2]}', '{a,9}', '5')",
     "set beyond array bounds"),
    ("jsonb_ops", [], "SELECT jsonb_set('{\"a\":1}', '{a,b}', '{}', true)",
     "set into scalar create_missing"),
    ("jsonb_ops", [], "SELECT to_jsonb(ROW(1,'a',NULL))",
     "to_jsonb composite"),
    ("jsonb_ops", [],
     "SELECT json_strip_nulls('{\"a\":null,\"b\":[null,1]}')",
     "strip_nulls nested array untouched"),
    ("jsonb_ops", [], "SELECT '{\"a\":1}'::jsonb ? 'a', "
     "'[\"a\",1]'::jsonb ? 'a'", "? operator on obj/arr"),
    ("jsonb_ops", [], "SELECT jsonb_path_query('{\"a\":[1,2,3]}', '$.a[0 to 2]')",
     "array slice in path"),
    # ----------------------------------------------- ranges/multiranges
    ("range", [],
     "SELECT range_agg(r) FROM (VALUES (int4range(1,3)),(int4range(5,7)),"
     "(NULL)) v(r)", "range_agg with nulls (PG17+)"),
    ("range", [],
     "SELECT '{[1,3],[5,9]}'::int4multirange + int4range(4,4)",
     "multirange + bridging range merges"),
    ("range", [], "SELECT range_intersect(int4range(0,10), int4range(5,20))",
     "range_intersect"),
    ("range", [], "SELECT int4range(0,10) - int4range(3,5)",
     "non-contiguous range difference"),
    ("range", [],
     "SELECT '{[0,10]}'::int4multirange - '{[3,5]}'::int4multirange",
     "multirange difference splits"),
    ("range", [],
     "SELECT lower_inf('(,)'::int8range), upper_inf('(,)'::int8range), "
     "isempty('empty'::int8range)", "infinite/empty bounds"),
    ("range", [],
     "SELECT '{[1,3),[3,5)}'::int4multirange", "adjacent ranges normalize"),
    ("range", [],
     "SELECT '[-infinity,infinity]'::tstzrange", "infinite tstzrange"),
    ("range", [],
     "SELECT daterange('2020-01-01','infinity') * "
     "daterange('-infinity','2021-01-01')", "daterange intersect inf bounds"),
    ("range", [],
     "SELECT * FROM unnest('{[1,2],[4,5]}'::int4multirange)",
     "unnest multirange"),
    ("range", [],
     "SELECT int4range(1,5) @> int4range(1,5), int4range(1,5) -|- "
     "int4range(5,9)", "containment + adjacency"),
    ("range", [],
     "SELECT range_agg(int4range(g, g+2)) FROM generate_series(1,20,3) g",
     "range_agg gaps -> multirange"),
    ("range", [],
     "SELECT '[0,0]'::numrange(0,0) = 'empty'::numrange",
     "degenerate numrange is empty"),
    ("range", [],
     "SELECT numrange(0.0, -0.0), numrange(0.0, -0.0) = 'empty'",
     "-0.0 bound edge"),
    # ----------------------------------------- interval/timestamp edge
    ("interval", [], "SELECT make_interval(secs => 9223372036854)",
     "interval overflow via make_interval"),
    ("interval", [], "SELECT '2147483647 days'::interval + '1 day'::interval",
     "interval day overflow"),
    ("interval", [], "SELECT justify_interval('1 year -1 hour'::interval)",
     "justify_interval sign flip"),
    ("interval", [], "SELECT 'infinity'::timestamp - '-infinity'::timestamp",
     "inf minus -inf"),
    ("interval", [], "SELECT 'infinity'::timestamptz + '1 day'::interval",
     "inf plus interval stays inf"),
    ("interval", [], "SELECT extract(epoch from 'epoch'::timestamp)",
     "epoch of epoch"),
    ("interval", [],
     "SELECT date_bin('15 min', TIMESTAMP '2020-01-01 00:14', "
     "TIMESTAMP '2001-01-01')", "date_bin basic"),
    ("interval", [],
     "SELECT date_bin('0 sec', TIMESTAMP '2020-01-01', TIMESTAMP '2001-01-01')",
     "date_bin zero stride"),
    ("interval", [],
     "SELECT date_bin('-1 hour', TIMESTAMP '2020-01-01', "
     "TIMESTAMP '2001-01-01')", "date_bin negative stride"),
    ("interval", [],
     "SELECT make_timestamp(2020,13,45,25,61,61)", "make_timestamp overflow"),
    ("interval", [],
     "SELECT make_timestamptz(2020,1,1,0,0,0,'Mars/Olympus')",
     "make_timestamptz bad zone"),
    ("interval", [], "SELECT age('infinity'::timestamp)", "age of infinity"),
    ("interval", [], "SELECT '1 hour'::interval / 0", "interval div zero"),
    ("interval", [],
     "SELECT '2000-01-01'::timestamp - 'infinity'::timestamp",
     "ts minus inf"),
    ("interval", [],
     "SELECT '2001-02-16 20:38:40'::timestamptz AT TIME ZONE 'Invalid/Zone'",
     "AT TIME ZONE bad zone"),
    ("interval", [],
     "SELECT to_timestamp('2024-13-45','YYYY-MM-DD')", "to_timestamp bad date"),
    ("interval", [],
     "SELECT date_trunc('microsecond','2001-02-16 20:38:40.123456'::timestamp)",
     "date_trunc microsecond"),
    ("interval", [],
     "SELECT '999999-12-31'::timestamp", "huge year timestamp"),
    ("interval", [], "SELECT '-4713-01-01'::date + (-1)",
     "date below minimum"),
    # ---------------------------------------------------------- numeric
    ("numeric", [], "SELECT 'NaN'::numeric + 1, 'NaN'::numeric > "
     "'Infinity'::numeric, 'NaN'::numeric = 'NaN'::numeric",
     "NaN arithmetic and ordering"),
    ("numeric", [],
     "SELECT 'Infinity'::numeric * '-Infinity'::numeric, "
     "'Infinity'::numeric / 0, 'Infinity'::numeric % 1",
     "numeric infinity ops"),
    ("numeric", [], "SELECT 1::numeric/0", "numeric div zero"),
    ("numeric", [], "SELECT (10::numeric ^ 131071)", "numeric max exponent"),
    ("numeric", [], "SELECT (10::numeric ^ 131072)", "numeric overflow exp"),
    ("numeric", [], "SELECT '9223372036854775808'::int8", "int8 literal +1"),
    ("numeric", [], "SELECT '9223372036854775807'::int8 + 1", "int8 max +1"),
    ("numeric", [], "SELECT abs(-9223372036854775808::int8)",
     "abs of int8 min"),
    ("numeric", [], "SELECT 2147483647::int4 + 1", "int4 overflow"),
    ("numeric", [], "SELECT (-2147483648)::int4", "int4 min literal quirk"),
    ("numeric", [], "SELECT 5/0, 5.0/0", "int and numeric div zero"),
    ("numeric", [], "SELECT 5%0", "int mod zero"),
    ("numeric", [], "SELECT mod(5,0)", "mod() zero"),
    ("numeric", [], "SELECT 2::int8 ^ 63::int8", "int8 pow overflow"),
    ("numeric", [], "SELECT (1::numeric/3)::numeric(10,5)",
     "numeric scale cast"),
    ("numeric", [], "SELECT 123.456::numeric(3,0)", "precision squeeze err"),
    ("numeric", [], "SELECT round('NaN'::numeric), trunc(123.456, -5)",
     "round NaN / negative trunc"),
    ("numeric", [], "SELECT trunc(1.5::numeric, 1000)", "huge trunc digits"),
    ("numeric", [], "SELECT width_bucket(5, 0, 10, 0)",
     "width_bucket zero count"),
    ("numeric", [], "SELECT width_bucket('NaN'::numeric, 1,10,5)",
     "width_bucket NaN operand"),
    ("numeric", [], "SELECT 25!", "factorial numeric"),
    ("numeric", [], "SELECT (-1)!", "factorial negative"),
    ("numeric", [], "SELECT sqrt(-1::numeric)", "sqrt negative"),
    ("numeric", [], "SELECT ln(-1)", "ln negative"),
    ("numeric", [], "SELECT exp(10000)", "float exp overflow -> inf"),
    ("numeric", [], "SELECT 'NaN'::float8 = 'NaN'::float8, "
     "'Infinity'::float8 - 'Infinity'::float8", "float NaN eq, inf-inf"),
    ("numeric", [], "SELECT 1e308::float8 * 10, -1e308::float8 * 10",
     "float8 overflow to inf"),
    ("numeric", [], "SELECT 1::int4 << 33, 5::int4 >> 100",
     "shift beyond width"),
    ("numeric", [], "SELECT '1 2 3'::int2vector, 'a'::oidvector",
     "vector casts"),
    ("numeric", [], "SELECT 0.0/0.0", "float div zero"),
    ("numeric", [], "SELECT numeric '0.00000000000000000000001' * 0.1",
     "tiny scale multiply"),
    # ------------------------------------------------------------- text
    ("text", [], "SELECT format('%s %L %I', NULL, NULL, NULL)",
     "format all specifiers NULL"),
    ("text", [], "SELECT format('%5$s', 'a')", "format out-of-range ref"),
    ("text", [], "SELECT format('%s%s', 'a')", "format too few args"),
    ("text", [], "SELECT position('' in 'abc'), position('abc' in 'abcabc')",
     "position edge"),
    ("text", [], "SELECT substr('abcdef', -2, 3), substr('abc', 0, 5)",
     "substr negative/zero start"),
    ("text", [], "SELECT substr('abc',2,-1)", "substr negative len"),
    ("text", [], "SELECT left('abc', -5), right('abc', -5)",
     "left/right negative"),
    ("text", [], "SELECT 'straße' ILIKE 'STRASSE'", "unicode ilike"),
    ("text", [], "SELECT lower('İ'), upper('ß')", "multichar case fold"),
    ("text", [], "SELECT normalize('Héllo', 'nfkd')", "unicode normalize"),
    ("text", [], "SELECT 'a' COLLATE \"C\" < 'B' COLLATE \"POSIX\"",
     "cross collation compare"),
    ("text", [], "SELECT chr(0)", "chr zero"),
    ("text", [], "SELECT chr(55296)", "chr surrogate"),
    ("text", [], "SELECT repeat('x', 0), repeat('ab', -1)",
     "repeat non-positive"),
    ("text", [], "SELECT to_char(1.5, 'FM999.99')", "to_char float fmt"),
    ("text", [], "SELECT to_number('12,34','99D99')", "to_number bad input"),
    ("text", [], "SELECT split_part('a,b,c', ',', -1)", "split_part negative"),
    ("text", [], "SELECT split_part('a,b',',',0)", "split_part zero"),
    ("text", [], "SELECT string_to_array('abc', NULL)",
     "string_to_array null delim"),
    ("text", [], "SELECT string_to_array('a,,b',',',NULL)",
     "string_to_array null placeholder"),
    ("text", [], "SELECT md5(''), encode('abc','base64')",
     "md5 empty / encode"),
    ("text", [], "SELECT decode('!!','base64'), decode('zz','hex')",
     "decode garbage"),
    ("text", [], "SELECT quote_ident('a\"b'), quote_literal(E'a\\'b')",
     "quote edge"),
    ("text", [], "SELECT regexp_replace('aaa','a*','X','g')",
     "regexp zero-width global replace"),
    ("text", [], "SELECT regexp_match('abc', '(')", "malformed regexp"),
    ("text", [], "SELECT (regexp_match('a','a'))[2]", "match group miss"),
    ("text", [], "SELECT regexp_replace('abc', 'x{1000}', 'y')",
     "regexp bounded repeat"),
    ("text", [], "SELECT 'a' LIKE 'a' ESCAPE ''", "empty escape char"),
    ("text", [], "SELECT ascii(''), to_hex(-1)", "ascii empty / to_hex neg"),
    ("text", [], "SELECT lpad('abc', 10, ''), lpad('abc', -1)",
     "lpad empty fill / negative"),
    ("text", [], "SELECT starts_with('abc','')", "starts_with empty"),
    ("text", [], "SELECT btrim('abc', 'cab')", "btrim all chars"),
    ("text", [], "SELECT overlay('Txxxxas' placing 'hom' from -1 for 3)",
     "overlay negative from"),
    ("text", [], "SELECT translate('abcdef', 'def', 'xy')",
     "translate shrink"),
    ("text", [], "SELECT 'abc' SIMILAR TO '%(a|b)%' ESCAPE ''",
     "similar-to empty escape"),
    # ----------------------------------------------------------- arrays
    ("array", [], "SELECT array_agg(x) FROM (VALUES (NULL),(NULL)) v(x)",
     "array_agg of nulls"),
    ("array", [],
     "SELECT array_agg(x) FROM (SELECT 1 WHERE false) v(x)",
     "array_agg empty -> null"),
    ("array", [], "SELECT (ARRAY[1,2,3,4,5])[0:2]",
     "slice with zero lower bound"),
    ("array", [], "SELECT (ARRAY[1,2,3])[2:1]", "empty slice"),
    ("array", [], "SELECT (ARRAY[1,2,3])[-2147483648]",
     "subscript int min"),
    ("array", [], "SELECT * FROM unnest(ARRAY[1,2,3]) WITH ORDINALITY",
     "unnest ordinality"),
    ("array", [], "SELECT ARRAY[[1,2],[3,4]], (ARRAY[[1,2],[3,4]])[2][1]",
     "multidim array"),
    ("array", [], "SELECT ARRAY[[1],[2,3]]", "ragged multidim"),
    ("array", [], "SELECT * FROM unnest(ARRAY[[1,2],[3,4]]) WITH ORDINALITY",
     "unnest multidim ordinality"),
    ("array", [], "SELECT array_to_string(ARRAY[1,NULL,3], ',')",
     "array_to_string skips null"),
    ("array", [], "SELECT array_to_string(ARRAY[1,2], ',', 'X')",
     "array_to_string null string"),
    ("array", [], "SELECT string_to_array('a,b',',') || 'x'",
     "array concat element"),
    ("array", [], "SELECT array_position(ARRAY[1,NULL,3], NULL)",
     "position of null"),
    ("array", [], "SELECT array_remove(ARRAY[1,NULL,1], NULL)",
     "remove nulls"),
    ("array", [], "SELECT cardinality(ARRAY[]::int[]), "
     "cardinality(ARRAY[[1,2],[3,4]])", "cardinality"),
    ("array", [], "SELECT array_dims('{}'::int[])", "dims of empty"),
    ("array", [], "SELECT array_fill(0, ARRAY[-1])", "array_fill negative"),
    ("array", [], "SELECT array_fill('x', ARRAY[2], ARRAY[3])",
     "array_fill lower bound"),
    ("array", [], "SELECT ARRAY[1,2] @> ARRAY[NULL], NULL::int[] @> ARRAY[1]",
     "containment null"),
    ("array", [], "SELECT array_cat(ARRAY[1], NULL::int[]), "
     "ARRAY[1] || NULL::int[]", "cat null array"),
    ("array", [], "SELECT (ARRAY[]::int[])[1]", "subscript empty"),
    ("array", [], "SELECT (ARRAY[[1,2],[3,4]])[0:1][1]",
     "multidim slice zero bound"),
    ("array", [], "SELECT array_prepend(0, ARRAY[1,2]), "
     "array_append(ARRAY[1,2], 0)", "prepend/append"),
    ("array", [],
     "SELECT ARRAY(SELECT x FROM (VALUES(1),(2)) v(x))",
     "array from subquery"),
    # ----------------------------------------------------------- window
    ("window", [],
     "SELECT x, sum(x) OVER (ORDER BY x GROUPS BETWEEN 1 PRECEDING AND "
     "CURRENT ROW EXCLUDE TIES) FROM (VALUES (1),(1),(2)) v(x) ORDER BY x",
     "GROUPS frame EXCLUDE TIES"),
    ("window", [],
     "SELECT x, sum(x) OVER (ORDER BY x GROUPS BETWEEN CURRENT ROW AND "
     "CURRENT ROW EXCLUDE GROUP) FROM (VALUES (1),(1),(2)) v(x) ORDER BY x",
     "GROUPS frame EXCLUDE GROUP"),
    ("window", [],
     "SELECT x, sum(x) OVER (ORDER BY x ROWS BETWEEN 1 PRECEDING AND "
     "CURRENT ROW EXCLUDE CURRENT ROW) FROM (VALUES (1),(2)) v(x) "
     "ORDER BY x", "EXCLUDE CURRENT ROW"),
    ("window", [],
     "SELECT x, nth_value(x, 0) OVER (ORDER BY x) FROM (VALUES(1),(2)) v(x)",
     "nth_value zero"),
    ("window", [],
     "SELECT x, nth_value(x, -1) OVER (ORDER BY x) FROM (VALUES(1),(2)) v(x)",
     "nth_value negative"),
    ("window", [], "SELECT x, lead(x, -1) OVER (ORDER BY x) "
     "FROM (VALUES(1)) v(x)", "lead negative offset"),
    ("window", [],
     "SELECT sum(x) OVER (ORDER BY d RANGE BETWEEN INTERVAL '1 day' "
     "PRECEDING AND CURRENT ROW) FROM (VALUES (1,'2020-01-01'::date),"
     "(2,'2020-01-02'::date),(3,'2020-01-02'::date)) v(x,d) ORDER BY d",
     "RANGE interval offset on date"),
    ("window", [], "SELECT row_number() OVER (), rank() OVER (ORDER BY NULL)",
     "ungrouped window + null order"),
    ("window", [],
     "SELECT count(*) FILTER (WHERE x>1) OVER () FROM (VALUES(1),(2)) v(x)",
     "aggregate FILTER as window"),
    ("window", [],
     "SELECT x, string_agg(x::text, ',') OVER (ORDER BY x ROWS "
     "UNBOUNDED PRECEDING) FROM (VALUES(1),(2),(3)) v(x) ORDER BY x",
     "string_agg running"),
    ("window", [],
     "SELECT x, first_value(x) OVER w, last_value(x) OVER w "
     "FROM (VALUES(1),(2)) v(x) WINDOW w AS (ORDER BY x ROWS BETWEEN "
     "UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) ORDER BY x",
     "named window frame"),
    # ------------------------------------------------- obscure type I/O
    ("bit", [], "SELECT B'1010' & B'1100', B'1010' >> 2, B'1010'::bit(2)",
     "bit ops and truncation"),
    ("bit", [], "SELECT '10102'::bit(4)", "bad bit string"),
    ("bit", [], "SELECT bit_count(B'1111'), bit_and(b) FROM "
     "(VALUES (B'11'),(B'10')) v(b)", "bit_count / bit_and"),
    ("bytea", [], "SELECT '\\xdeadbeef'::bytea || '\\x00'::bytea",
     "bytea concat"),
    ("bytea", [], "SELECT get_bit('\\xff'::bytea, 0), "
     "get_bit('\\xff'::bytea, 7)", "get_bit bounds"),
    ("bytea", [], "SELECT get_bit('\\xff'::bytea, 9)", "get_bit out of range"),
    ("bytea", [], "SELECT substring('\\xdeadbeef'::bytea from 2 for 2), "
     "position('\\xbe'::bytea in '\\xdeadbeef'::bytea)", "bytea substr/pos"),
    ("bytea", [], "SELECT '\\x'::bytea, octet_length('\\x00ff'::bytea)",
     "empty bytea + length"),
    ("bytea", [], "SELECT byteaout(byteain('\\x00'))", "bytea in/out cycle"),
    ("uuid", [], "SELECT 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid, "
     "'not-a-uuid'::uuid", "uuid good and bad"),
    ("uuid", [], "SELECT uuidv7(), uuid_extract_version(uuidv7())",
     "uuidv7 (PG18+)"),
    ("uuid", [],
     "SELECT uuid_extract_timestamp('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11')",
     "extract ts from non-v7 uuid"),
    ("macaddr", [], "SELECT '08:00:2b:01:02:03'::macaddr = "
     "macaddr '08-00-2B-01-02-03', trunc('08:00:2b:01:02:03'::macaddr)",
     "macaddr eq + trunc"),
    ("macaddr", [], "SELECT '08:00:2b:01:02:03:04:05'::macaddr8, "
     "macaddr8_set7bit('08:00:2b:01:02:03:04:05'::macaddr8)", "macaddr8"),
    ("inet", [], "SELECT '10.0.0.1/8'::inet, '10.0.0.1/8'::cidr",
     "inet vs cidr host bits"),
    ("inet", [], "SELECT '10.0.0.1'::inet - '10.0.0.5'::inet, "
     "host('10.0.0.1/8'::inet), masklen('10.0.0.1/24'::inet)", "inet arith"),
    ("inet", [], "SELECT '255.255.255.255'::inet + 1", "inet max + 1"),
    ("inet", [], "SELECT set_masklen('10.0.0.1/24'::inet, 8), "
     "'10/8'::cidr, netmask('10.0.0.1/24'::inet)", "mask ops"),
    ("inet", [], "SELECT '::1'::inet, '2001:db8::/32'::cidr", "ipv6"),
    ("money", [], "SELECT '100.50'::money + '0.01'::money",
     "money addition"),
    ("money", [], "SELECT 'NaN'::money", "money NaN"),
    ("money", [], "SELECT '1e5'::money", "money sci notation"),
    ("pg_lsn", [], "SELECT '0/0'::pg_lsn, 'FFFFFFFF/FFFFFFFF'::pg_lsn",
     "pg_lsn bounds"),
    ("pg_lsn", [], "SELECT '0/0'::pg_lsn - '1/0'::pg_lsn",
     "pg_lsn negative diff"),
    ("pg_lsn", [], "SELECT pg_lsn '0/1' + 1, '2/0'::pg_lsn - '1/0'::pg_lsn",
     "pg_lsn arith"),
    ("tid", [], "SELECT '(0,1)'::tid, '(4294967295,65535)'::tid",
     "tid bounds"),
    ("regtype", [], "SELECT 'int4'::regtype, 'nonexistent_xyz'::regclass",
     "regtype ok / regclass miss"),
    ("sendrecv", [], "SELECT int4send(5)", "int4send binary out"),
    ("sendrecv", [], "SELECT int4recv('\\x00000005'::bytea)",
     "int4recv 5 bytes"),
    ("sendrecv", [], "SELECT int4recv('\\x01'::bytea)",
     "int4recv short buffer"),
    ("sendrecv", [], "SELECT int4recv(''::bytea)", "int4recv empty"),
    ("sendrecv", [], "SELECT numeric_recv(numeric_send(1.5))",
     "numeric send/recv roundtrip"),
    ("sendrecv", [], "SELECT record_send(ROW(1,'a'))", "record_send"),
    ("sendrecv", [], "SELECT unknownsend('x'::unknown)", "unknownsend"),
    ("sendrecv", [], "SELECT float8recv('x'::bytea)", "float8recv 1 byte"),
    ("sendrecv", [], "SELECT point_recv('\\x0001'::bytea)",
     "point_recv short"),
    ("sendrecv", [], "SELECT textrecv('abc'::bytea)", "textrecv raw"),
    ("sendrecv", [], "SELECT charsend('a'::\"char\"), namesend('n'::name)",
     "char/name send"),
    # ----------------------------------------------- system introspection
    ("sysfunc", [], "SELECT pg_typeof(NULL), pg_typeof(ROW(1,'a'))",
     "pg_typeof unknown + record"),
    ("sysfunc", [], "SELECT format_type(23, -1), format_type(1043, 10), "
     "format_type(-1, -1)", "format_type incl bad oid"),
    ("sysfunc", [], "SELECT format_type(25, 4294967295)",
     "format_type max typmod"),
    ("sysfunc", [], "SELECT to_regclass('pg_class'), to_regclass('nosuch'), "
     "to_regtype('foo')", "to_reg* null vs err"),
    ("sysfunc", [], "SELECT to_regproc('abs'), to_regproc('foo'), "
     "to_regnamespace('foo'), to_regrole('nosuchrole')", "to_reg* nulls"),
    ("sysfunc", [], "SELECT has_table_privilege('pg_class','SELECT'), "
     "has_table_privilege('nosuchtable','SELECT')", "privilege checks"),
    ("sysfunc", [],
     "SELECT has_column_privilege('pg_class','oid','SELECT'), "
     "has_schema_privilege('public','CREATE'), "
     "has_database_privilege('postgres','CONNECT')", "more privilege"),
    ("sysfunc", [],
     "SELECT has_function_privilege('abs(int)','EXECUTE'), "
     "has_tablespace_privilege('pg_default','CREATE'), "
     "has_language_privilege('sql','USAGE')", "func/tblspc/lang priv"),
    ("sysfunc", [], "SELECT has_sequence_privilege('nosuch','USAGE')",
     "seq priv missing obj"),
    ("sysfunc", [], "SELECT pg_total_relation_size('pg_class'), "
     "pg_relation_size('nosuch')", "pg_size_* miss"),
    ("sysfunc", [], "SELECT pg_column_size(ROW(1,'a')), "
     "pg_size_pretty(-1), pg_size_pretty(9223372036854775807)",
     "pg_size edge"),
    ("sysfunc", [], "SELECT pg_size_bytes('1 PB'), pg_size_bytes('-1 GB'), "
     "pg_size_bytes('1XB')", "pg_size_bytes bad unit"),
    ("sysfunc", [], "SELECT current_setting('nosuch'), "
     "current_setting('nosuch', true)", "current_setting missing"),
    ("sysfunc", [], "SELECT pg_get_expr('a > 0', 'pg_class'::regclass), "
     "pg_get_expr('nonsense((', 'pg_class'::regclass)",
     "pg_get_expr deparse incl garbage"),
    ("sysfunc", [], "SELECT pg_get_expr('', 'pg_class'::regclass)",
     "pg_get_expr empty"),
    ("sysfunc", [], "SELECT pg_get_constraintdef(0), pg_get_indexdef(0), "
     "pg_get_viewdef('pg_class'::regclass)", "getdef bad oid"),
    ("sysfunc", [], "SELECT pg_get_userbyid(0), pg_get_userbyid(1)",
     "userbyid unknown oid"),
    ("sysfunc", [], "SELECT col_description('pg_class'::regclass, 0), "
     "obj_description(0)", "descriptions edge"),
    ("sysfunc", [], "SELECT pg_encoding_to_char(-1), "
     "pg_char_to_encoding('BOGUS'), pg_char_to_encoding('UTF8')",
     "encoding lookup"),
    ("sysfunc", [], "SELECT pg_filenode_relation(0, 1259), "
     "pg_relation_filenode('pg_class')", "filenode lookup"),
    ("sysfunc", [], "SELECT pg_get_serial_sequence('pg_class','oid')",
     "serial sequence none"),
    ("sysfunc", [], "SELECT txid_current(), pg_current_xact_id()",
     "xact id funcs"),
    ("sysfunc", [], "SELECT pg_postmaster_start_time(), pg_backend_pid()",
     "backend info"),
    ("sysfunc", [], "SELECT 'a > 0'::pg_node_tree", "pg_node_tree cast"),
    ("sysfunc", [], "SELECT '1+1'::pg_node_tree",
     "pg_node_tree expr input"),
    ("sysfunc", [], "SELECT ROW(1,2) = ROW(1,2), 1 = ALL(ARRAY[1,2])",
     "record eq / ALL"),
    ("sysfunc", [], "SELECT pg_table_is_visible('pg_class'::regclass), "
     "pg_function_is_visible('abs'::regproc)", "visibility funcs"),
    # ---------------------------------- recursive CTE / cycle / lateral
    ("cte", [],
     "WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM r "
     "WHERE n < 10) SELECT count(*) FROM r", "recursive count"),
    ("cte", [],
     "WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n FROM r) "
     "SELECT n FROM r LIMIT 5", "nonterminating recursive + LIMIT"),
    ("cte", [],
     "WITH RECURSIVE g(n) AS (SELECT 1 UNION ALL SELECT n FROM g "
     "CYCLE n SET c USING p) SELECT count(*) FROM g",
     "CYCLE self-detect"),
    ("cte", [],
     "WITH RECURSIVE r(n,p) AS (VALUES(1,ARRAY[1]) UNION ALL "
     "SELECT n+1, p||n+1 FROM r WHERE n<5) SEARCH DEPTH FIRST BY n SET o "
     "SELECT * FROM r ORDER BY o", "SEARCH DEPTH FIRST"),
    ("cte", [],
     "WITH m AS MATERIALIZED (SELECT 'k' v) "
     "SELECT (SELECT v FROM m) = (SELECT v FROM m)",
     "MATERIALIZED hint determinism"),
    ("cte", [],
     "WITH m AS NOT MATERIALIZED (SELECT 1 v) SELECT * FROM m",
     "NOT MATERIALIZED hint"),
    ("cte", [],
     "WITH m(v) AS (SELECT 1) SELECT * FROM m AS a JOIN m AS b USING (v)",
     "CTE self join"),
    ("lateral", [],
     "SELECT * FROM (VALUES(1),(2)) a(x), LATERAL (SELECT x*2) b",
     "basic lateral"),
    ("lateral", [],
     "SELECT * FROM (VALUES(1)) a, LATERAL (SELECT 1 WHERE false) b",
     "lateral empty right"),
    ("lateral", ["CREATE TABLE lt(a int, j jsonb)",
                 "INSERT INTO lt VALUES (1,'{\"x\":1}'),(2,'{\"y\":2}')"],
     "SELECT a, k.key FROM lt, LATERAL jsonb_each(lt.j) k ORDER BY a",
     "lateral set-returning function"),
    ("lateral", [],
     "SELECT * FROM (VALUES(1)) a(x) LEFT JOIN LATERAL "
     "(SELECT x WHERE x > 5) b ON true", "lateral left join"),
    ("lateral", [],
     "SELECT x, (SELECT max(y) FROM generate_series(1,x) y) "
     "FROM (VALUES(2),(3)) v(x) ORDER BY x",
     "correlated srf subquery"),
    ("tablesample", ["CREATE TABLE ts AS SELECT i FROM "
                     "generate_series(1,200) i"],
     "SELECT count(*) FROM ts TABLESAMPLE SYSTEM (0)", "system 0%"),
    ("tablesample", ["CREATE TABLE ts AS SELECT i FROM "
                     "generate_series(1,200) i"],
     "SELECT count(*) FROM ts TABLESAMPLE SYSTEM (100)", "system 100%"),
    ("tablesample", ["CREATE TABLE ts AS SELECT i FROM "
                     "generate_series(1,200) i"],
     "SELECT count(*) FROM ts TABLESAMPLE BERNOULLI (0)", "bernoulli 0%"),
    ("tablesample", ["CREATE TABLE ts AS SELECT i FROM "
                     "generate_series(1,200) i"],
     "SELECT count(*) FROM ts TABLESAMPLE SYSTEM (50) REPEATABLE (42)",
     "repeatable seed deterministic"),
    ("tablesample", ["CREATE TABLE ts AS SELECT i FROM "
                     "generate_series(1,200) i"],
     "SELECT count(*) FROM ts TABLESAMPLE BERNOULLI (-1)",
     "negative sample pct"),
    ("tablesample", ["CREATE TABLE ts AS SELECT i FROM "
                     "generate_series(1,200) i"],
     "SELECT count(*) FROM ts TABLESAMPLE SYSTEM (101)", "sample > 100%"),
    # -------------------------------------------------- misc planner/SQL
    ("misc", [], "SELECT (SELECT x FROM (VALUES(1),(2)) v(x))",
     "scalar subquery multirow"),
    ("misc", [], "SELECT NULLIF(1,1), COALESCE(NULL,NULL)",
     "nullif hit + unknown coalesce"),
    ("misc", [], "SELECT 1 UNION ALL SELECT 'a'", "union type conflict"),
    ("misc", [], "SELECT NULL UNION SELECT NULL", "union of nulls"),
    ("misc", [], "VALUES (1,2),(3)", "ragged VALUES"),
    ("misc", [], "SELECT 1 INTERSECT SELECT 1 EXCEPT SELECT 2",
     "set-op precedence"),
    ("misc", [], "SELECT 1 GROUP BY 1 HAVING count(*)>=0",
     "aggregate HAVING no table"),
    ("misc", [], "SELECT count(*) FROM (SELECT 1 WHERE false) s",
     "count empty"),
    ("misc", [],
     "SELECT DISTINCT ON (x) x, y FROM "
     "(VALUES(1,'a'),(1,'b'),(2,'c')) v(x,y) ORDER BY x, y",
     "distinct on"),
    ("misc", [], "SELECT CASE WHEN false THEN 1 END",
     "case no else null"),
    ("misc", [], "SELECT x FROM (SELECT 1 x) s WHERE x IN (SELECT 1)",
     "IN scalar subquery"),
    ("misc", [], "TABLE pg_class LIMIT 0", "TABLE stmt limit 0"),
    ("misc", [], "SELECT * FROM pg_class WHERE oid = 0",
     "catalog oid zero"),
    ("misc", ["CREATE DOMAIN posint AS int CHECK (VALUE > 0)"],
     "SELECT '5'::posint, '-3'::posint", "domain cast ok + violate"),
    ("misc", ["CREATE TYPE mood AS ENUM ('sad','ok','happy')"],
     "SELECT enum_range(NULL::mood), 'ok'::mood < 'sad'::mood",
     "enum_range + ordering"),
    ("misc", [],
     "SELECT x, count(*) OVER () FROM (VALUES(1),(1)) v(x) "
     "GROUP BY x ORDER BY x", "window over grouped"),
    ("misc", [],
     "SELECT generate_series(1,0), * FROM generate_series(0,0) g",
     "empty srf targets"),
    ("misc", [],
     "SELECT * FROM generate_series(1,3) WITH ORDINALITY AS t(i,o)",
     "srf ordinality alias"),
    ("misc", [], "SELECT 1 = ANY(ARRAY[1,2]), 3 <> ALL(ARRAY[1,2])",
     "ANY/ALL array"),
    ("misc", [], "SELECT NOT NULL, NULL IS NOT TRUE, NULL IS UNKNOWN",
     "null boolean edges"),
    ("misc", [],
     "SELECT x.* FROM (VALUES (ROW(1,'a'),2)) v(x)",
     "column of composite"),
    ("misc", [],
     "SELECT (r).a, (r).b FROM (SELECT ROW(1,'x') r) s",
     "field select composite"),
    ("misc", [],
     "SELECT * FROM (VALUES (1,'a'),(2,'b')) AS v(a,b) ORDER BY b LIMIT 1",
     "values alias cols"),
    ("misc", [], "SELECT 'all'::\"char\", 'z'::char(1), ''::char(1)",
     "char(1) edges"),
    ("misc", [], "SELECT ' 5 '::int, E'\\t7'::int", "whitespace int cast"),
    ("misc", [], "SELECT '0x1F'::int", "hex literal cast int"),
    ("misc", [], "SELECT '0b101'::int, '0o17'::int",
     "binary/octal literal cast"),
    ("misc", [], "SELECT '1_000'::int", "underscore literal cast"),
    ("misc", [], "SELECT '+Inf'::float8, 'iNfInItY'::float8, 'nan'::float8",
     "case-insensitive float specials"),
    ("misc", [], "SELECT 'infinity'::float8::numeric",
     "float inf to numeric"),
    ("misc", [], "SELECT 'infinity'::numeric::float8",
     "numeric inf to float"),
    ("misc", [], "SELECT '1.5e2'::int4", "float-syntax int cast"),
    ("misc", [], "SELECT '5.'::int, '.5'::float8", "edge number formats"),
    ("misc", [],
     "SELECT extract(century from '2001-01-01'::date), "
     "extract(millennium from '0999-01-01'::date)", "extract big units"),
    ("misc", [],
     "SELECT date_part('epoch', '00:00:01'::interval)",
     "date_part epoch interval"),
    ("misc", [], "SELECT timestamp '2001-02-16' + interval '25 hours'",
     "ts+interval>24h"),
    ("misc", [], "SELECT '2001-02-30'::date", "invalid feb 30 date"),
    ("misc", [], "SELECT '2001-02-16 25:00:00'::time", "invalid 25h time"),
    ("misc", [], "SELECT '25:00'::interval", "interval 25h valid"),
    ("misc", [],
     "SELECT now() = now(), clock_timestamp() >= now()", "volatile clocks"),
    ("misc", [],
     "SELECT setseed(0.5), random() = random()", "setseed determinism"),
]


def as_seeds() -> list[dict]:
    out = []
    for i, (surface, setup, query, note) in enumerate(PG_EDGE_TEMPLATES):
        out.append({
            "setup_sqls": list(setup),
            "query": query,
            "source": f"pg_edge:{surface}#{i}",
            "engine": "postgres",
            "tags": ["pg_edge", surface, note],
        })
    return out


if __name__ == "__main__":
    import json
    print(json.dumps(as_seeds(), indent=1)[:2000])
    print("count:", len(PG_EDGE_TEMPLATES))
