"""PostgreSQL-native feature templates: queries exercising PG-specific
surfaces that shared/DuckDB-derived corpora never touch.

Targets (PG 16.x): arrays, LATERAL, DISTINCT ON, JSONB, CTE MATERIALIZED,
declarative partitioning + partitionwise, generated columns, recursive CTE,
FILTER/EXCLUDE window clauses, numeric/date edge cases, set-op ALL forms,
regex/string ops, domain-ish CHECK types, TABLESAMPLE REPEATABLE.

Each template is a seed dict: {setup_sqls, query, source, tags}.
All queries must be deterministic (no unseeded random()/clock functions,
no undefined order, no unordered aggregates).
"""

from __future__ import annotations

# (surface, setup_sqls, query, note)
PG_TEMPLATES: list[tuple[str, list[str], str, str]] = [
    # ---------------------------------------------------------- arrays
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{1,2,3}'),(2,'{2,3}'),(3,'{}'),(4,NULL),(5,'{1,1,1}')"],
     "SELECT id, array_length(arr,1) FROM a1 ORDER BY id",
     "array_length incl NULL/empty"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{1,2,3}'),(2,'{2,3}'),(3,'{}'),(4,NULL)"],
     "SELECT id, u FROM a1, LATERAL unnest(arr) u ORDER BY id, u",
     "unnest lateral"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{1,2,3}'),(2,'{2,3}'),(3,'{}'),(4,NULL)"],
     "SELECT id FROM a1 WHERE arr @> '{2}' ORDER BY id",
     "array contains"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{1,2,3}'),(2,'{2,3}'),(3,'{}'),(4,NULL)"],
     "SELECT id FROM a1 WHERE arr && '{3,9}' ORDER BY id",
     "array overlap"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{1,2,3}'),(2,'{2,3}'),(3,NULL)"],
     "SELECT id, arr[1], arr[0], arr[4], arr[-1] FROM a1 ORDER BY id",
     "array index edge"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{1,2,3,4}'),(2,'{9,8,7,6}'),(3,NULL)"],
     "SELECT id, arr[2:3], arr[:2], arr[3:] FROM a1 ORDER BY id",
     "array slices"),
    ("array",
     ["CREATE TABLE a1(id INT, v INT)",
      "INSERT INTO a1 VALUES (1,5),(1,3),(2,7),(2,7),(3,NULL)"],
     "SELECT id, array_agg(v ORDER BY v DESC NULLS LAST) FROM a1 GROUP BY id ORDER BY id",
     "array_agg ordered"),
    ("array",
     ["CREATE TABLE a1(id INT, v INT)",
      "INSERT INTO a1 VALUES (1,5),(1,3),(2,7),(3,NULL)"],
     "SELECT id, v, array_agg(v) OVER (PARTITION BY id ORDER BY v ROWS UNBOUNDED PRECEDING) FROM a1 ORDER BY id, v NULLS LAST",
     "window array_agg"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{1,2,NULL}'),(2,'{NULL,NULL}'),(3,'{}')"],
     "SELECT id, array_position(arr, NULL), cardinality(arr) FROM a1 ORDER BY id",
     "array NULL elems"),
    ("array",
     ["CREATE TABLE a1(id INT, arr TEXT[])",
      "INSERT INTO a1 VALUES (1,'{a,b}'),(2,'{A,b}'),(3,'{a,a}')"],
     "SELECT id, array_to_string(arr,',') FROM a1 ORDER BY id",
     "array_to_string"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[][])",
      "INSERT INTO a1 VALUES (1,'{{1,2},{3,4}}'),(2,'{{5,6}}'),(3,NULL)"],
     "SELECT id, arr[1][2], array_dims(arr) FROM a1 ORDER BY id",
     "multidim array"),
    ("array",
     ["CREATE TABLE a1(id INT, v INT)",
      "INSERT INTO a1 VALUES (1,1),(1,2),(2,3)"],
     "SELECT id FROM a1 GROUP BY id HAVING 2 = ANY(array_agg(v)) ORDER BY id",
     "HAVING ANY array_agg"),
    # ---------------------------------------------------------- LATERAL
    ("lateral",
     ["CREATE TABLE t1(id INT, v INT)",
      "INSERT INTO t1 VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,1),(1,2),(2,3)"],
     "SELECT t1.id, s.w FROM t1, LATERAL (SELECT w FROM t2 WHERE t2.k=t1.id ORDER BY w LIMIT 2) s ORDER BY t1.id, s.w",
     "lateral limit"),
    ("lateral",
     ["CREATE TABLE t1(id INT, v INT)",
      "INSERT INTO t1 VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,1),(2,3)"],
     "SELECT t1.id, s.w FROM t1 LEFT JOIN LATERAL (SELECT w FROM t2 WHERE t2.k=t1.id) s ON true ORDER BY t1.id, s.w",
     "lateral left join unmatched"),
    ("lateral",
     ["CREATE TABLE t1(id INT)",
      "INSERT INTO t1 VALUES (1),(2),(3)"],
     "SELECT t1.id, g.x FROM t1 CROSS JOIN LATERAL (SELECT t1.id*10 AS x) g ORDER BY t1.id",
     "lateral scalar ref"),
    ("lateral",
     ["CREATE TABLE t1(id INT)",
      "INSERT INTO t1 VALUES (2),(3)"],
     "SELECT t1.id, s.i FROM t1, LATERAL generate_series(1,t1.id) s(i) ORDER BY t1.id, s.i",
     "lateral SRF"),
    ("lateral",
     ["CREATE TABLE t1(id INT, v INT)",
      "INSERT INTO t1 VALUES (1,10),(2,20)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,5),(1,15),(2,25)"],
     "SELECT t1.id, s.agg FROM t1 LEFT JOIN LATERAL (SELECT sum(w) AS agg FROM t2 WHERE t2.k=t1.id) s ON true ORDER BY t1.id",
     "lateral aggregate"),
    ("lateral",
     ["CREATE TABLE t1(id INT)",
      "INSERT INTO t1 VALUES (1),(2)"],
     "SELECT t1.id, s.x FROM t1, LATERAL (SELECT x FROM (VALUES (t1.id+1),(t1.id+2)) v(x)) s ORDER BY t1.id, s.x",
     "lateral VALUES"),
    # ------------------------------------------------------- DISTINCT ON
    ("distinct_on",
     ["CREATE TABLE d1(a INT, b INT, c INT)",
      "INSERT INTO d1 VALUES (1,9,1),(1,5,2),(1,7,3),(2,1,4),(2,8,5)"],
     "SELECT DISTINCT ON (a) a, b, c FROM d1 ORDER BY a, b",
     "distinct on asc"),
    ("distinct_on",
     ["CREATE TABLE d1(a INT, b INT)",
      "INSERT INTO d1 VALUES (1,9),(1,5),(2,1),(2,8),(3,NULL)"],
     "SELECT DISTINCT ON (a) a, b FROM d1 ORDER BY a, b DESC NULLS LAST",
     "distinct on desc nulls"),
    ("distinct_on",
     ["CREATE TABLE d1(a INT, b TEXT)",
      "INSERT INTO d1 VALUES (1,'x'),(1,'y'),(1,'x'),(2,'z')"],
     "SELECT DISTINCT ON (a,b) a, b FROM d1 ORDER BY a, b",
     "distinct on multikey"),
    # ---------------------------------------------------------- JSONB
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1,\"b\":[1,2]}'),(2,'{\"a\":2}'),(3,'{}'),(4,NULL)"],
     "SELECT id, j->>'a', j->'b' FROM j1 ORDER BY id",
     "jsonb extract"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":{\"x\":5}}'),(2,'{\"a\":{\"x\":6}}'),(3,'{}')"],
     "SELECT id, j#>>'{a,x}' FROM j1 ORDER BY id",
     "jsonb path text"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1}'),(2,'{\"a\":2,\"b\":3}'),(3,'{}')"],
     "SELECT id FROM j1 WHERE j @> '{\"a\":1}' ORDER BY id",
     "jsonb contains"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'[1,2,3]'),(2,'[2,3]'),(3,'[]')"],
     "SELECT id, e FROM j1, LATERAL jsonb_array_elements(j) e ORDER BY id, e",
     "jsonb array elements"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1}'),(2,'{\"a\":2}')"],
     "SELECT id, j ? 'a', j ? 'zzz' FROM j1 ORDER BY id",
     "jsonb key exists"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, v INT)",
      "INSERT INTO j1 VALUES (1,5),(1,3),(2,7)"],
     "SELECT id, jsonb_agg(jsonb_build_object('v',v) ORDER BY v) FROM j1 GROUP BY id ORDER BY id",
     "jsonb_agg ordered"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1}'),(2,'{\"a\":2,\"b\":{}}')"],
     "SELECT id, j - 'a', j || '{\"z\":9}' FROM j1 ORDER BY id",
     "jsonb delete/concat"),
    # ------------------------------------------------- CTE MATERIALIZED
    ("cte_mat",
     ["CREATE TABLE c1(a INT, b INT)",
      "INSERT INTO c1 VALUES (1,10),(1,20),(2,30),(2,40)"],
     "WITH s AS MATERIALIZED (SELECT a, sum(b) t FROM c1 GROUP BY a) SELECT s1.a, s1.t, s2.t FROM s s1 JOIN s s2 ON s1.a=s2.a ORDER BY s1.a",
     "materialized self-join"),
    ("cte_mat",
     ["CREATE TABLE c1(a INT, b INT)",
      "INSERT INTO c1 VALUES (1,10),(2,30)"],
     "WITH s AS NOT MATERIALIZED (SELECT a, b FROM c1) SELECT * FROM s s1 JOIN s s2 ON s1.a=s2.a AND s1.b<s2.b ORDER BY s1.a",
     "not materialized self-join"),
    ("cte_mat",
     ["CREATE TABLE c1(a INT)",
      "INSERT INTO c1 VALUES (1),(2),(3)"],
     "WITH s AS MATERIALIZED (SELECT a, a*2 d FROM c1) SELECT a, d FROM s WHERE d IN (SELECT d FROM s) ORDER BY a",
     "materialized in-subq"),
    ("cte_mat",
     ["CREATE TABLE c1(a INT, b INT)",
      "INSERT INTO c1 VALUES (1,10),(1,20),(2,30)"],
     "WITH s AS (SELECT a, sum(b) t FROM c1 GROUP BY a) SELECT a FROM c1 WHERE a IN (SELECT a FROM s WHERE t>15) ORDER BY a",
     "cte in subquery"),
    # ------------------------------------------------------ recursive
    ("recursive",
     ["CREATE TABLE r1(id INT, parent INT)",
      "INSERT INTO r1 VALUES (1,NULL),(2,1),(3,1),(4,2),(5,4)"],
     "WITH RECURSIVE tr AS (SELECT id, parent, 0 d FROM r1 WHERE parent IS NULL UNION ALL SELECT r.id, r.parent, t.d+1 FROM r1 r JOIN tr t ON r.parent=t.id) SELECT id, d FROM tr ORDER BY id",
     "tree walk"),
    ("recursive",
     ["CREATE TABLE r1(id INT, parent INT)",
      "INSERT INTO r1 VALUES (1,NULL),(2,1),(3,2),(4,3)"],
     "WITH RECURSIVE tr AS (SELECT id, 0 d FROM r1 WHERE id=1 UNION ALL SELECT r.id, t.d+1 FROM r1 r JOIN tr t ON r.parent=t.id) SELECT max(d) FROM tr",
     "chain depth"),
    ("recursive",
     [],
     "WITH RECURSIVE s(i) AS (SELECT 1 UNION ALL SELECT i+1 FROM s WHERE i<10) SELECT sum(i), count(*) FROM s",
     "series gen"),
    # ---------------------------------------------------- partitioning
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "INSERT INTO p1 VALUES (10,1),(20,2),(60,3),(70,4),(30,5)"],
     "SELECT a, sum(b) FROM p1 GROUP BY a ORDER BY a",
     "range partition agg"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY LIST (a)",
      "CREATE TABLE p1_a PARTITION OF p1 FOR VALUES IN (1,2)",
      "CREATE TABLE p1_b PARTITION OF p1 FOR VALUES IN (3,4)",
      "INSERT INTO p1 VALUES (1,10),(2,20),(3,30),(4,40)"],
     "SELECT * FROM p1 WHERE a IN (1,3) ORDER BY a",
     "list partition prune"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY HASH (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES WITH (MODULUS 2, REMAINDER 0)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES WITH (MODULUS 2, REMAINDER 1)",
      "INSERT INTO p1 VALUES (1,10),(2,20),(3,30),(4,40)"],
     "SELECT a, b FROM p1 ORDER BY a",
     "hash partition scan"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "INSERT INTO p1 VALUES (10,1),(20,2),(60,3)",
      "CREATE TABLE q1(a INT, c INT)",
      "INSERT INTO q1 VALUES (10,100),(60,300)"],
     "SELECT p1.a, p1.b, q1.c FROM p1 JOIN q1 ON p1.a=q1.a ORDER BY p1.a",
     "partition join"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "INSERT INTO p1 VALUES (10,1),(20,2),(60,3)"],
     "SELECT count(*) FROM p1 WHERE a >= 50",
     "partition count"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "INSERT INTO p1 VALUES (10,1),(20,2),(60,3)",
      "CREATE INDEX pi ON p1(b)"],
     "SELECT a, b FROM p1 WHERE b >= 2 ORDER BY a",
     "partitioned index"),
    # ------------------------------------------------ generated cols
    ("gen_col",
     ["CREATE TABLE g1(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g1(a) VALUES (1),(2),(NULL)"],
     "SELECT a, b FROM g1 ORDER BY a NULLS LAST",
     "generated basic"),
    ("gen_col",
     ["CREATE TABLE g1(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g1(a) VALUES (1),(2),(3)",
      "CREATE INDEX gi ON g1(b)"],
     "SELECT a FROM g1 WHERE b = 4 ORDER BY a",
     "generated index lookup"),
    ("gen_col",
     ["CREATE TABLE g1(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g1(a) VALUES (1),(2),(3)"],
     "SELECT sum(b), max(b) FROM g1 GROUP BY a ORDER BY a",
     "generated agg"),
    # ------------------------------------------------- window extras
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,20),(1,30),(2,5),(2,15)"],
     "SELECT g, v, sum(v) OVER (PARTITION BY g ORDER BY v ROWS UNBOUNDED PRECEDING EXCLUDE CURRENT ROW) FROM w1 ORDER BY g, v",
     "EXCLUDE CURRENT ROW"),
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,10),(1,20),(2,5)"],
     "SELECT g, v, sum(v) OVER (PARTITION BY g ORDER BY v GROUPS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE TIES) FROM w1 ORDER BY g, v",
     "GROUPS + EXCLUDE TIES"),
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,20),(2,5),(2,15)"],
     "SELECT g, v, avg(v) FILTER (WHERE v>10) OVER (PARTITION BY g) FROM w1 ORDER BY g, v",
     "window FILTER"),
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,20),(2,5)"],
     "SELECT g, v, sum(v) OVER w1, count(*) OVER w2 FROM w1 WINDOW w1 AS (PARTITION BY g), w2 AS (ORDER BY v) ORDER BY g, v",
     "named windows"),
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,10),(1,20),(2,5),(2,5)"],
     "SELECT g, v, sum(v) OVER (PARTITION BY g ORDER BY v RANGE BETWEEN 5 PRECEDING AND 5 FOLLOWING EXCLUDE GROUP) FROM w1 ORDER BY g, v",
     "RANGE + EXCLUDE GROUP"),
    ("window",
     ["CREATE TABLE w1(v INT)",
      "INSERT INTO w1 VALUES (10),(20),(30),(40)"],
     "SELECT v, ntile(2) OVER (ORDER BY v ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) FROM w1 ORDER BY v",
     "ntile empty tail frame"),
    ("window",
     ["CREATE TABLE w1(v INT)",
      "INSERT INTO w1 VALUES (10),(20),(30)"],
     "SELECT v, lead(v) OVER (ORDER BY v ROWS BETWEEN 2 FOLLOWING AND 1 FOLLOWING) FROM w1 ORDER BY v",
     "lead inverted frame"),
    # ------------------------------------------------ numeric/interval
    ("numeric",
     ["CREATE TABLE n1(a NUMERIC(10,3), b NUMERIC(10,3))",
      "INSERT INTO n1 VALUES (1.005, 2.675),(0.1, 0.2),(99999.999, 0.001)"],
     "SELECT a, b, a+b, a*b, round(a,2), round(b,2) FROM n1 ORDER BY a",
     "numeric rounding"),
    ("numeric",
     ["CREATE TABLE n1(a NUMERIC(20,10), b INT)",
      "INSERT INTO n1 VALUES (1.0000000001,3),(2.5,0)"],
     "SELECT a, a/NULLIF(b,0), b=0, CASE WHEN b<>0 THEN a/b END FROM n1 ORDER BY a",
     "numeric div by zero guard"),
    ("numeric",
     ["CREATE TABLE n1(a BIGINT)",
      "INSERT INTO n1 VALUES (9223372036854775806),(2),(-9223372036854775807)"],
     "SELECT a, a+1, a-1, -a FROM n1 WHERE a < 9223372036854775806 AND a > -9223372036854775807 ORDER BY a",
     "bigint bounds"),
    ("numeric",
     ["CREATE TABLE n1(a DOUBLE PRECISION)",
      "INSERT INTO n1 VALUES ('NaN'),('Infinity'),('-Infinity'),(1.5),(0.0)"],
     "SELECT a FROM n1 ORDER BY a",
     "float specials order"),
    ("numeric",
     ["CREATE TABLE n1(a DOUBLE PRECISION)",
      "INSERT INTO n1 VALUES ('NaN'),(1.5),(2.5)"],
     "SELECT max(a), min(a), sum(a), avg(a) FROM n1",
     "NaN aggregates"),
    ("numeric",
     ["CREATE TABLE n1(a DOUBLE PRECISION)",
      "INSERT INTO n1 VALUES (0.1),(0.2),(0.3)"],
     "SELECT a, a+a+a = 0.3 AS eq3, sum(a) OVER () FROM n1 ORDER BY a",
     "float assoc"),
    ("interval",
     ["CREATE TABLE i1(d DATE)",
      "INSERT INTO i1 VALUES ('2024-01-31'),('2024-03-01'),('2023-02-28')"],
     "SELECT d, d + INTERVAL '1 month' a, d + INTERVAL '30 days' b FROM i1 ORDER BY d",
     "month vs days"),
    ("interval",
     ["CREATE TABLE i1(d DATE)",
      "INSERT INTO i1 VALUES ('2024-01-31'),('2024-02-29')"],
     "SELECT d, (d + INTERVAL '1 month') = (d + INTERVAL '30 days') eq FROM i1 ORDER BY d",
     "interval eq congruence"),
    ("interval",
     ["CREATE TABLE i1(t TIMESTAMP)",
      "INSERT INTO i1 VALUES ('2024-03-10 02:30:00'),('2024-11-03 01:30:00')"],
     "SELECT t, t + INTERVAL '1 day', t + INTERVAL '24 hours' FROM i1 ORDER BY t",
     "dst edge (utc embed)"),
    ("interval",
     ["CREATE TABLE i1(a INTERVAL)",
      "INSERT INTO i1 VALUES ('1 month'),('30 days'),('1 year'),('365 days')"],
     "SELECT a, a = INTERVAL '30 days' eq30, a = INTERVAL '1 month' eqm FROM i1 ORDER BY a",
     "interval equality"),
    ("interval",
     ["CREATE TABLE i1(d DATE)",
      "INSERT INTO i1 VALUES ('2024-02-29'),('2023-02-28')"],
     "SELECT d, d + INTERVAL '1 year', d - INTERVAL '1 year' FROM i1 ORDER BY d",
     "leap year"),
    # ------------------------------------------------------ set ops
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2),(2),(3)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (2),(2),(4)"],
     "SELECT a FROM s1 UNION ALL SELECT a FROM s2 ORDER BY a",
     "union all"),
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2),(2),(3)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (2),(2),(4)"],
     "SELECT a FROM s1 INTERSECT ALL SELECT a FROM s2 ORDER BY a",
     "intersect all"),
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2),(2),(3)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (2),(2),(4)"],
     "SELECT a FROM s1 EXCEPT ALL SELECT a FROM s2 ORDER BY a",
     "except all"),
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2),(NULL)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (2),(NULL)"],
     "SELECT a FROM s1 UNION SELECT a FROM s2 ORDER BY a NULLS LAST",
     "union nulls"),
    ("setop",
     ["CREATE TABLE s1(a INT, b INT)", "INSERT INTO s1 VALUES (1,1),(1,2),(2,1)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (1),(2)"],
     "(SELECT a, b FROM s1) INTERSECT (SELECT a, a FROM s2) ORDER BY 1,2",
     "intersect arity"),
    # ------------------------------------------------ string / regex
    ("string",
     ["CREATE TABLE t1(s TEXT)",
      "INSERT INTO t1 VALUES ('abc'),('a_c'),('a%c'),('ABC'),('a\\c')"],
     "SELECT s FROM t1 WHERE s LIKE 'a\\_c' ESCAPE '\\' ORDER BY s",
     "like escape"),
    ("string",
     ["CREATE TABLE t1(s TEXT)",
      "INSERT INTO t1 VALUES ('abc'),('axc'),('a.c'),('ABC')"],
     "SELECT s FROM t1 WHERE s ~ '^a.c$' ORDER BY s",
     "regex match"),
    ("string",
     ["CREATE TABLE t1(s TEXT)",
      "INSERT INTO t1 VALUES ('abc'),('axc'),('ABC'),('xyz')"],
     "SELECT s, regexp_replace(s,'[bx]','_','g') FROM t1 ORDER BY s",
     "regexp_replace"),
    ("string",
     ["CREATE TABLE t1(s TEXT)",
      "INSERT INTO t1 VALUES ('abc'),('a%bc'),('a\\bc')"],
     "SELECT s FROM t1 WHERE s LIKE 'a!%b%' ESCAPE '!' ORDER BY s",
     "like escape bang"),
    ("string",
     ["CREATE TABLE t1(s TEXT)",
      "INSERT INTO t1 VALUES ('a1b2'),('x9y'),('nodigits')"],
     "SELECT s, substring(s from '[0-9]+') FROM t1 ORDER BY s",
     "substring regex"),
    ("string",
     ["CREATE TABLE t1(s TEXT COLLATE \"C\")",
      "INSERT INTO t1 VALUES ('a'),('B'),('A'),('b'),('1')"],
     "SELECT s FROM t1 ORDER BY s",
     "C collation order"),
    # ------------------------------------------------- grouping sets
    ("grouping",
     ["CREATE TABLE g1(a INT, b INT, v INT)",
      "INSERT INTO g1 VALUES (1,1,10),(1,2,20),(2,1,30)"],
     "SELECT a, b, sum(v), grouping(a,b) FROM g1 GROUP BY GROUPING SETS ((a,b),(a),()) ORDER BY 1 NULLS LAST, 2 NULLS LAST",
     "grouping sets"),
    ("grouping",
     ["CREATE TABLE g1(a INT, b INT, v INT)",
      "INSERT INTO g1 VALUES (1,1,10),(1,2,20),(2,1,30),(2,NULL,5)"],
     "SELECT a, b, sum(v) FROM g1 GROUP BY ROLLUP (a,b) ORDER BY 1 NULLS LAST, 2 NULLS LAST",
     "rollup"),
    ("grouping",
     ["CREATE TABLE g1(a INT, b INT, v INT)",
      "INSERT INTO g1 VALUES (1,1,10),(1,2,20),(2,1,30)"],
     "SELECT a, b, count(*) FROM g1 GROUP BY CUBE (a,b) ORDER BY 1 NULLS LAST, 2 NULLS LAST",
     "cube"),
    ("grouping",
     ["CREATE TABLE g1(a INT, v INT)",
      "INSERT INTO g1 VALUES (1,10),(1,20),(2,30)"],
     "SELECT a, sum(v) FROM g1 GROUP BY a HAVING sum(v) > 15 UNION ALL SELECT NULL, sum(v) FROM g1 ORDER BY 1 NULLS LAST",
     "having + union"),
    # --------------------------------------------- subquery / exists
    ("subquery",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1),(3),(NULL)"],
     "SELECT a FROM t1 WHERE a IN (SELECT k FROM t2) ORDER BY a",
     "IN with null"),
    ("subquery",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1),(3),(NULL)"],
     "SELECT a FROM t1 WHERE a NOT IN (SELECT k FROM t2) ORDER BY a",
     "NOT IN null trap"),
    ("subquery",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2),(3)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1),(2)"],
     "SELECT a FROM t1 WHERE EXISTS (SELECT 1 FROM t2 WHERE t2.k=t1.a) ORDER BY a",
     "correlated exists"),
    ("subquery",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1)"],
     "SELECT a, (SELECT count(*) FROM t2 WHERE t2.k=t1.a) FROM t1 ORDER BY a",
     "scalar correlated"),
    ("subquery",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (1,5),(2,15)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,1),(1,9),(2,20)"],
     "SELECT a FROM t1 WHERE b > ALL (SELECT w FROM t2 WHERE t2.k=t1.a) ORDER BY a",
     "ALL correlated"),
    ("subquery",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2),(3)"],
     "SELECT a FROM t1 WHERE a = ANY (SELECT a FROM t1 WHERE a<3) ORDER BY a",
     "ANY self"),
    # ------------------------------------------------- join order stress
    ("joins",
     ["CREATE TABLE j1(a INT)", "INSERT INTO j1 VALUES (1),(2),(3)",
      "CREATE TABLE j2(a INT)", "INSERT INTO j2 VALUES (1),(2)",
      "CREATE TABLE j3(a INT)", "INSERT INTO j3 VALUES (1)",
      "CREATE TABLE j4(a INT)", "INSERT INTO j4 VALUES (1),(4)",
      "CREATE TABLE j5(a INT)", "INSERT INTO j5 VALUES (1)"],
     "SELECT count(*) FROM j1 JOIN j2 ON j1.a=j2.a JOIN j3 ON j2.a=j3.a JOIN j4 ON j3.a=j4.a JOIN j5 ON j4.a=j5.a",
     "5-way join geqo edge"),
    ("joins",
     ["CREATE TABLE j1(a INT, b INT)", "INSERT INTO j1 VALUES (1,1),(2,2)",
      "CREATE TABLE j2(a INT)", "INSERT INTO j2 VALUES (1),(2),(3)"],
     "SELECT j1.a, j2.a FROM j1 FULL JOIN j2 ON j1.a=j2.a ORDER BY 1 NULLS LAST, 2 NULLS LAST",
     "full join"),
    ("joins",
     ["CREATE TABLE j1(a INT)", "INSERT INTO j1 VALUES (1),(2),(NULL)",
      "CREATE TABLE j2(a INT)", "INSERT INTO j2 VALUES (1),(NULL)"],
     "SELECT j1.a, j2.a FROM j1 LEFT JOIN j2 ON j1.a=j2.a ORDER BY 1 NULLS LAST, 2 NULLS LAST",
     "left join nulls"),
    ("joins",
     ["CREATE TABLE j1(a INT, b INT)", "INSERT INTO j1 VALUES (1,5),(2,7)",
      "CREATE TABLE j2(a INT, c INT)", "INSERT INTO j2 VALUES (1,1),(1,2),(3,1)"],
     "SELECT j1.a, j2.c FROM j1 LEFT JOIN j2 ON j1.a=j2.a AND j1.b > j2.c ORDER BY 1, 2 NULLS LAST",
     "left join complex pred"),
    ("joins",
     ["CREATE TABLE j1(a INT)", "INSERT INTO j1 VALUES (1),(2)",
      "CREATE TABLE j2(a INT)", "INSERT INTO j2 VALUES (1),(3)"],
     "SELECT j1.a FROM j1 WHERE EXISTS (SELECT 1 FROM j2 WHERE j2.a=j1.a) AND NOT EXISTS (SELECT 1 FROM j2 WHERE j2.a=j1.a+1) ORDER BY j1.a",
     "exists + not exists"),
    # ------------------------------------------------------- misc
    ("misc",
     ["CREATE TABLE m1(a INT, b INT)",
      "INSERT INTO m1 VALUES (1,10),(2,20),(3,30)"],
     "SELECT a, b, CASE WHEN a=1 THEN 'one' WHEN a=2 THEN 'two' ELSE 'other' END FROM m1 ORDER BY a",
     "case"),
    ("misc",
     ["CREATE TABLE m1(a INT)",
      "INSERT INTO m1 VALUES (1),(2),(NULL)"],
     "SELECT a, COALESCE(a,0), NULLIF(a,2), a IS NULL FROM m1 ORDER BY a NULLS LAST",
     "coalesce nullif"),
    ("misc",
     [],
     "SELECT i, i*i, i%3 FROM generate_series(1,10) i ORDER BY i",
     "generate_series"),
    ("misc",
     ["CREATE TABLE m1(a INT)",
      "INSERT INTO m1 VALUES (1),(2),(3),(4)"],
     "SELECT a FROM m1 TABLESAMPLE BERNOULLI (50) REPEATABLE (42) ORDER BY a",
     "seeded sample"),
    ("misc",
     ["CREATE TABLE m1(a INT, b INT)",
      "INSERT INTO m1 VALUES (1,1),(2,2),(3,3),(4,4)"],
     "SELECT a FROM m1 WHERE (a,b) IN (SELECT b, a FROM m1 WHERE b<4) ORDER BY a",
     "row-wise IN"),
    ("misc",
     ["CREATE TABLE m1(a INT)",
      "INSERT INTO m1 VALUES (1),(2),(3)"],
     "SELECT a FROM m1 WHERE (a > 1) = true AND (a < 3) IS NOT false ORDER BY a",
     "boolean compare"),
    ("misc",
     ["CREATE TABLE m1(a INT)",
      "INSERT INTO m1 VALUES (1),(2),(3),(4),(5)"],
     "SELECT a, sum(a) OVER (ORDER BY a ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) FROM m1 ORDER BY a",
     "reverse running total"),
    ("misc",
     ["CREATE TABLE m1(t TEXT)",
      "INSERT INTO m1 VALUES ('2024-01-15'),('2024-03-20')"],
     "SELECT t::DATE, t::DATE + 7 FROM m1 ORDER BY t",
     "cast date"),
    ("misc",
     ["CREATE TABLE m1(a INT)",
      "INSERT INTO m1 VALUES (1),(1),(2),(2),(2)"],
     "SELECT a, count(*), rank() OVER (ORDER BY count(*)) FROM m1 GROUP BY a ORDER BY a",
     "agg in window order"),
    ("misc",
     ["CREATE TABLE m1(a INT)",
      "INSERT INTO m1 VALUES (3),(1),(2)"],
     "SELECT a, lag(a) OVER (ORDER BY a), lead(a,2) OVER (ORDER BY a) FROM m1 ORDER BY a",
     "lag lead"),
    # -------------------------------------------- domain-ish / check
    ("domain",
     ["CREATE TABLE d1(a INT CHECK (a>0), b INT)",
      "INSERT INTO d1 VALUES (1,5),(2,10),(3,15)"],
     "SELECT a FROM d1 WHERE b>7 ORDER BY a",
     "check constraint"),
    ("domain",
     ["CREATE DOMAIN posint AS INT CHECK (VALUE > 0)",
      "CREATE TABLE d1(a posint, b INT)",
      "INSERT INTO d1 VALUES (1,5),(2,10)"],
     "SELECT a, a+1 FROM d1 ORDER BY a",
     "domain type"),
    # ------------------------------------------------- temp views
    ("view",
     ["CREATE TABLE v1(a INT, b INT)",
      "INSERT INTO v1 VALUES (1,10),(2,20)",
      "CREATE VIEW vv AS SELECT a, b*2 d FROM v1 WHERE a>0"],
     "SELECT a, d FROM vv WHERE d>10 ORDER BY a",
     "view predicate push"),
    ("view",
     ["CREATE TABLE v1(a INT, b INT)",
      "INSERT INTO v1 VALUES (1,10),(2,20)",
      "CREATE VIEW vv AS SELECT a, sum(b) t FROM v1 GROUP BY a"],
     "SELECT a, t FROM vv WHERE t>15 ORDER BY a",
     "agg view filter"),
]


# ============================================================ BATCH 2
# Second-batch surfaces for PG 16.x (deeper / less-fuzzed axes):
# LATERAL + window/agg nests, grouping sets over joins with HAVING,
# composite/ROW arrays + multi-unnest + WITH ORDINALITY, jsonpath ops,
# recursive CYCLE / SEARCH, named windows + EXCLUDE frames, DISTINCT+FILTER
# aggregates, partitionwise joins + UPDATE row movement + pruning,
# generated cols + CHECK / constraint_exclusion probes, numeric scale/NaN,
# AT TIME ZONE / date_trunc / extract / age / OVERLAPS / date_bin,
# position/overlay/translate + SIMILAR TO + regexp groups + COLLATE LIKE,
# parenthesized set-op chains, EXISTS-in-SELECT / NULL scalar subqueries,
# wide multi-row VALUES in FROM, ordered-set aggregates, ranges/multiranges,
# SQL/JSON predicates+constructors, and multi-thousand-row tables sized so
# the force_parallel axis can actually engage.
PG_TEMPLATES_B2: list[tuple[str, list[str], str, str]] = [
    # ------------------------------------------- lateral + window/agg
    ("lateral",
     ["CREATE TABLE t1(id INT, v INT)",
      "INSERT INTO t1 VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,1),(1,3),(2,5)"],
     "SELECT t1.id, s.w, s.rn FROM t1 CROSS JOIN LATERAL (SELECT w, row_number() OVER (ORDER BY w) AS rn FROM t2 WHERE t2.k=t1.id) s ORDER BY t1.id, s.rn",
     "window inside lateral"),
    ("lateral",
     ["CREATE TABLE t1(id INT)",
      "INSERT INTO t1 VALUES (1),(2),(9)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,1),(1,3),(2,5)"],
     "SELECT t1.id, s.cnt, s.tot FROM t1 LEFT JOIN LATERAL (SELECT count(*) AS cnt, sum(w) AS tot FROM t2 WHERE t2.k=t1.id) s ON true ORDER BY t1.id",
     "lateral agg empty->0"),
    ("lateral",
     ["CREATE TABLE t1(id INT)",
      "INSERT INTO t1 VALUES (1),(2)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,1),(1,3),(2,5),(2,7)"],
     "SELECT t1.id, s.w, s.mx FROM t1, LATERAL (SELECT w, (SELECT max(w) FROM t2 x WHERE x.k=t1.id) AS mx FROM t2 WHERE t2.k=t1.id) s ORDER BY t1.id, s.w",
     "nested corr scalar in lateral"),
    ("lateral",
     ["CREATE TABLE t1(id INT)",
      "INSERT INTO t1 VALUES (1),(2),(3)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,1),(2,5),(3,2)"],
     "SELECT t1.id, s.fw, s.c FROM t1 LEFT JOIN LATERAL (SELECT sum(w) FILTER (WHERE w>3) AS fw, count(*) AS c FROM t2 WHERE t2.k=t1.id) s ON true ORDER BY t1.id",
     "lateral FILTER agg"),
    ("lateral",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{3,1,2}'),(2,'{5,4}'),(3,'{}'),(4,NULL)"],
     "SELECT id, u, row_number() OVER (PARTITION BY id ORDER BY u) AS rn FROM a1, LATERAL unnest(arr) u ORDER BY id, u",
     "lateral unnest + outer window"),
    ("lateral",
     ["CREATE TABLE t1(id INT, v INT)",
      "INSERT INTO t1 VALUES (1,2),(2,3)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1),(2)"],
     "SELECT t1.id, s.i, s2.j FROM t1, LATERAL generate_series(1,t1.v) s(i), LATERAL (SELECT s.i*10+t1.id AS j) s2 ORDER BY t1.id, s.i",
     "chained laterals"),
    # ----------------------------------- grouping sets + join + having
    ("grouping",
     ["CREATE TABLE g1(a INT, v INT)",
      "INSERT INTO g1 VALUES (1,10),(1,20),(2,30)",
      "CREATE TABLE h1(k INT, w INT)",
      "INSERT INTO h1 VALUES (1,5),(2,7)"],
     "SELECT g1.a, h1.k, sum(g1.v*h1.w), grouping(g1.a, h1.k) FROM g1 JOIN h1 ON g1.a=h1.k GROUP BY GROUPING SETS ((g1.a,h1.k),(g1.a),()) ORDER BY 1 NULLS LAST, 2 NULLS LAST",
     "grouping sets over join"),
    ("grouping",
     ["CREATE TABLE g1(a INT, b INT, v INT)",
      "INSERT INTO g1 VALUES (1,1,10),(1,2,20),(2,1,30),(2,2,40)",
      "CREATE TABLE h1(a INT)",
      "INSERT INTO h1 VALUES (1),(2)"],
     "SELECT g1.a, g1.b, count(*) FROM g1 JOIN h1 ON g1.a=h1.a GROUP BY ROLLUP (g1.a, g1.b) HAVING count(*) >= 1 ORDER BY 1 NULLS LAST, 2 NULLS LAST",
     "rollup join having"),
    ("grouping",
     ["CREATE TABLE g1(a INT, b INT, v INT)",
      "INSERT INTO g1 VALUES (1,1,10),(1,2,20),(2,1,30),(2,2,40)"],
     "SELECT a, b, sum(v) FROM g1 GROUP BY CUBE (a,b) HAVING sum(v) > 40 ORDER BY 1 NULLS LAST, 2 NULLS LAST",
     "cube having threshold"),
    ("grouping",
     ["CREATE TABLE g1(a INT, b INT, v INT)",
      "INSERT INTO g1 VALUES (1,NULL,10),(1,2,20),(NULL,1,30),(2,2,40)"],
     "SELECT a, b, grouping(a) ga, grouping(b) gb, count(*) FROM g1 GROUP BY GROUPING SETS ((a),(b),(a,b),()) ORDER BY 1 NULLS LAST, 2 NULLS LAST, 3, 4",
     "grouping sets nulls"),
    ("grouping",
     ["CREATE TABLE g1(a INT, b INT, v INT)",
      "INSERT INTO g1 VALUES (1,1,10),(1,2,20),(2,1,30)"],
     "SELECT a, b, t FROM (SELECT a, b, sum(v) AS t, grouping(a,b) AS g FROM g1 GROUP BY GROUPING SETS ((a,b),(a),())) s WHERE g=0 ORDER BY a, b",
     "grouping() outer filter"),
    ("grouping",
     ["CREATE TABLE g1(a INT, v INT)",
      "INSERT INTO g1 VALUES (1,10),(1,20),(2,30),(3,40)"],
     "SELECT a, sum(v), count(*) FILTER (WHERE v>15) FROM g1 GROUP BY ROLLUP(a) HAVING grouping(a)=0 OR sum(v)>100 ORDER BY a NULLS LAST",
     "rollup grouping() in having"),
    # ----------------------------------- composite arrays / unnest
    ("array",
     ["CREATE TYPE pt AS (x INT, y INT)",
      "CREATE TABLE c1(id INT, arr pt[])",
      "INSERT INTO c1 VALUES (1,'{\"(1,2)\",\"(3,4)\"}'),(2,'{\"(5,6)\"}'),(3,'{}'),(4,NULL)"],
     "SELECT id, u.x, u.y FROM c1, LATERAL unnest(arr) u ORDER BY id, u.x NULLS LAST, u.y NULLS LAST",
     "composite array unnest"),
    ("array",
     ["CREATE TYPE pt2 AS (x INT, y INT)",
      "CREATE TABLE c1(id INT, arr pt2[])",
      "INSERT INTO c1 VALUES (1,'{\"(1,10)\",\"(2,20)\"}'),(2,'{\"(3,30)\"}')"],
     "SELECT id, sum(u.x), max(u.y) FROM c1, LATERAL unnest(arr) u GROUP BY id ORDER BY id",
     "agg over composite unnest"),
    ("array",
     ["CREATE TABLE a1(id INT, a INT[], b TEXT[])",
      "INSERT INTO a1 VALUES (1,'{10,20}','{x,y,z}'),(2,'{30,40,50}','{p}'),(3,'{}','{q}')"],
     "SELECT id, u.i, u.t FROM a1, LATERAL unnest(a, b) AS u(i,t) ORDER BY id, u.i NULLS LAST, u.t NULLS LAST",
     "multi-arg unnest ragged"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{7,8,9}'),(2,'{4}'),(3,'{}'),(4,NULL)"],
     "SELECT id, u.e, u.n FROM a1 LEFT JOIN LATERAL unnest(arr) WITH ORDINALITY AS u(e,n) ON true ORDER BY id, u.n NULLS LAST",
     "unnest ordinality left join"),
    ("array",
     ["CREATE TYPE pr AS (f1 INT, f2 TEXT)",
      "CREATE TABLE c1(id INT, r pr)",
      "INSERT INTO c1 VALUES (1,ROW(1,'a')::pr),(2,ROW(2,'b')::pr),(3,NULL)"],
     "SELECT id, (r).f1, (r).f2, r IS NOT NULL FROM c1 ORDER BY id",
     "composite column fields"),
    ("array",
     ["CREATE TABLE a1(id INT, v INT)",
      "INSERT INTO a1 VALUES (1,5),(1,3),(2,7)"],
     "SELECT id, array_agg(a1 ORDER BY v) FROM a1 GROUP BY id ORDER BY id",
     "array_agg whole row"),
    ("array",
     ["CREATE TABLE a1(id INT, arr INT[])",
      "INSERT INTO a1 VALUES (1,'{5,3,9,1}'),(2,'{8,8}'),(3,NULL)"],
     "SELECT id, u.e, u.n FROM a1, LATERAL unnest(arr) WITH ORDINALITY u(e,n) WHERE u.n <= 2 ORDER BY id, u.n",
     "ordinality filter"),
    ("array",
     ["CREATE TABLE a1(id INT, a INT[])",
      "INSERT INTO a1 VALUES (1,'{10,20,30}'),(2,'{40}')"],
     "SELECT id, u.g, u.e FROM a1, LATERAL ROWS FROM (generate_series(1,2), unnest(a1.a)) AS u(g,e) ORDER BY id, u.g, u.e NULLS LAST",
     "ROWS FROM lateral"),
    # ----------------------------------- jsonb / jsonpath
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":[1,2,3]}'),(2,'{\"a\":[4]}'),(3,'{\"b\":1}'),(4,NULL)"],
     "SELECT id, q FROM j1, LATERAL jsonb_path_query(j, '$.a[*]') q ORDER BY id, q",
     "jsonb_path_query elems"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":[1,5]}'),(2,'{\"a\":[2]}'),(3,'{}')"],
     "SELECT id FROM j1 WHERE jsonb_path_exists(j, '$.a[*] ? (@ > 3)') ORDER BY id",
     "jsonb_path_exists pred"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1,\"b\":2}'),(2,'{\"b\":3}'),(3,'{}')"],
     "SELECT id, kv.k, kv.v FROM j1, LATERAL jsonb_each_text(j) kv(k,v) ORDER BY id, kv.k",
     "jsonb_each_text pairs"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1,\"b\":2}'),(2,'{\"c\":3}')"],
     "SELECT id, jsonb_object_agg(kv.k, kv.v) FROM j1, LATERAL jsonb_each(j) kv(k,v) GROUP BY id ORDER BY id",
     "jsonb_object_agg roundtrip"),
    ("jsonb",
     ["CREATE TABLE m1(a INT, b TEXT)",
      "INSERT INTO m1 VALUES (1,'x'),(2,NULL)"],
     "SELECT a, to_jsonb(m1) FROM m1 ORDER BY a",
     "to_jsonb whole row"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":{\"b\":7}}'),(2,'{\"a\":{\"b\":8}}'),(3,'{\"a\":{}}')"],
     "SELECT id FROM j1 WHERE j @? '$.a.b ? (@ > 6)' ORDER BY id",
     "jsonpath @? operator"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":5}'),(2,'{\"a\":15}'),(3,'{}')"],
     "SELECT id FROM j1 WHERE j @@ '$.a > 10' ORDER BY id",
     "jsonpath @@ operator"),
    ("jsonb",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":[10,20]}'),(2,'{\"a\":[30]}')"],
     "SELECT id, jsonb_path_query_array(j, '$.a[*] ? (@ > 15)') FROM j1 ORDER BY id",
     "jsonb_path_query_array"),
    ("jsonb",
     ["CREATE TYPE pr3 AS (f1 INT, f2 TEXT)",
      "CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"f1\":1,\"f2\":\"a\"}'),(2,'{\"f1\":2}'),(3,'{}')"],
     "SELECT id, p.f1, p.f2 FROM j1, LATERAL jsonb_populate_record(NULL::pr3, j1.j) p ORDER BY id",
     "jsonb_populate_record"),
    # ----------------------------------- recursive CYCLE / SEARCH
    ("recursive",
     ["CREATE TABLE g1(src INT, dst INT)",
      "INSERT INTO g1 VALUES (1,2),(2,3),(3,1),(3,4),(4,5)"],
     "WITH RECURSIVE sg(node, depth) AS (SELECT g.dst, 0 FROM g1 g WHERE g.src=1 UNION ALL SELECT g.dst, sg.depth+1 FROM g1 g, sg WHERE g.src=sg.node) CYCLE node SET cyc USING pth SELECT node, depth, cyc FROM sg ORDER BY node, depth",
     "cycle detection"),
    ("recursive",
     ["CREATE TABLE r1(id INT, parent INT)",
      "INSERT INTO r1 VALUES (1,NULL),(2,1),(3,1),(4,2),(5,2),(6,3)"],
     "WITH RECURSIVE bfs AS (SELECT id, parent, 0 AS d FROM r1 WHERE parent IS NULL UNION ALL SELECT r.id, r.parent, b.d+1 FROM r1 r JOIN bfs b ON r.parent=b.id) SEARCH BREADTH FIRST BY id SET o SELECT id, d, o FROM bfs ORDER BY o",
     "search breadth first"),
    ("recursive",
     ["CREATE TABLE r1(id INT, parent INT)",
      "INSERT INTO r1 VALUES (1,NULL),(2,1),(3,1),(4,2),(5,3)"],
     "WITH RECURSIVE dfs AS (SELECT id, parent, 0 AS d FROM r1 WHERE parent IS NULL UNION ALL SELECT r.id, r.parent, s.d+1 FROM r1 r JOIN dfs s ON r.parent=s.id) SEARCH DEPTH FIRST BY id SET o SELECT id, d, o FROM dfs ORDER BY o",
     "search depth first"),
    ("recursive",
     ["CREATE TABLE g1(a INT, b INT)",
      "INSERT INTO g1 VALUES (1,2),(2,3),(3,4),(2,5),(5,5)"],
     "WITH RECURSIVE t(n) AS (SELECT a FROM g1 WHERE a=1 UNION SELECT g.b FROM g1 g JOIN t ON g.a=t.n) SELECT n FROM t ORDER BY n",
     "recursive union dedup selfloop"),
    ("recursive",
     ["CREATE TABLE r1(id INT, parent INT)",
      "INSERT INTO r1 VALUES (1,NULL),(2,1),(3,1),(4,2),(5,4)"],
     "WITH RECURSIVE tr AS (SELECT id, parent, 1 AS lvl, ARRAY[id] AS path FROM r1 WHERE parent IS NULL UNION ALL SELECT r.id, r.parent, t.lvl+1, t.path||r.id FROM r1 r JOIN tr t ON r.parent=t.id WHERE NOT r.id = ANY(t.path)) SELECT tr.id, tr.lvl, r1.parent FROM tr JOIN r1 ON tr.id=r1.id ORDER BY tr.id",
     "manual path cycle + join"),
    # ----------------------------------- window named/EXCLUDE/FILTER-DISTINCT
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,20),(1,30),(2,5),(2,15)"],
     "SELECT g, v, sum(v) OVER wa, max(v) OVER wb, count(*) OVER w FROM w1 WINDOW w AS (PARTITION BY g ORDER BY v), wa AS (w ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), wb AS (w ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) ORDER BY g, v",
     "named window chaining"),
    ("window",
     ["CREATE TABLE w1(g INT, v NUMERIC)",
      "INSERT INTO w1 VALUES (1,10),(1,10),(1,20),(1,30),(2,5)"],
     "SELECT g, v, sum(v) OVER (PARTITION BY g ORDER BY v RANGE BETWEEN 5 PRECEDING AND 10 FOLLOWING EXCLUDE TIES) FROM w1 ORDER BY g, v",
     "RANGE offset EXCLUDE TIES"),
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,10),(1,20),(2,5),(2,5)"],
     "SELECT g, v, count(*) OVER (PARTITION BY g ORDER BY v GROUPS BETWEEN 1 PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW) FROM w1 ORDER BY g, v",
     "GROUPS EXCLUDE CURRENT ROW"),
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,20),(1,30),(2,5),(2,15),(2,25)"],
     "SELECT g, v, sum(v) FILTER (WHERE v>10) OVER (PARTITION BY g ORDER BY v ROWS UNBOUNDED PRECEDING) FROM w1 ORDER BY g, v",
     "window FILTER running"),
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,10),(1,20),(2,5),(2,15)"],
     "SELECT g, count(DISTINCT v) FILTER (WHERE v>10), sum(DISTINCT v) FILTER (WHERE v<20), count(DISTINCT v) FROM w1 GROUP BY g ORDER BY g",
     "distinct aggs + FILTER"),
    ("window",
     ["CREATE TABLE w1(g INT, v INT)",
      "INSERT INTO w1 VALUES (1,10),(1,20),(2,5),(2,15),(2,25)"],
     "SELECT g, v, avg(v) OVER (PARTITION BY g ORDER BY v ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE GROUP), min(v) OVER (PARTITION BY g ORDER BY v DESC) FROM w1 ORDER BY g, v",
     "EXCLUDE GROUP + desc order"),
    # ----------------------------------- partitioned
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "CREATE TABLE q1(a INT, c INT) PARTITION BY RANGE (a)",
      "CREATE TABLE q1_0 PARTITION OF q1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE q1_1 PARTITION OF q1 FOR VALUES FROM (50) TO (100)",
      "INSERT INTO p1 VALUES (10,1),(20,2),(60,3),(70,4)",
      "INSERT INTO q1 VALUES (10,100),(20,200),(60,300),(90,400)"],
     "SELECT p1.a, p1.b, q1.c FROM p1 JOIN q1 ON p1.a=q1.a ORDER BY p1.a",
     "identical partitionwise join"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "INSERT INTO p1 VALUES (10,1),(20,2),(60,3),(70,4)",
      "UPDATE p1 SET a = a + 60 WHERE a < 30"],
     "SELECT a, b FROM p1 ORDER BY a",
     "update row movement then read"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY LIST (a)",
      "CREATE TABLE p1_a PARTITION OF p1 FOR VALUES IN (1,2,3)",
      "CREATE TABLE p1_b PARTITION OF p1 FOR VALUES IN (4,5,6)",
      "CREATE TABLE p1_d PARTITION OF p1 DEFAULT",
      "INSERT INTO p1 VALUES (1,10),(4,40),(7,70),(9,90)"],
     "SELECT a, b FROM p1 WHERE a IN (1,4,7) OR a = 9 ORDER BY a",
     "list prune IN/OR + default"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "INSERT INTO p1 VALUES (10,1),(20,2),(60,3),(70,4)",
      "CREATE INDEX pi_b ON p1(b)"],
     "SELECT a, b FROM p1 WHERE b = 3 OR b = 4 ORDER BY a",
     "partitioned index probe"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "CREATE TABLE p1_d PARTITION OF p1 DEFAULT",
      "INSERT INTO p1 VALUES (10,1),(60,3),(150,9)"],
     "SELECT a, b FROM p1 WHERE a >= 100 ORDER BY a",
     "default partition catch"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY HASH (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES WITH (MODULUS 4, REMAINDER 0)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES WITH (MODULUS 4, REMAINDER 1)",
      "CREATE TABLE p1_2 PARTITION OF p1 FOR VALUES WITH (MODULUS 4, REMAINDER 2)",
      "CREATE TABLE p1_3 PARTITION OF p1 FOR VALUES WITH (MODULUS 4, REMAINDER 3)",
      "INSERT INTO p1 SELECT i, i*10 FROM generate_series(1,24) i"],
     "SELECT a, b FROM p1 WHERE a = 5 OR a = 12 ORDER BY a",
     "hash prune eq"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "CREATE TABLE p1_2 PARTITION OF p1 FOR VALUES FROM (100) TO (200)",
      "INSERT INTO p1 SELECT i, i%7 FROM generate_series(1,150) i"],
     "SELECT (a/50) AS bucket, count(*), sum(b) FROM p1 GROUP BY 1 ORDER BY 1",
     "agg across partitions"),
    ("partition",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (50) TO (100)",
      "INSERT INTO p1 VALUES (10,1),(20,2),(60,3)",
      "CREATE TABLE q1(a INT, c INT) PARTITION BY RANGE (a)",
      "CREATE TABLE q1_0 PARTITION OF q1 FOR VALUES FROM (0) TO (30)",
      "CREATE TABLE q1_1 PARTITION OF q1 FOR VALUES FROM (30) TO (100)",
      "INSERT INTO q1 VALUES (10,9),(60,8)"],
     "SELECT p1.a, q1.c FROM p1 LEFT JOIN q1 ON p1.a=q1.a ORDER BY p1.a",
     "mismatched bounds join"),
    # ------------------------- generated cols / check / constraint_exclusion
    ("gen_col",
     ["CREATE TABLE g1(a INT CHECK (a BETWEEN 0 AND 100), b INT GENERATED ALWAYS AS (a*3) STORED)",
      "INSERT INTO g1(a) VALUES (0),(5),(33),(100)"],
     "SELECT a, b FROM g1 WHERE a >= -1 ORDER BY a",
     "generated + range check"),
    ("gen_col",
     ["CREATE TABLE g1(a INT, b INT GENERATED ALWAYS AS (a % 3) STORED, c INT CHECK (c > 0))",
      "INSERT INTO g1(a,c) VALUES (7,10),(9,5),(10,1)"],
     "SELECT a, b, c FROM g1 WHERE b = 0 OR c > 100 ORDER BY a",
     "generated + check sibling"),
    ("gen_col",
     ["CREATE TABLE g1(a INT, b INT GENERATED ALWAYS AS (a*2) STORED, UNIQUE(a,b))",
      "INSERT INTO g1(a) VALUES (1),(2),(3)"],
     "SELECT a, b FROM g1 WHERE b IN (2,4,8) ORDER BY a",
     "generated in unique + IN"),
    ("domain",
     ["CREATE TABLE d1(a INT CHECK (a>0), b INT CHECK (b BETWEEN 0 AND 10), v INT)",
      "INSERT INTO d1 VALUES (1,5,10),(2,0,20),(3,10,30)"],
     "SELECT a, b, v FROM d1 WHERE b < 11 AND a > -5 ORDER BY a",
     "two checks looser preds"),
    ("domain",
     ["CREATE TABLE d1(a INT, v INT)",
      "INSERT INTO d1 VALUES (1,10),(2,20)",
      "ALTER TABLE d1 ADD CONSTRAINT pos CHECK (a > 0) NOT VALID"],
     "SELECT a, v FROM d1 WHERE a > -1 ORDER BY a",
     "not-valid check"),
    ("domain",
     ["CREATE TABLE d1(a INT, CONSTRAINT lo CHECK (a >= 0), CONSTRAINT hi CHECK (a <= 50), v INT)",
      "INSERT INTO d1 VALUES (0,1),(25,2),(50,3)"],
     "SELECT a, v FROM d1 WHERE a >= -10 AND a <= 60 ORDER BY a",
     "named check pair"),
    # ----------------------------------- numeric edges
    ("numeric",
     ["CREATE TABLE n1(a NUMERIC(12,4), f FLOAT8)",
      "INSERT INTO n1 VALUES (0.1,0.1),(1.5,1.5),(2.675,2.675),(100.001,100.001)"],
     "SELECT a, f, a = f AS eq, a < f AS lt, a > f AS gt, CAST(f AS NUMERIC(12,4)) = a AS feq FROM n1 ORDER BY a",
     "numeric vs float8 cmp"),
    ("numeric",
     ["CREATE TABLE n1(a NUMERIC(10,2))",
      "INSERT INTO n1 VALUES (1.005),(2.675),(0.125),(-1.005),(9999999.995)"],
     "SELECT a, a::NUMERIC(10,1) AS a1, round(a,1) AS r1, trunc(a,1) AS t1 FROM n1 ORDER BY a",
     "scale narrowing cast"),
    ("numeric",
     ["CREATE TABLE n1(a NUMERIC)",
      "INSERT INTO n1 VALUES ('NaN'),('Infinity'),('-Infinity'),(1.5),(0),(-1.5)"],
     "SELECT a, a = 'NaN'::NUMERIC AS isnan_eq, a > 0 AS gt0, rank() OVER (ORDER BY a) FROM n1 ORDER BY a",
     "numeric NaN Inf order"),
    ("numeric",
     ["CREATE TABLE n1(a NUMERIC(38,20), b NUMERIC(38,20))",
      "INSERT INTO n1 VALUES (0.00000000000000000001, 999999999999999999.99),(123456789.123456789, 0.00000000000000000001)"],
     "SELECT a, b, a+b, a*b, b/a FROM n1 ORDER BY a",
     "extreme scale arith"),
    ("numeric",
     ["CREATE TABLE n1(a NUMERIC(10,3), b INT)",
      "INSERT INTO n1 VALUES (10.5,2),(7.25,3),(-9.5,4),(100,7)"],
     "SELECT a, b, mod(a, b::NUMERIC), a % b, div(a, b::NUMERIC), a/b FROM n1 ORDER BY a",
     "numeric mod div"),
    ("numeric",
     ["CREATE TABLE n1(a DOUBLE PRECISION, b NUMERIC(25,5))",
      "INSERT INTO n1 VALUES (1e308, 1e15),(-1e308,-1e15),(0.0,0.00001),('Infinity', 9.9)"],
     "SELECT a, b, a > b AS agtb, b > a AS bgta FROM n1 ORDER BY a",
     "float8 huge vs numeric"),
    # ----------------------------------- date / timestamp
    ("interval",
     ["CREATE TABLE i1(t TIMESTAMP, z TIMESTAMPTZ)",
      "INSERT INTO i1 VALUES ('2024-03-10 02:30:00','2024-03-10 02:30:00+00'),('2024-11-03 01:30:00','2024-11-03 01:30:00+00')"],
     "SELECT t, t AT TIME ZONE 'UTC', z AT TIME ZONE 'UTC', (z AT TIME ZONE 'America/New_York') AT TIME ZONE 'UTC' FROM i1 ORDER BY t",
     "at time zone roundtrip"),
    ("interval",
     ["CREATE TABLE i1(t TIMESTAMP)",
      "INSERT INTO i1 VALUES ('2024-03-15 10:45:30'),('2024-03-31 23:59:59'),('2024-01-01 00:00:00')"],
     "SELECT t, date_trunc('month',t) m, date_trunc('hour',t) h, date_trunc('quarter',t) q, date_trunc('week',t) w FROM i1 ORDER BY t",
     "date_trunc fields"),
    ("interval",
     ["CREATE TABLE i1(t TIMESTAMP, d DATE)",
      "INSERT INTO i1 VALUES ('2024-03-10 15:30:00','2024-03-10'),('2024-12-25 00:00:00','2024-12-25')"],
     "SELECT t, extract(epoch FROM t) e, extract(isodow FROM t) dw, extract(doy FROM d) dy, date_part('hour',t) hh FROM i1 ORDER BY t",
     "extract fields"),
    ("interval",
     ["CREATE TABLE i1(a TIMESTAMP, b TIMESTAMP)",
      "INSERT INTO i1 VALUES ('2024-01-15 10:00:00','2024-03-20 12:30:45'),('2000-02-29 00:00:00','2001-02-28 00:00:00')"],
     "SELECT a, b, age(b,a), justify_days(age(b,a)), justify_hours(INTERVAL '25 hours') FROM i1 ORDER BY a",
     "age + justify"),
    ("interval",
     ["CREATE TABLE i1(s TIMESTAMP, e TIMESTAMP, s2 TIMESTAMP, e2 TIMESTAMP)",
      "INSERT INTO i1 VALUES ('2024-01-01','2024-01-10','2024-01-05','2024-01-20'),('2024-02-01','2024-02-05','2024-02-10','2024-02-15'),('2024-03-01','2024-03-10','2024-03-01','2024-03-10')"],
     "SELECT s, (s,e) OVERLAPS (s2,e2) AS ov, (s,e) OVERLAPS (s2,s2) AS point FROM i1 ORDER BY s",
     "overlaps operator"),
    ("interval",
     ["CREATE TABLE i1(t TIMESTAMP)",
      "INSERT INTO i1 VALUES ('2024-03-10 10:07:00'),('2024-03-10 10:14:59'),('2024-03-10 10:15:00')"],
     "SELECT t, date_bin('15 minutes', t, TIMESTAMP '2001-01-01') b FROM i1 ORDER BY t",
     "date_bin"),
    ("interval",
     ["CREATE TABLE i1(d DATE)",
      "INSERT INTO i1 VALUES ('2024-02-29'),('2024-01-15'),('2023-12-31')"],
     "SELECT d, d - date_trunc('month', d)::date AS dom_off, make_date(extract(year FROM d)::int, extract(month FROM d)::int, 1) AS first FROM i1 ORDER BY d",
     "date arith + make_date"),
    # ----------------------------------- text ops
    ("string",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'hello world'),(2,'abcdef'),(3,'aaa bbb'),(4,'xyzzy')"],
     "SELECT id, position('b' IN s), overlay(s PLACING 'XX' FROM 2 FOR 3), translate(s,'ab','AB'), left(s,3), right(s,-2) FROM t1 ORDER BY id",
     "position overlay translate"),
    ("string",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'abc123'),(2,'ab12'),(3,'a1b2c3'),(4,'xyz'),(5,'12abc')"],
     "SELECT id FROM t1 WHERE s SIMILAR TO '[a-z]+[0-9]+' OR s SIMILAR TO 'x_y%' ORDER BY id",
     "similar to"),
    ("string",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'key=42'),(2,'k=7,x=9'),(3,'nope'),(4,'a=1,b=22,c=333')"],
     "SELECT id, m[1], m[2] FROM t1, LATERAL regexp_match(s, '([a-z]+)=([0-9]+)') m ORDER BY id, m[1] NULLS LAST, m[2] NULLS LAST",
     "regexp_match groups"),
    ("string",
     ["CREATE TABLE t1(id INT, s TEXT COLLATE \"C\")",
      "INSERT INTO t1 VALUES (1,'Apple'),(2,'apple'),(3,'Banana'),(4,'banana'),(5,'10')"],
     "SELECT id, s FROM t1 WHERE s LIKE 'a%' OR s ILIKE 'b%' ORDER BY id",
     "like with C collation"),
    ("string",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'a1b22c333'),(2,'x9'),(3,'none')"],
     "SELECT id, (regexp_match(s, '([0-9]+)([a-z]*)'))[1] g1, (regexp_match(s, '([0-9]+)([a-z]*)'))[2] g2, substring(s FROM '([a-z]+)([0-9]+)') FROM t1 ORDER BY id",
     "regexp group index"),
    ("string",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'foo_bar_baz'),(2,'a-b-c'),(3,'x  y')"],
     "SELECT id, split_part(s,'_',2), regexp_replace(s,'[_-]','+','g'), strpos(s,'b'), initcap(s) FROM t1 ORDER BY id",
     "split regex strpos"),
    ("string",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'abc'),(2,'Abc'),(3,'ABC'),(4,'abd')"],
     "SELECT id FROM t1 WHERE s ~* '^ab' AND s !~ 'z' ORDER BY id",
     "regex case ops"),
    # ----------------------------------- set op chains
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2),(3)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (2),(3),(4)",
      "CREATE TABLE s3(a INT)", "INSERT INTO s3 VALUES (3),(5)"],
     "SELECT u.a, s3.a FROM ((SELECT a FROM s1 UNION SELECT a FROM s2) INTERSECT SELECT a FROM s3) u JOIN s3 ON u.a=s3.a ORDER BY u.a",
     "paren union intersect join"),
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2),(3),(3)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (3),(3),(4)",
      "CREATE TABLE s3(a INT)", "INSERT INTO s3 VALUES (3)"],
     "SELECT u.a, s3.a FROM (SELECT a FROM s1 UNION ALL SELECT a FROM s2 EXCEPT SELECT a FROM s3) u JOIN s3 ON true ORDER BY u.a",
     "unionall except precedence"),
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2),(NULL)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (2),(NULL),(4)",
      "CREATE TABLE s3(a INT)", "INSERT INTO s3 VALUES (1),(2)"],
     "SELECT u.a, s3.a FROM ((SELECT a FROM s1 EXCEPT SELECT a FROM s2) UNION ALL (SELECT a FROM s2 EXCEPT SELECT a FROM s1)) u LEFT JOIN s3 ON u.a=s3.a ORDER BY u.a NULLS LAST, s3.a NULLS LAST",
     "symmetric difference nulls"),
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2),(2),(3)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (2),(2),(4)"],
     "SELECT u.a, count(*) FROM (SELECT a FROM s1 INTERSECT ALL SELECT a FROM s2) u, s1 WHERE s1.a >= u.a GROUP BY u.a ORDER BY u.a",
     "intersect all then agg"),
    ("setop",
     ["CREATE TABLE s1(a INT)", "INSERT INTO s1 VALUES (1),(2)",
      "CREATE TABLE s2(a INT)", "INSERT INTO s2 VALUES (2),(3)",
      "CREATE TABLE s3(a INT)", "INSERT INTO s3 VALUES (2),(4)"],
     "SELECT u.a FROM (SELECT a FROM s1 UNION SELECT a FROM s2 UNION SELECT a FROM s3) u WHERE u.a > ALL (SELECT a/2 FROM s3) ORDER BY u.a",
     "3-way union + ALL"),
    # ----------------------------------- subqueries
    ("subquery",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2),(3),(NULL)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1),(3)"],
     "SELECT a, EXISTS (SELECT 1 FROM t2 WHERE t2.k=t1.a) AS e, NOT EXISTS (SELECT 1 FROM t2 WHERE t2.k=t1.a+1) AS ne FROM t1 ORDER BY a NULLS LAST",
     "exists in select clause"),
    ("subquery",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2),(9)",
      "CREATE TABLE t2(k INT, w TEXT)",
      "INSERT INTO t2 VALUES (1,'one'),(2,'two')"],
     "SELECT a, (SELECT w FROM t2 WHERE t2.k=t1.a) AS w FROM t1 ORDER BY a",
     "scalar subq null miss"),
    ("subquery",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2),(3)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1),(1),(2)"],
     "SELECT a FROM t1 WHERE (SELECT count(*) FROM t2 WHERE t2.k=t1.a) BETWEEN 1 AND 1 ORDER BY a",
     "scalar count in where"),
    ("subquery",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (1,5),(2,15),(3,25)",
      "CREATE TABLE t2(k INT, w INT)",
      "INSERT INTO t2 VALUES (1,10),(2,10),(3,30)"],
     "SELECT t1.a FROM t1 WHERE t1.b < SOME (SELECT w FROM t2 WHERE t2.k <> t1.a) ORDER BY t1.a",
     "SOME correlated anti"),
    ("subquery",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2),(3)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1),(2)"],
     "SELECT a FROM t1 GROUP BY a HAVING EXISTS (SELECT 1 FROM t2 WHERE t2.k=t1.a) ORDER BY a",
     "exists in having"),
    ("subquery",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (1),(2)",
      "CREATE TABLE t3(m INT)",
      "INSERT INTO t3 VALUES (1)"],
     "SELECT a FROM t1 WHERE EXISTS (SELECT 1 FROM t2 WHERE t2.k=t1.a AND EXISTS (SELECT 1 FROM t3 WHERE t3.m=t2.k)) ORDER BY a",
     "doubly nested exists"),
    # ----------------------------------- VALUES
    ("values",
     ["CREATE TABLE v1(a INT, b TEXT, c NUMERIC, d BOOL)",
      "INSERT INTO v1 VALUES (1,'x',1.5,true),(2,'y',2.5,false)"],
     "SELECT v.a, v.b, v1.d FROM (VALUES (1,'x',9.9),(3,'z',0.0),(2,'y',5.5)) v(a,b,c) JOIN v1 ON v.a=v1.a AND v.b=v1.b ORDER BY v.a",
     "values in from join"),
    ("values",
     ["CREATE TABLE v1(a INT)",
      "INSERT INTO v1 VALUES (1),(2),(3)"],
     "SELECT x.c1, x.c2, x.c3, x.c4, x.c5, v1.a FROM (VALUES (1,10,100,'p',true),(2,20,200,'q',false),(3,30,300,'r',true)) x(c1,c2,c3,c4,c5) LEFT JOIN v1 ON x.c1=v1.a ORDER BY x.c1",
     "wide values row"),
    ("values",
     ["CREATE TABLE v1(a INT)",
      "INSERT INTO v1 VALUES (1),(2)"],
     "SELECT a FROM v1 WHERE (a, a*2) IN (VALUES (1,2),(2,4),(5,5)) ORDER BY a",
     "row IN values"),
    ("values",
     ["CREATE TABLE v1(a INT, t TEXT)",
      "INSERT INTO v1 VALUES (1,'a'),(2,'b'),(3,'c')"],
     "SELECT u.i, v1.t FROM v1 RIGHT JOIN (VALUES (1),(2),(4)) u(i) ON v1.a=u.i ORDER BY u.i",
     "values right join"),
    # ----------------------------------- extra surfaces
    ("misc",
     ["CREATE TABLE e1(a INT, b INT)",
      "INSERT INTO e1 VALUES (1,NULL),(NULL,NULL),(NULL,2),(3,3)"],
     "SELECT a, b, a IS DISTINCT FROM b AS d, a IS NOT DISTINCT FROM b AS nd FROM e1 ORDER BY a NULLS LAST, b NULLS LAST",
     "null-safe compare"),
    ("misc",
     ["CREATE TABLE o1(g INT, v INT)",
      "INSERT INTO o1 VALUES (1,10),(1,20),(1,30),(2,5),(2,15)"],
     "SELECT g, percentile_cont(0.5) WITHIN GROUP (ORDER BY v), mode() WITHIN GROUP (ORDER BY v), percentile_disc(0.9) WITHIN GROUP (ORDER BY v) FROM o1 GROUP BY g ORDER BY g",
     "ordered-set aggregates"),
    ("misc",
     ["CREATE TABLE o1(g INT, v INT, b BOOL)",
      "INSERT INTO o1 VALUES (1,10,true),(1,20,false),(2,5,true),(2,15,true)"],
     "SELECT g, bool_and(b), bool_or(b), every(b), bit_and(v), bit_or(v), string_agg(DISTINCT v::text, ',' ORDER BY v::text) FROM o1 GROUP BY g ORDER BY g",
     "bool bit string aggs"),
    ("range",
     ["CREATE TABLE r1(a INT, r INT4RANGE)",
      "INSERT INTO r1 VALUES (1,'[1,5)'),(2,'[3,8)'),(3,'[10,20)'),(4,'empty')"],
     "SELECT a, r, lower(r), upper(r), isempty(r), r && int4range(4,7) AS ov FROM r1 ORDER BY a",
     "int4range ops"),
    ("range",
     ["CREATE TABLE r1(a INT, r NUMRANGE)",
      "INSERT INTO r1 VALUES (1,'[1.5,5.5)'),(2,'(3,8]'),(3,'[,)')"],
     "SELECT a, r, r @> 4.0 AS has4, r -|- numrange(1.5,5.5) AS adj FROM r1 ORDER BY a",
     "numrange contains adjacent"),
    ("range",
     ["CREATE TABLE r1(a INT, m INT4MULTIRANGE)",
      "INSERT INTO r1 VALUES (1,'{[1,5),[10,20)}'),(2,'{[3,4]}'),(3,'{}')"],
     "SELECT a, m, m @> 4 AS has4, m && int4multirange('{[4,6)}') AS ov FROM r1 ORDER BY a",
     "multirange ops"),
    ("tsvector",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'the quick brown fox'),(2,'lazy dog sleeps'),(3,'foxes and dogs')"],
     "SELECT id FROM t1 WHERE to_tsvector('english', s) @@ to_tsquery('english','fox') ORDER BY id",
     "tsvector match"),
    ("misc",
     ["CREATE TABLE f1(a INT, b INT)",
      "INSERT INTO f1 VALUES (1,5),(2,5),(3,5),(4,9)"],
     "SELECT a, b FROM f1 ORDER BY a FETCH FIRST 2 ROWS WITH TIES",
     "fetch with ties"),
    ("misc",
     ["CREATE TABLE f1(a INT)",
      "INSERT INTO f1 VALUES (1),(2),(3),(4),(5)"],
     "SELECT a FROM f1 ORDER BY a OFFSET 1 ROWS FETCH NEXT 2 ROWS ONLY",
     "offset fetch"),
    ("misc",
     ["CREATE TABLE t1(a INT, b INT, c INT)",
      "INSERT INTO t1 VALUES (1,NULL,3),(NULL,2,NULL),(NULL,NULL,NULL),(4,5,6)"],
     "SELECT a, b, c, greatest(a,b,c), least(a,b,c), num_nonnulls(a,b,c), num_nulls(a,b,c) FROM t1 ORDER BY a NULLS LAST, b NULLS LAST",
     "greatest null semantics"),
    ("joins",
     ["CREATE TABLE j1(a INT)", "INSERT INTO j1 VALUES (1),(2),(3)",
      "CREATE TABLE j2(a INT)", "INSERT INTO j2 VALUES (1),(2)",
      "CREATE TABLE j3(a INT)", "INSERT INTO j3 VALUES (1),(3)",
      "CREATE TABLE j4(a INT)", "INSERT INTO j4 VALUES (1)",
      "CREATE TABLE j5(a INT)", "INSERT INTO j5 VALUES (1),(2)",
      "CREATE TABLE j6(a INT)", "INSERT INTO j6 VALUES (1)"],
     "SELECT count(*) FROM j1 JOIN j2 ON j1.a=j2.a JOIN j3 ON j2.a=j3.a JOIN j4 ON j3.a=j4.a JOIN j5 ON j4.a=j5.a JOIN j6 ON j5.a=j6.a",
     "6-way star geqo"),
    ("joins",
     ["CREATE TABLE j1(a INT, b INT)", "INSERT INTO j1 VALUES (1,1),(2,2)",
      "CREATE TABLE j2(a INT)", "INSERT INTO j2 VALUES (1),(2)",
      "CREATE TABLE j3(a INT)", "INSERT INTO j3 VALUES (1)"],
     "SELECT j1.a FROM j1 LEFT JOIN j2 ON j1.a=j2.a RIGHT JOIN j3 ON j2.a=j3.a ORDER BY j1.a NULLS LAST",
     "left right join mix"),
    ("joins",
     ["CREATE TABLE j1(a INT)", "INSERT INTO j1 VALUES (1),(2),(3)",
      "CREATE TABLE j2(a INT)", "INSERT INTO j2 VALUES (1),(2)"],
     "SELECT j1.a, j2.a FROM j1 JOIN j2 ON j1.a=j2.a AND EXISTS (SELECT 1 FROM j2 x WHERE x.a=j1.a) ORDER BY 1, 2",
     "exists in join on"),
    ("misc",
     ["CREATE TABLE t1(a INT)",
      "INSERT INTO t1 VALUES (1),(2),(2),(3)",
      "CREATE TABLE t2(k INT)",
      "INSERT INTO t2 VALUES (2),(2),(3)"],
     "SELECT DISTINCT a FROM t1 WHERE a IN (SELECT k FROM t2) ORDER BY a",
     "semijoin distinct"),
    ("parallel",
     ["CREATE TABLE big1(a INT, b INT)",
      "INSERT INTO big1 SELECT i, i%97 FROM generate_series(1,4000) i"],
     "SELECT b, count(*), sum(a) FROM big1 GROUP BY b ORDER BY b",
     "4k rows group agg"),
    ("parallel",
     ["CREATE TABLE big1(a INT, b INT)",
      "INSERT INTO big1 SELECT i, i%50 FROM generate_series(1,3000) i",
      "CREATE TABLE big2(a INT, c INT)",
      "INSERT INTO big2 SELECT i, i*2 FROM generate_series(1,3000) i"],
     "SELECT count(*) FROM big1 JOIN big2 ON big1.a=big2.a",
     "3k join parallel bait"),
    ("parallel",
     ["CREATE TABLE big1(a INT, b TEXT)",
      "INSERT INTO big1 SELECT i, 'v'||(i%200) FROM generate_series(1,5000) i",
      "CREATE INDEX big1_b ON big1(b)"],
     "SELECT b, count(*) FROM big1 GROUP BY b ORDER BY b",
     "5k text group indexed"),
    ("sqljson",
     ["CREATE TABLE t1(id INT, s TEXT, j JSONB)",
      "INSERT INTO t1 VALUES (1,'{\"a\":1}','{\"a\":1}'),(2,'[1,2]','[1,2]'),(3,'nope','7')"],
     "SELECT id, s IS JSON, s IS JSON OBJECT, s IS JSON SCALAR, j IS JSON ARRAY FROM t1 ORDER BY id",
     "is json predicates"),
    ("sqljson",
     ["CREATE TABLE t1(k TEXT, v INT)",
      "INSERT INTO t1 VALUES ('a',1),('b',2),('c',NULL)"],
     "SELECT JSON_OBJECTAGG(k: v) FROM t1",
     "json_objectagg"),
    ("sqljson",
     ["CREATE TABLE t1(id INT, v INT)",
      "INSERT INTO t1 VALUES (1,5),(1,3),(2,7)"],
     "SELECT id, JSON_ARRAYAGG(v ORDER BY v) FROM t1 GROUP BY id ORDER BY id",
     "json_arrayagg ordered"),
    ("misc",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (1,10),(2,20),(3,30)"],
     "SELECT a FROM t1 WHERE a IN (1,2) AND b NOT IN (10,99) OR (a,b) IN ((3,30)) ORDER BY a",
     "in-list mix"),
    ("misc",
     ["CREATE TABLE h1(a INT, v INT)",
      "INSERT INTO h1 VALUES (1,5),(1,15),(2,10),(2,10)"],
     "SELECT a FROM h1 GROUP BY a HAVING count(DISTINCT v) > 1 OR sum(v) FILTER (WHERE v>10) > 10 ORDER BY a",
     "having distinct+filter"),
    ("misc",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (NULL,1),(1,NULL),(2,2),(NULL,NULL)"],
     "SELECT a, b FROM t1 ORDER BY a NULLS FIRST, b NULLS LAST",
     "nulls first last"),
    ("misc",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (1,NULL),(1,NULL),(NULL,1),(2,2)"],
     "SELECT DISTINCT a, b FROM t1 ORDER BY a NULLS LAST, b NULLS LAST",
     "distinct null dedup"),
    ("misc",
     ["CREATE TABLE t1(g INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'b'),(1,'a'),(2,'c'),(2,'a')"],
     "SELECT g, string_agg(s, ':' ORDER BY s DESC), array_agg(s ORDER BY s) FROM t1 GROUP BY g ORDER BY g",
     "ordered string array agg"),
    ("misc",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (1,2),(2,1),(3,3),(NULL,1)"],
     "SELECT a, b FROM t1 WHERE (a,b) < (2,2) OR (a,b) IS NOT NULL ORDER BY a NULLS LAST, b",
     "row-wise compare"),
    ("misc",
     ["CREATE TABLE t1(a INT, b INT)",
      "INSERT INTO t1 VALUES (1,NULL),(NULL,2)"],
     "SELECT a, b, a IS NOT NULL AND b IS NOT NULL AS both, NOT (a IS NULL OR b IS NULL) AS neg FROM t1 ORDER BY a NULLS LAST, b NULLS LAST",
     "3vl equivalence probe"),
    ("misc",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'123x'),(2,'42'),(3,'1e5'),(4,'-7')"],
     "SELECT id, pg_input_is_valid(s,'int4'), pg_input_is_valid(s,'float8') FROM t1 ORDER BY id",
     "pg_input_is_valid"),
    ("misc",
     ["CREATE TABLE s1(a INT, b INT)",
      "INSERT INTO s1 VALUES (1,NULL),(NULL,2)",
      "CREATE TABLE s2(a INT, b INT)",
      "INSERT INTO s2 VALUES (1,NULL),(NULL,2),(3,3)"],
     "SELECT u.a, u.b FROM (SELECT a,b FROM s1 INTERSECT SELECT a,b FROM s2) u ORDER BY u.a NULLS LAST, u.b NULLS LAST",
     "intersect nulls equal"),
    ("misc",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'a.b.c'),(2,'x,y'),(3,'  pad  ')"],
     "SELECT id, string_to_array(s,'.'), array_to_string(string_to_array(s,'.'),'-'), btrim(s), lpad(s,8,'*') FROM t1 ORDER BY id",
     "string array fns"),
]


# ============================================================ BATCH 3 (R2)
# Third-batch surfaces: features introduced in PG 14/15/16 specifically.
# SQL/JSON constructors + IS JSON predicates (16), multiranges (14/15),
# MERGE deeper shapes (15), incremental-sort/MEMOIZE/work_mem bait,
# domains over composite/array, generated+domain+expression indexes,
# parallel-safety probes (debug_parallel_query bait), jsonb subscripting (14)
# and jsonpath edge cases, non-decimal/underscored numeric literals (16),
# any_value / range_intersect_agg (16), UNIQUE NULLS NOT DISTINCT (15),
# interval fractional units (16), SUBSTRING ... FOR (14).
# MERGE runs as the last setup statement; the SELECT observes post-merge state.
PG_TEMPLATES_R2: list[tuple[str, list[str], str, str]] = [
    # ----------------------------------- SQL/JSON (PG16)
    ("sqljson16",
     ["CREATE TABLE j1(id INT, s TEXT)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1}'),(2,'[1,2]'),(3,'\"x\"'),(4,'7'),(5,'bad'),(6,NULL),(7,'{\"a\":1,\"a\":2}')"],
     "SELECT id, s IS JSON, s IS JSON VALUE, s IS JSON SCALAR, s IS JSON OBJECT, s IS JSON ARRAY FROM j1 ORDER BY id",
     "is json type keywords"),
    ("sqljson16",
     ["CREATE TABLE j1(id INT, s TEXT)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1,\"b\":2}'),(2,'{\"a\":1,\"a\":2}'),(3,'[1,2]'),(4,'null'),(5,'{\"a\":{\"x\":1},\"a\":{\"x\":2}}'),(6,'[{\"k\":1,\"k\":1}]')"],
     "SELECT id, s IS JSON WITH UNIQUE KEYS, s IS JSON WITHOUT UNIQUE KEYS, s IS JSON OBJECT WITH UNIQUE KEYS FROM j1 ORDER BY id",
     "is json unique keys recursive"),
    ("sqljson16",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1}'),(2,'[3]'),(3,'\"s\"'),(4,NULL),(5,'{\"a\":1,\"b\":{\"x\":1}}')"],
     "SELECT id, j IS JSON, j IS JSON OBJECT, j IS JSON ARRAY, j IS JSON SCALAR, j IS JSON WITH UNIQUE KEYS FROM j1 ORDER BY id",
     "is json on jsonb col"),
    ("sqljson16",
     ["CREATE TABLE j1(id INT, j JSON)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1,\"a\":2}'),(2,'{\"b\":3}'),(3,'[1]'),(4,'null')"],
     "SELECT id, j IS JSON WITH UNIQUE KEYS, j::text FROM j1 ORDER BY id",
     "is json on json type"),
    ("sqljson16",
     ["CREATE TABLE j1(k TEXT, v INT)",
      "INSERT INTO j1 VALUES ('a',1),('b',NULL),('c',3),('a',9)"],
     "SELECT JSON_OBJECTAGG(k: v)::jsonb::text AS jb, JSON_OBJECTAGG(k: v)::text AS jt FROM j1",
     "objectagg dup keys json vs jsonb"),
    ("sqljson16",
     ["CREATE TABLE j1(k TEXT, v INT)",
      "INSERT INTO j1 VALUES ('a',1),('b',NULL),('c',3)"],
     "SELECT JSON_OBJECTAGG(k: v NULL ON NULL)::text AS nul, JSON_OBJECTAGG(k: v ABSENT ON NULL)::text AS abs FROM j1",
     "objectagg null vs absent"),
    ("sqljson16",
     ["CREATE TABLE j1(k TEXT, v INT)",
      "INSERT INTO j1 VALUES ('b',1),('a',2),('c',NULL)"],
     "SELECT (JSON_OBJECTAGG(k: v RETURNING jsonb))::text FROM j1",
     "objectagg returning jsonb"),
    ("sqljson16",
     ["CREATE TABLE j1(id INT, v INT)",
      "INSERT INTO j1 VALUES (1,5),(1,3),(2,NULL),(2,9)"],
     "SELECT id, JSON_ARRAYAGG(v ORDER BY v NULLS LAST) AS dflt, JSON_ARRAYAGG(v ORDER BY v NULLS LAST ABSENT ON NULL) AS abs, JSON_ARRAYAGG(v ORDER BY v NULLS LAST NULL ON NULL) AS nul FROM j1 GROUP BY id ORDER BY id",
     "arrayagg null modes"),
    ("sqljson16",
     ["CREATE TABLE j1(id INT, a INT, t TEXT, j JSONB)",
      "INSERT INTO j1 VALUES (1,5,'x','{\"k\":1}'),(2,NULL,NULL,NULL)"],
     "SELECT id, JSON_OBJECT('a': a, 't': t, 'j': j FORMAT JSON, 'n': NULL ABSENT ON NULL)::text FROM j1 ORDER BY id",
     "json_object format json + absent"),
    ("sqljson16",
     ["CREATE TABLE j1(a INT)",
      "INSERT INTO j1 VALUES (1),(NULL),(3)"],
     "SELECT JSON_ARRAY(a, a*10, 'txt', NULL, true NULL ON NULL)::text AS nul, JSON_ARRAY(a, a*10, 'txt', NULL, true ABSENT ON NULL)::text AS abs FROM j1 ORDER BY a NULLS LAST",
     "json_array list null modes"),
    ("sqljson16",
     [],
     "SELECT JSON_ARRAY(SELECT x FROM (VALUES (3),(1),(2)) v(x) ORDER BY x)::text AS arr",
     "json_array query form"),
    ("sqljson16",
     ["CREATE TABLE j1(a INT)",
      "INSERT INTO j1 VALUES (1),(2)"],
     "SELECT JSON_ARRAY(SELECT a*3 FROM j1 ORDER BY a RETURNING jsonb)::text AS arr FROM j1 ORDER BY a",
     "json_array query returning jsonb"),
    ("sqljson16",
     ["CREATE TABLE j1(a INT)",
      "INSERT INTO j1 VALUES (3),(1),(2),(1)"],
     "SELECT JSON_ARRAYAGG(a ORDER BY a RETURNING jsonb)::text AS jb, JSON_ARRAYAGG(a ORDER BY a)::text AS jt FROM j1",
     "arrayagg returning types"),
    ("sqljson16",
     ["CREATE TABLE j1(k TEXT, v INT)",
      "INSERT INTO j1 VALUES ('a',1),('b',2),('a',3)"],
     "SELECT JSON_OBJECTAGG(k: v WITHOUT UNIQUE KEYS)::text AS jt FROM j1",
     "objectagg without unique keeps dups"),
    ("sqljson16",
     ["CREATE TABLE j1(g INT, a INT)",
      "INSERT INTO j1 VALUES (1,5),(1,3),(2,7),(2,1)"],
     "SELECT g, JSON_ARRAYAGG(a ORDER BY a) FILTER (WHERE a > 2) AS f FROM j1 GROUP BY g ORDER BY g",
     "arrayagg filter clause"),
    ("sqljson16",
     ["CREATE TABLE j1(id INT, s TEXT)",
      "INSERT INTO j1 VALUES (1,'{\"k\":1}'),(2,'plain'),(3,'[1,2]')"],
     "SELECT id, JSON_OBJECT('v': s FORMAT JSON)::text AS raw, JSON_OBJECT('v': s)::text AS cooked FROM j1 ORDER BY id",
     "format json raw embed"),
    ("sqljson16",
     ["CREATE TABLE j1(k TEXT, v INT)",
      "INSERT INTO j1 VALUES ('a',1),('a',2)"],
     "SELECT JSON_OBJECTAGG(k: v WITH UNIQUE KEYS) FROM j1",
     "objectagg unique keys error"),
    # ----------------------------------- multiranges (PG14/15/16)
    ("multirange",
     ["CREATE TABLE r1(g INT, r INT4RANGE)",
      "INSERT INTO r1 VALUES (1,'[1,5)'),(1,'[3,8)'),(1,'empty'),(2,'[10,20)'),(3,NULL)"],
     "SELECT g, range_agg(r)::text FROM r1 GROUP BY g ORDER BY g",
     "range_agg"),
    ("multirange",
     ["CREATE TABLE r1(g INT, r INT4RANGE)",
      "INSERT INTO r1 VALUES (1,'[1,5)'),(1,'[8,12)'),(2,'[10,20)'),(2,'[15,25)')"],
     "SELECT g, range_intersect_agg(r)::text FROM r1 GROUP BY g ORDER BY g",
     "range_intersect_agg pg16"),
    ("multirange",
     ["CREATE TABLE r1(id INT, m INT4MULTIRANGE)",
      "INSERT INTO r1 VALUES (1,'{[1,5),[10,20)}'),(2,'{[3,4]}'),(3,'{}'),(4,NULL)"],
     "SELECT id, u.r::text AS r, lower(u.r), upper(u.r) FROM r1 LEFT JOIN LATERAL unnest(m) u(r) ON true ORDER BY id, u.r NULLS LAST",
     "unnest multirange pg15"),
    ("multirange",
     ["CREATE TABLE r1(id INT, a INT4MULTIRANGE, b INT4MULTIRANGE)",
      "INSERT INTO r1 VALUES (1,'{[1,5),[7,9)}','{[2,8)}'),(2,'{[1,3)}','{[5,6)}'),(3,'{}','{[1,9)}')"],
     "SELECT id, (a + b)::text AS uni, (a - b)::text AS dif, (a * b)::text AS isect FROM r1 ORDER BY id",
     "multirange arith"),
    ("multirange",
     ["CREATE TABLE r1(id INT, m INT4MULTIRANGE)",
      "INSERT INTO r1 VALUES (1,'{[1,3),[2,5),[4,6)}'),(2,'{[10,10)}'),(3,'{[5,5]}'),(4,'{[1,1),(1,1]}')"],
     "SELECT id, m::text, m = '{[1,6)}'::int4multirange AS eq16, isempty(m) FROM r1 ORDER BY id",
     "multirange canonicalization"),
    ("multirange",
     ["CREATE TABLE r1(id INT, m NUMMULTIRANGE)",
      "INSERT INTO r1 VALUES (1,'{[1.5,5.5),[10,)}'),(2,'{(,0]}'),(3,'{}')"],
     "SELECT id, lower(m), upper(m), lower_inf(m), upper_inf(m), m @> 4.5 AS has45 FROM r1 ORDER BY id",
     "nummultirange infinities"),
    ("multirange",
     ["CREATE TABLE r1(id INT, m TSTZMULTIRANGE)",
      "INSERT INTO r1 VALUES (1,'{[2024-01-01,2024-01-10),[2024-02-01,2024-02-05)}'),(2,'{}')"],
     "SELECT id, m @> timestamptz '2024-01-05' AS jan5, m @> timestamptz '2024-01-15' AS jan15, (m -|- tstzmultirange('{[2024-01-09,2024-01-30)}')) AS adj FROM r1 ORDER BY id",
     "tstzmultirange contains adjacent"),
    ("multirange",
     ["CREATE TABLE r1(id INT, m INT4MULTIRANGE)",
      "INSERT INTO r1 VALUES (1,'{[1,5),[10,20)}'),(2,'{[3,4]}'),(3,'{}')"],
     "SELECT id, range_agg(u.r)::text = m::text AS roundtrip, range_agg(u.r)::text AS agg FROM r1 LEFT JOIN LATERAL unnest(m) u(r) ON true GROUP BY id, m ORDER BY id",
     "unnest range_agg roundtrip"),
    ("multirange",
     ["CREATE TABLE r1(id INT, r INT4RANGE)",
      "INSERT INTO r1 VALUES (1,'[1,5)'),(2,'[3,8)'),(3,'[10,20)'),(4,'empty')"],
     "SELECT id, r::int4multirange::text AS mr, r -|- int4range(5,10) AS adj, r << int4range(10,20) AS before, int4range(0,1) >> r AS after FROM r1 ORDER BY id",
     "range cast + position ops"),
    # ----------------------------------- MERGE (PG15) deeper shapes
    ("merge",
     ["CREATE TABLE mt(k INT PRIMARY KEY, v INT)",
      "INSERT INTO mt VALUES (1,10),(2,20)",
      "CREATE TABLE ms(k INT, w INT)",
      "INSERT INTO ms VALUES (1,99),(3,30),(4,NULL)",
      "MERGE INTO mt USING ms ON mt.k=ms.k WHEN MATCHED THEN UPDATE SET v=ms.w WHEN NOT MATCHED THEN INSERT VALUES (ms.k, ms.w)"],
     "SELECT k, v FROM mt ORDER BY k",
     "merge basic"),
    ("merge",
     ["CREATE TABLE mt(k INT PRIMARY KEY, v INT)",
      "INSERT INTO mt VALUES (1,10),(2,20),(5,50)",
      "MERGE INTO mt USING (SELECT k, w*10 AS w FROM (VALUES (1,9),(2,1),(5,9),(7,3)) s(k,w)) q ON mt.k=q.k WHEN MATCHED AND mt.v < q.w THEN UPDATE SET v=q.w WHEN MATCHED THEN DELETE WHEN NOT MATCHED THEN INSERT VALUES (q.k,q.w)"],
     "SELECT k, v FROM mt ORDER BY k",
     "merge conditional clauses"),
    ("merge",
     ["CREATE TABLE mt(k INT PRIMARY KEY, v INT)",
      "INSERT INTO mt VALUES (1,10),(2,20)",
      "MERGE INTO mt USING (WITH w AS (SELECT 1 AS k, 77 AS v UNION ALL SELECT 9, 88) SELECT * FROM w) s ON mt.k=s.k WHEN MATCHED THEN UPDATE SET v=s.v WHEN NOT MATCHED THEN INSERT VALUES (s.k, s.v)"],
     "SELECT k, v FROM mt ORDER BY k",
     "merge cte inside using"),
    ("merge",
     ["CREATE TABLE mp(k INT, v INT) PARTITION BY RANGE (k)",
      "CREATE TABLE mp0 PARTITION OF mp FOR VALUES FROM (0) TO (50)",
      "CREATE TABLE mp1 PARTITION OF mp FOR VALUES FROM (50) TO (200)",
      "INSERT INTO mp VALUES (10,1),(60,2)",
      "MERGE INTO mp USING (VALUES (10,70),(60,5)) s(k,nk) ON mp.k=s.k WHEN MATCHED AND s.nk >= 50 THEN UPDATE SET k=s.nk WHEN MATCHED THEN UPDATE SET v=v*100"],
     "SELECT k, v FROM mp ORDER BY k",
     "merge partition row movement"),
    ("merge",
     ["CREATE TABLE mt(k INT PRIMARY KEY, v INT)",
      "INSERT INTO mt VALUES (1,1),(4,4)",
      "CREATE FUNCTION mf() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.v := NEW.v + 1; RETURN NEW; END $$",
      "CREATE TRIGGER mtrg BEFORE INSERT OR UPDATE ON mt FOR EACH ROW EXECUTE FUNCTION mf()",
      "CREATE TABLE ms(k INT, w INT)",
      "INSERT INTO ms VALUES (1,10),(2,20)",
      "MERGE INTO mt USING ms ON mt.k=ms.k WHEN MATCHED THEN UPDATE SET v=ms.w WHEN NOT MATCHED THEN INSERT VALUES (ms.k,ms.w)"],
     "SELECT k, v FROM mt ORDER BY k",
     "merge with before trigger"),
    ("merge",
     ["CREATE TABLE mt(k INT PRIMARY KEY, v INT)",
      "INSERT INTO mt VALUES (1,10),(2,20),(3,30)",
      "MERGE INTO mt t USING mt s ON t.k = s.k + 1 WHEN MATCHED THEN UPDATE SET v = s.v + 1"],
     "SELECT k, v FROM mt ORDER BY k",
     "merge self join"),
    ("merge",
     ["CREATE TABLE mt(k INT PRIMARY KEY, v INT, g INT GENERATED ALWAYS AS (v*10) STORED)",
      "INSERT INTO mt(k,v) VALUES (1,10)",
      "MERGE INTO mt USING (VALUES (1),(5)) s(k) ON mt.k=s.k WHEN MATCHED THEN UPDATE SET v=v+5 WHEN NOT MATCHED THEN INSERT (k,v) VALUES (s.k, DEFAULT)"],
     "SELECT k, v, g FROM mt ORDER BY k",
     "merge generated col + DEFAULT"),
    ("merge",
     ["CREATE TABLE mt(k INT PRIMARY KEY, v INT)",
      "INSERT INTO mt VALUES (1,10),(2,20)",
      "CREATE TABLE ms(k INT, w INT)",
      "INSERT INTO ms VALUES (1,1),(1,2)"],
     "MERGE INTO mt USING ms ON mt.k=ms.k WHEN MATCHED THEN UPDATE SET v=ms.w",
     "merge second-touch error path"),
    ("merge",
     ["CREATE TABLE mt(k INT, v INT)",
      "INSERT INTO mt VALUES (1,1)",
      "CREATE RULE mru AS ON INSERT TO mt DO INSTEAD NOTHING"],
     "MERGE INTO mt USING (VALUES (2,2)) s(k,v) ON mt.k=s.k WHEN NOT MATCHED THEN INSERT VALUES (s.k,s.v)",
     "merge on rule table error"),
    ("merge",
     ["CREATE TABLE mt(k INT PRIMARY KEY, v INT)",
      "INSERT INTO mt VALUES (1,10),(9,90)",
      "CREATE TABLE ms(k INT)",
      "INSERT INTO ms VALUES (1)"],
     "MERGE INTO mt USING ms ON mt.k=ms.k WHEN NOT MATCHED BY SOURCE THEN DELETE",
     "merge not matched by source pg17"),
    # ------------------- incremental sort / memoize / work_mem bait
    ("incsort",
     ["CREATE TABLE s1(a INT, b INT, c INT)",
      "INSERT INTO s1 SELECT i%50, (i*7)%200, i FROM generate_series(1,4000) i",
      "CREATE INDEX s1_a ON s1(a)",
      "ANALYZE s1"],
     "SELECT a, b, count(*), sum(c) FROM s1 WHERE a < 20 GROUP BY a, b ORDER BY a, b",
     "presorted prefix group"),
    ("incsort",
     ["CREATE TABLE s1(a INT, b INT)",
      "INSERT INTO s1 SELECT i%30, i FROM generate_series(1,3000) i",
      "CREATE INDEX s1_a ON s1(a)",
      "ANALYZE s1"],
     "SELECT a, b FROM s1 WHERE a BETWEEN 5 AND 25 ORDER BY a, b",
     "partial sort extra key"),
    ("incsort",
     ["CREATE TABLE s1(a INT, b INT, c INT)",
      "INSERT INTO s1 SELECT i%10, i%40, i FROM generate_series(1,3000) i",
      "CREATE INDEX s1_ab ON s1(a,b)",
      "ANALYZE s1"],
     "SELECT a, b, c FROM s1 WHERE a < 5 ORDER BY a, b, c",
     "two-key prefix third key"),
    ("memoize",
     ["CREATE TABLE out1(k INT)",
      "INSERT INTO out1 SELECT i%20 FROM generate_series(1,4000) i",
      "CREATE TABLE in1(k INT, v INT)",
      "INSERT INTO in1 SELECT i, i*11 FROM generate_series(1,2000) i",
      "CREATE INDEX in1_k ON in1(k)",
      "ANALYZE out1", "ANALYZE in1"],
     "SELECT o.k, count(*) AS c FROM out1 o JOIN in1 ON in1.k=o.k GROUP BY o.k ORDER BY o.k",
     "repeated lookup keys"),
    ("memoize",
     ["CREATE TABLE out1(k INT)",
      "INSERT INTO out1 SELECT i%25 FROM generate_series(1,2000) i",
      "CREATE TABLE in1(k INT, v INT)",
      "INSERT INTO in1 SELECT i, i*7 FROM generate_series(1,1500) i",
      "CREATE INDEX in1_k ON in1(k)",
      "ANALYZE out1", "ANALYZE in1"],
     "SELECT o.k, (SELECT count(*) FROM in1 WHERE in1.k=o.k) AS c FROM out1 o GROUP BY o.k ORDER BY o.k",
     "correlated repeat params"),
    ("workmem",
     ["CREATE TABLE s1(a INT, b INT)",
      "INSERT INTO s1 SELECT i, i*3 % 500 FROM generate_series(1,20000) i"],
     "SELECT a, b FROM s1 ORDER BY a DESC, b",
     "big sort spillable"),
    ("workmem",
     ["CREATE TABLE s1(a INT, b INT)",
      "INSERT INTO s1 SELECT i%4000, i FROM generate_series(1,20000) i"],
     "SELECT a, count(*), sum(b) FROM s1 GROUP BY a ORDER BY a",
     "big groupby spill"),
    ("workmem",
     ["CREATE TABLE s1(a INT, b INT)",
      "INSERT INTO s1 SELECT i%3000, i*5 FROM generate_series(1,18000) i"],
     "SELECT DISTINCT a, b%3 FROM s1 ORDER BY a, 2",
     "big distinct spill"),
    # ----------------------------------- domains (composite/array)
    ("domain16",
     ["CREATE DOMAIN darr AS INT[] CHECK (VALUE IS NULL OR cardinality(VALUE) <= 3)",
      "CREATE TABLE d1(id INT, a darr)",
      "INSERT INTO d1 VALUES (1,'{1,2,3}'),(2,'{}'),(3,NULL)"],
     "SELECT id, a, cardinality(a) FROM d1 ORDER BY id",
     "domain over array"),
    ("domain16",
     ["CREATE TYPE pt AS (x INT, y INT)",
      "CREATE DOMAIN dpt AS pt CHECK ((VALUE).x <= (VALUE).y)",
      "CREATE TABLE d1(id INT, p dpt)",
      "INSERT INTO d1 VALUES (1,ROW(1,2)::pt),(2,ROW(5,5)::pt)"],
     "SELECT id, (p).x, (p).y, p = ROW(1,2)::dpt AS eq FROM d1 ORDER BY id",
     "domain over composite"),
    ("domain16",
     ["CREATE DOMAIN dpos AS INT CHECK (VALUE > 0)",
      "CREATE DOMAIN dpos2 AS dpos CHECK (VALUE < 100)",
      "CREATE TABLE d1(a dpos2)",
      "INSERT INTO d1 VALUES (5),(50),(99)"],
     "SELECT a, a::int AS bi, a + 1 AS p1 FROM d1 ORDER BY a",
     "stacked domains"),
    ("domain16",
     ["CREATE DOMAIN dpos AS INT CHECK (VALUE > 0)",
      "CREATE TABLE d1(id INT, a dpos[])",
      "INSERT INTO d1 VALUES (1,'{1,2,3}'),(2,'{}'),(3,NULL)"],
     "SELECT id, u.e FROM d1 LEFT JOIN LATERAL unnest(a) u(e) ON true ORDER BY id, u.e NULLS LAST",
     "array of domain unnest"),
    ("domain16",
     ["CREATE DOMAIN dtxt AS TEXT CHECK (VALUE ~ '^[a-z]+$')",
      "CREATE TABLE d1(id INT, s dtxt)",
      "INSERT INTO d1 VALUES (1,'abc'),(2,'xyz')",
      "CREATE INDEX d1_s ON d1(s)"],
     "SELECT id, s FROM d1 WHERE s LIKE 'a%' OR s = 'xyz' ORDER BY id",
     "domain text + index probe"),
    # ------------------- generated cols + domains + expression indexes
    ("genexpr",
     ["CREATE DOMAIN dpos AS INT CHECK (VALUE > 0)",
      "CREATE TABLE g1(a INT, b dpos GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g1(a) VALUES (1),(2),(5)",
      "CREATE INDEX g1_b ON g1(b)"],
     "SELECT a, b FROM g1 WHERE b > 3 ORDER BY a",
     "generated domain col index"),
    ("genexpr",
     ["CREATE DOMAIN dpos AS INT CHECK (VALUE > 0)",
      "CREATE TABLE g1(a INT, b dpos GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g1(a) VALUES (1),(0)"],
     "SELECT a, b FROM g1 ORDER BY a",
     "generated domain check fires"),
    ("genexpr",
     ["CREATE TABLE g1(a INT, b INT)",
      "INSERT INTO g1 VALUES (1,10),(2,20),(3,30)",
      "CREATE INDEX g1_ab ON g1((a+b))"],
     "SELECT a, b FROM g1 WHERE a+b = 30 OR a+b = 12 ORDER BY a",
     "expression index match"),
    ("genexpr",
     ["CREATE TABLE g1(a INT, b INT GENERATED ALWAYS AS (a % 4) STORED)",
      "INSERT INTO g1(a) SELECT i FROM generate_series(1,20) i",
      "CREATE INDEX g1_pb ON g1(b) WHERE b = 0"],
     "SELECT a, b FROM g1 WHERE b = 0 ORDER BY a",
     "partial index on generated"),
    ("genexpr",
     ["CREATE TABLE g1(id INT PRIMARY KEY, a INT, b INT GENERATED ALWAYS AS (a*2) STORED, UNIQUE(a,b))",
      "INSERT INTO g1(id,a) VALUES (1,5),(2,10)",
      "INSERT INTO g1(id,a) VALUES (3,5) ON CONFLICT (a,b) DO NOTHING"],
     "SELECT id, a, b FROM g1 ORDER BY id",
     "upsert hits generated unique"),
    # ------------------- parallel-safety bait (debug_parallel_query)
    ("par16",
     ["CREATE TABLE p1(a INT, b INT) PARTITION BY RANGE (a)",
      "CREATE TABLE p1_0 PARTITION OF p1 FOR VALUES FROM (0) TO (500)",
      "CREATE TABLE p1_1 PARTITION OF p1 FOR VALUES FROM (500) TO (1000)",
      "INSERT INTO p1 SELECT i, i*3 FROM generate_series(1,900) i",
      "CREATE TABLE d1(k INT, w INT)",
      "INSERT INTO d1 SELECT i, i*2 FROM generate_series(1,50) i",
      "ANALYZE p1", "ANALYZE d1"],
     "SELECT a, b, (SELECT w FROM d1 WHERE d1.k = p1.a % 50) AS w FROM p1 WHERE a % 200 < 20 ORDER BY a",
     "corr subq on partitioned"),
    ("par16",
     ["CREATE TABLE big1(a INT, s TEXT)",
      "INSERT INTO big1 SELECT i, 'v'||(i%100) FROM generate_series(1,20000) i",
      "ANALYZE big1"],
     "SELECT s, count(*), string_agg(a::text, ',' ORDER BY a DESC), array_agg(a ORDER BY a) FROM big1 GROUP BY s ORDER BY s",
     "parallel string/array agg pg16"),
    ("par16",
     ["CREATE TABLE l1(a INT)",
      "INSERT INTO l1 SELECT i FROM generate_series(1,4000) i",
      "CREATE TABLE r1(a INT)",
      "INSERT INTO r1 SELECT i FROM generate_series(1000,5000) i",
      "CREATE INDEX r1_a ON r1(a)",
      "ANALYZE l1", "ANALYZE r1"],
     "SELECT count(*) FROM l1 FULL JOIN r1 ON l1.a=r1.a WHERE l1.a IS NULL OR r1.a IS NULL",
     "parallel full join pg16"),
    ("par16",
     ["CREATE TABLE big1(a INT, b INT)",
      "INSERT INTO big1 SELECT i, i%50 FROM generate_series(1,30000) i",
      "CREATE TABLE big2(a INT, c INT)",
      "INSERT INTO big2 SELECT i, i*2 FROM generate_series(1,15000) i",
      "CREATE INDEX big2_a ON big2(a)",
      "ANALYZE big1", "ANALYZE big2"],
     "SELECT b, count(*) FROM big1 WHERE EXISTS (SELECT 1 FROM big2 WHERE big2.a = big1.a) GROUP BY b ORDER BY b",
     "parallel semijoin exists"),
    ("par16",
     ["CREATE TABLE big1(a INT, v NUMERIC)",
      "INSERT INTO big1 SELECT i, (i*1.5)::numeric FROM generate_series(1,25000) i",
      "ANALYZE big1"],
     "SELECT a%17 AS g, sum(v), avg(v), count(DISTINCT a%997) FROM big1 GROUP BY 1 ORDER BY 1",
     "parallel agg + distinct"),
    # ----------------------------------- jsonb subscript / ops (PG14+)
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":{\"b\":[1,2,3]}}'),(2,'{\"a\":{\"b\":[4]}}'),(3,'{}'),(4,NULL)"],
     "SELECT id, j['a'], j['a']['b'][0], j['missing'] FROM j1 ORDER BY id",
     "jsonb subscript pg14"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":{\"b\":1}}'),(2,'{\"a\":2}')",
      "UPDATE j1 SET j['a']['b'] = '9'::jsonb WHERE id=1",
      "UPDATE j1 SET j['x']['y'] = '7'::jsonb WHERE id=2"],
     "SELECT id, j::text FROM j1 ORDER BY id",
     "jsonb nested subscript update"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1,\"b\":2}'),(2,'[1,2]'),(3,'\"s\"'),(4,'[3]'),(5,'5')"],
     "SELECT id, (j || '5'::jsonb)::text AS js, (j || '[9]'::jsonb)::text AS ja, ('8'::jsonb || j)::text AS pre, (j || '{\"z\":1}'::jsonb)::text AS jo FROM j1 ORDER BY id",
     "jsonb concat type matrix"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":1,\"b\":{\"c\":2}}'),(2,'[1,2,3]'),(3,'{\"a\":{\"b\":{\"c\":9}}}')"],
     "SELECT id, (j - 'a')::text AS dma, (j - 'b')::text AS dmb, (j - 1)::text AS di1, (j #- '{a,b,c}')::text AS dpc, (j #- '{b,c}')::text AS dpb FROM j1 ORDER BY id",
     "jsonb delete ops matrix"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'[1,2,3,4]'),(2,'{\"a\":10,\"b\":20}'),(3,'{\"a\":{\"x\":[5,6]}}')"],
     "SELECT id, q::text FROM j1, LATERAL jsonb_path_query(j, '$[*] ? (@ > $lim)', jsonb_build_object('lim',2), true) q ORDER BY id, q::text",
     "jsonpath vars passing"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'[\"apple\",\"banana\",\"avocado\"]'),(2,'{\"k1\":\"cat\",\"k2\":\"cut\"}')"],
     "SELECT id, q::text FROM j1, LATERAL jsonb_path_query(j, '$[*] ? (@ like_regex \"^a\")', silent => true) q ORDER BY id, q::text",
     "jsonpath like_regex"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":{\"b\":{\"c\":42}}}'),(2,'{\"x\":{\"c\":7}}'),(3,'{\"c\":1}')"],
     "SELECT id, q::text FROM j1, LATERAL jsonb_path_query(j, '$.**.c ? (@ > 1)') q ORDER BY id, q::text",
     "jsonpath recursive descent"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'[1,4,9,16]'),(2,'[\"-3\",2.25]'),(3,'[]')"],
     "SELECT id, q::text FROM j1, LATERAL jsonb_path_query(j, '$[*].double() ? (@ > 2)') q ORDER BY id, q::text",
     "jsonpath double method"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"d\":\"2024-01-05\"}'),(2,'{\"d\":\"2024-06-01\"}'),(3,'{\"d\":\"notadate\"}')"],
     "SELECT id, q::text FROM j1, LATERAL jsonb_path_query(j, '$.d.datetime() ? (@ > \"2024-03-01\".datetime())', silent => true) q ORDER BY id, q::text",
     "jsonpath datetime"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":5}'),(2,'[1,2]'),(3,'\"s\"')"],
     "SELECT id, jsonb_path_query(j, 'strict $.a') FROM j1 ORDER BY id",
     "jsonpath strict error"),
    ("jsonb_ops",
     ["CREATE TABLE j1(id INT, j JSONB)",
      "INSERT INTO j1 VALUES (1,'{\"a\":[10,20,30]}'),(2,'{\"a\":5}'),(3,'{}')"],
     "SELECT id, jsonb_path_query_first(j, '$.a[*] ? (@ >= 20)')::text AS f1, jsonb_path_query_first(j, '$.a')::text AS f2 FROM j1 ORDER BY id",
     "jsonb_path_query_first"),
    # ------------------- non-decimal / underscored literals (PG16)
    ("numlit16",
     [],
     "SELECT 0xFF AS h, 0b1010 AS b, 0o17 AS o, 1_000_000 AS u, 0x1F + 0b1 AS mix, 2_5.5 AS f, 1e1_0 AS e",
     "non-decimal + underscore literals"),
    ("numlit16",
     ["CREATE TABLE n1(a INT)",
      "INSERT INTO n1 VALUES (0x10),(0b11),(0o20),(1_000)"],
     "SELECT a, a = 16 AS eq16, a & 0x0F AS band, a | 0b100 AS bor FROM n1 ORDER BY a",
     "literal insert bitops"),
    ("numlit16",
     ["CREATE TABLE n1(a NUMERIC, b BIGINT)",
      "INSERT INTO n1 VALUES (1_000.5, 0x7FFF_FFFF_FFFF_FFFF),(2_5e1, -0b1_000)"],
     "SELECT a, b, a + 0.5 AS a2, -b AS nb FROM n1 ORDER BY a",
     "underscore numeric bigint"),
    # ------------------- misc PG15/16
    ("pg1516",
     ["CREATE TABLE nd(a INT, b TEXT)",
      "CREATE UNIQUE INDEX ndu ON nd(a) NULLS NOT DISTINCT",
      "INSERT INTO nd VALUES (NULL,'x'),(1,'p')",
      "INSERT INTO nd VALUES (NULL,'y'),(2,'q') ON CONFLICT (a) DO UPDATE SET b = 'u'"],
     "SELECT a, b FROM nd ORDER BY a NULLS FIRST",
     "nulls not distinct upsert"),
    ("pg1516",
     ["CREATE TABLE nd(a INT, b TEXT)",
      "CREATE UNIQUE INDEX ndu ON nd(a)",
      "INSERT INTO nd VALUES (NULL,'x'),(NULL,'x2'),(1,'p')"],
     "SELECT count(*) AS nulls, count(DISTINCT b) AS nb FROM nd",
     "nulls distinct default"),
    ("pg1516",
     [],
     "SELECT gcd(12,18) AS g1, gcd(0,7) AS g2, lcm(4,6) AS l1, lcm(0,5) AS l2, scale(1.2340::numeric) AS sc, min_scale(1.2300::numeric) AS ms, trim_scale(1.2300::numeric) AS ts",
     "gcd lcm scale pg15"),
    ("pg1516",
     ["CREATE TABLE i1(d DATE)",
      "INSERT INTO i1 VALUES ('2024-01-15'),('2024-03-20')"],
     "SELECT d, d + interval '1.5 months' AS m15, d + interval '0.25 years' AS y25, interval '2.5 hours' AS h FROM i1 ORDER BY d",
     "interval fractions pg16"),
    ("pg1516",
     ["CREATE TABLE t1(s TEXT)",
      "INSERT INTO t1 VALUES ('abc123def'),('x9'),('no-digits')"],
     "SELECT s, substring(s FROM '([a-z]+)([0-9]+)' FOR '#') AS sub, substring(s FROM '[0-9]+') AS num FROM t1 ORDER BY s",
     "substring for escape pg14"),
    ("pg1516",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'123x'),(2,'42'),(3,'1e5'),(4,'abc')"],
     "SELECT id, (pg_input_error_info(s,'int4')).* FROM t1 ORDER BY id",
     "pg_input_error_info pg16"),
    ("pg1516",
     ["CREATE TABLE t1(g INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'b'),(1,'a'),(1,'a'),(2,'c'),(2,'a')"],
     "SELECT g, string_agg(DISTINCT s, ',' ORDER BY s), count(DISTINCT s) FROM t1 GROUP BY g ORDER BY g",
     "distinct agg order by pg16"),
    ("pg1516",
     ["CREATE TABLE t1(g INT, v INT)",
      "INSERT INTO t1 VALUES (1,5),(1,5),(2,9),(3,NULL),(3,NULL)"],
     "SELECT g, any_value(v) FROM t1 GROUP BY g ORDER BY g",
     "any_value pg16"),
    # ------------------- second wave (verified edges)
    ("pg1516",
     ["CREATE TABLE t1(id INT, s TEXT)",
      "INSERT INTO t1 VALUES (1,'abc'),(2,'a' || U&'0308'),(3,'x%y')"],
     "SELECT id, s IS NORMALIZED, s IS NFC NORMALIZED, s IS NFKC NORMALIZED FROM t1 ORDER BY id",
     "is normalized predicate"),
    ("pg1516",
     ["CREATE TABLE t1(t TIMESTAMPTZ)",
      "INSERT INTO t1 VALUES ('2024-03-10 15:04:05+05:30'),('2024-12-25 00:00:00-08:00')"],
     "SELECT to_char(t, 'YYYY-MM-DD HH24:MI OF TZH:TZM'), to_char(t, 'Dy Mon DD YYYY') FROM t1 ORDER BY t",
     "to_char OF TZH TZM pg16"),
    ("pg1516",
     ["CREATE TABLE t1(id INT, s TEXT CHECK (s IS JSON OBJECT))",
      "INSERT INTO t1 VALUES (1,'{\"a\":1}'),(2,'{}')"],
     "SELECT id, s FROM t1 ORDER BY id",
     "is json in check constraint"),
    ("pg1516",
     ["CREATE DOMAIN dn AS INT",
      "CREATE TABLE d1(a dn)",
      "INSERT INTO d1 VALUES (-5),(3)",
      "ALTER DOMAIN dn ADD CONSTRAINT dnc CHECK (VALUE > 0)"],
     "SELECT a FROM d1 ORDER BY a",
     "alter domain retro check error"),
    ("multirange",
     ["CREATE TABLE r1(id INT, m INT4MULTIRANGE)",
      "INSERT INTO r1 VALUES (1,'{[1,3),[7,9)}'),(2,'{}'),(3,NULL)"],
     "SELECT id, u.r::text, u.n FROM r1 LEFT JOIN LATERAL unnest(m) WITH ORDINALITY u(r,n) ON true ORDER BY id, u.n NULLS LAST",
     "unnest multirange ordinality"),
    ("multirange",
     ["CREATE TABLE r1(id INT, x INT4RANGE)",
      "INSERT INTO r1 VALUES (1,'[1,3)'),(1,'empty'),(2,'[5,9)'),(2,'[7,10)')"],
     "SELECT id, range_intersect_agg(x) OVER (PARTITION BY id)::text AS ri, range_agg(x) OVER (PARTITION BY id)::text AS ra FROM r1 ORDER BY id, x::text",
     "range aggs as window fns"),
    ("misc",
     ["CREATE TABLE t1(s TEXT)",
      "INSERT INTO t1 VALUES ('a-b-c'),('xy'),('')"],
     "SELECT s, st.v, st.n FROM t1, LATERAL string_to_table(s, '-') WITH ORDINALITY st(v,n) ORDER BY s, st.n",
     "string_to_table pg14"),
    ("incsort",
     ["CREATE TABLE s1(a INT, b INT, c INT)",
      "INSERT INTO s1 SELECT i%40, i, i%97 FROM generate_series(1,3000) i",
      "CREATE INDEX s1_a ON s1(a)",
      "ANALYZE s1"],
     "SELECT a, c, row_number() OVER (ORDER BY a, c) rn FROM s1 WHERE a<3 ORDER BY a, c",
     "window fed by presorted prefix"),
]


def as_seeds() -> list[dict]:
    all_t = PG_TEMPLATES + PG_TEMPLATES_B2 + PG_TEMPLATES_R2
    r2_start = len(all_t) - len(PG_TEMPLATES_R2)
    out = []
    for i, (surface, setup, query, note) in enumerate(all_t):
        out.append({
            "setup_sqls": list(setup),
            "query": query,
            "source": f"pg_target:{surface}#{i}",
            "engine": "postgres",
            "tags": ["pg_native", "pg16_r2" if i >= r2_start else "pg_base",
                     surface, note],
        })
    return out


def as_seeds_r2() -> list[dict]:
    """Only the round-2 (PG14/15/16 feature) templates."""
    return as_seeds()[-len(PG_TEMPLATES_R2):]
