"""Per-rule trigger templates: queries designed to exercise each optimizer
rule — i.e. each *optimization direction* — on the current engine.

Rationale: novel bugs live in the product space (existing complex
queries) x (newer optimizer features). Old corpus queries predate rules
added in 1.4/1.5.x; per-rule targeted queries close that gap. Each
template is a Seed-like dict {setup_sqls, query, source, tags} so it can
flow through the same corpus_hunt pipeline; sigma then attributes any
hit to a specific rule = a specific optimization direction.

Data variety matters more than query cleverness: each template should be
tried under several data shapes (empty side, NULL keys, skewed, dup
rows) — the mutator's structural variants and DCE handle the rest.
"""

from __future__ import annotations

# Each entry: (rule, setup_sqls, query, note)
RULE_TEMPLATES: list[tuple[str, list[str], str, str]] = [
    # ------------------------------------------------ window_self_join (1.5.0)
    ("window_self_join",
     ["CREATE TABLE w(a INT, b INT, v INT)",
      "INSERT INTO w VALUES (1,1,10),(1,2,20),(2,1,30),(2,2,40)"],
     "SELECT SUM(v) OVER (PARTITION BY a) s1, AVG(v) OVER (PARTITION BY a) s2 FROM w ORDER BY a,b",
     "two windows same partition"),
    ("window_self_join",
     ["CREATE TABLE w(a INT, b INT, v INT)",
      "INSERT INTO w VALUES (1,1,10),(1,2,20),(2,1,30),(2,2,40)"],
     "SELECT SUM(v) OVER (PARTITION BY a, b) s1, SUM(v) OVER (PARTITION BY a, a) s2, COUNT(*) OVER (PARTITION BY b) s3 FROM w ORDER BY a,b",
     "dup partition key + mixed"),
    ("window_self_join",
     ["CREATE TABLE w(a INT, v INT)",
      "INSERT INTO w VALUES (1,10),(1,20),(2,30),(2,40),(3,NULL)"],
     "SELECT SUM(v) OVER (PARTITION BY a ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) c FROM w ORDER BY a",
     "ROWS frame (issue-21592 class)"),
    ("window_self_join",
     ["CREATE TABLE w(a INT, v INT)",
      "INSERT INTO w VALUES (1,10),(1,20),(2,30),(2,40)"],
     "SELECT SUM(v) OVER (PARTITION BY a ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) s FROM w ORDER BY a,v",
     "RANGE frame"),
    ("window_self_join",
     ["CREATE TABLE w(a INT, v INT)",
      "INSERT INTO w VALUES (1,10),(1,20),(1,NULL),(2,30)"],
     "SELECT SUM(v) OVER (PARTITION BY a) s, MIN(v) OVER (PARTITION BY a) m, MAX(v) OVER (PARTITION BY a) x FROM w ORDER BY a,v",
     "three windows same partition + NULL"),
    # -------------------------------------- top_n_window_elimination (new)
    ("top_n_window_elimination",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,5),(1,9),(2,7),(2,3),(3,8)"],
     "SELECT * FROM (SELECT g, v, ROW_NUMBER() OVER (PARTITION BY g ORDER BY v DESC) rn FROM t) s WHERE rn <= 1 ORDER BY g",
     "row_number + rn<=1"),
    ("top_n_window_elimination",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,5),(1,9),(2,7),(2,3),(3,8)"],
     "SELECT * FROM (SELECT g, v, RANK() OVER (PARTITION BY g ORDER BY v) rk, DENSE_RANK() OVER (PARTITION BY g ORDER BY v) dr FROM t) s WHERE rk = 1 ORDER BY g,v",
     "rank + dense_rank mix"),
    ("top_n_window_elimination",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,5),(1,NULL),(2,7),(2,7),(3,8)"],
     "SELECT g, v FROM t QUALIFY ROW_NUMBER() OVER (PARTITION BY g ORDER BY v) = 1 ORDER BY g",
     "QUALIFY + ties + NULL"),
    ("top_n_window_elimination",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,5),(1,9),(2,7),(2,3),(3,8)"],
     "SELECT * FROM (SELECT g, v, ROW_NUMBER() OVER (ORDER BY v) rn FROM t) s WHERE rn BETWEEN 2 AND 3 ORDER BY rn",
     "unpartitioned row_number range"),
    # ------------------------------------------------- CTE rules (3 rules)
    ("cte_inlining",
     ["CREATE TABLE base(x INT)",
      "INSERT INTO base VALUES (1),(2),(3)"],
     "WITH c AS (SELECT x, x*2 AS d FROM base) SELECT a.d, b.d FROM c a JOIN c b ON a.x = b.x ORDER BY 1",
     "CTE self-join 2 refs"),
    ("materialized_cte",
     ["CREATE TABLE base(x INT, y INT)",
      "INSERT INTO base VALUES (1,10),(2,20),(3,30)"],
     "WITH c AS MATERIALIZED (SELECT x, SUM(y) s FROM base GROUP BY x) SELECT c1.s, c2.s FROM c c1, c c2 WHERE c1.x < c2.x ORDER BY 1,2",
     "MATERIALIZED hint + self join"),
    ("cte_filter_pusher",
     ["CREATE TABLE base(x INT, y INT)",
      "INSERT INTO base VALUES (1,10),(2,20),(3,30),(4,40)"],
     "WITH c AS (SELECT x, y FROM base) SELECT * FROM c WHERE x > 2 ORDER BY x",
     "outer filter into CTE"),
    ("cte_filter_pusher",
     ["CREATE TABLE base(x INT, y INT)",
      "INSERT INTO base VALUES (1,10),(2,NULL),(3,30)"],
     "WITH c AS (SELECT x, y, ROW_NUMBER() OVER (ORDER BY x) rn FROM base) SELECT * FROM c WHERE y IS NOT NULL AND rn > 1 ORDER BY x",
     "filter through windowed CTE"),
    ("cte_inlining",
     ["CREATE TABLE base(x INT)",
      "INSERT INTO base VALUES (1),(2),(3)"],
     "WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n < 5) SELECT COUNT(*), SUM(n) FROM seq",
     "recursive CTE"),
    # ------------------------------------------- late/compressed materialization
    ("late_materialization",
     ["CREATE TABLE wide(id INT, c1 INT, c2 INT, c3 VARCHAR, c4 VARCHAR)",
      "INSERT INTO wide SELECT i, i*2, i*3, 'a'||i::VARCHAR, 'b'||i::VARCHAR FROM range(200) t(i)"],
     "SELECT id, c1 FROM wide ORDER BY c2 DESC LIMIT 5",
     "wide row + top-n"),
    ("late_materialization",
     ["CREATE TABLE wide(id INT, c1 INT, c2 INT)",
      "INSERT INTO wide SELECT i, i*2, i*3 FROM range(200) t(i)"],
     "SELECT w1.id FROM wide w1 JOIN wide w2 ON w1.c1 = w2.c2 ORDER BY w1.id LIMIT 7",
     "self-join + limit"),
    ("compressed_materialization",
     ["CREATE TABLE wide(id INT, payload VARCHAR)",
      "INSERT INTO wide SELECT i, repeat('x', 200) || i::VARCHAR FROM range(120) t(i)"],
     "SELECT id, length(payload) L FROM wide ORDER BY L DESC LIMIT 3",
     "large payload + limit"),
    # ------------------------------------------------- join filter pushdown
    ("join_filter_pushdown",
     ["CREATE TABLE l(a INT, v INT)", "CREATE TABLE r(a INT, w INT)",
      "INSERT INTO l VALUES (1,10),(2,20),(3,30)",
      "INSERT INTO r VALUES (1,100),(1,200),(4,300)"],
     "SELECT l.a, SUM(l.v) FROM l JOIN r ON l.a = r.a WHERE l.v > 5 GROUP BY l.a ORDER BY 1",
     "join + selective filter + agg"),
    ("join_filter_pushdown",
     ["CREATE TABLE l(a INT, v INT)", "CREATE TABLE r(a INT, w INT)",
      "INSERT INTO l VALUES (1,10),(2,20),(3,30),(4,NULL)",
      "INSERT INTO r VALUES (1,100),(2,200),(5,300)"],
     "SELECT l.a, r.w FROM l LEFT JOIN r ON l.a = r.a AND l.v > 15 ORDER BY 1,2",
     "outer join + ON-clause filter"),
    ("join_filter_pushdown",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(a INT)",
      "INSERT INTO l VALUES (1),(2),(3)", "INSERT INTO r VALUES (1),(2)"],
     "SELECT * FROM l JOIN r ON l.a = r.a WHERE EXISTS (SELECT 1 FROM r r2 WHERE r2.a = l.a) ORDER BY l.a",
     "join + EXISTS on same table"),
    # -------------------------------------------------- statistics_propagation
    ("statistics_propagation",
     ["CREATE TABLE skew(k INT, v INT)",
      "INSERT INTO skew SELECT 1, i FROM range(80) t(i)",
      "INSERT INTO skew SELECT 2, i FROM range(3) t(i)"],
     "SELECT k, COUNT(*) FROM skew GROUP BY k ORDER BY k",
     "skewed group counts"),
    ("statistics_propagation",
     ["CREATE TABLE nums(v INT)",
      "INSERT INTO nums VALUES (2147483647),(-2147483648),(0),(1)"],
     "SELECT v, v::BIGINT + 1 FROM nums WHERE v > -2147483648 ORDER BY v",
     "int boundary values"),
    ("statistics_propagation",
     ["CREATE TABLE a(x INT)", "CREATE TABLE b(x INT)",
      "INSERT INTO a VALUES (1),(1),(1),(2)", "INSERT INTO b VALUES (1),(2)"],
     "SELECT COUNT(*) FROM a JOIN b ON a.x = b.x WHERE a.x = 1",
     "dup-heavy equi join + equality"),
    # ------------------------------------------------------ empty_result_pullup
    ("empty_result_pullup",
     ["CREATE TABLE e(x INT)", "CREATE TABLE f(x INT)",
      "INSERT INTO f VALUES (1),(2)"],
     "SELECT COUNT(*) c, SUM(x) s FROM e",
     "empty aggregate"),
    ("empty_result_pullup",
     ["CREATE TABLE e(x INT)", "CREATE TABLE f(x INT)",
      "INSERT INTO f VALUES (1),(2)"],
     "SELECT f.x, e.x FROM f LEFT JOIN e ON f.x = e.x ORDER BY f.x",
     "empty right side outer join"),
    ("empty_result_pullup",
     ["CREATE TABLE e(x INT)",
      "INSERT INTO e VALUES (1)"],
     "SELECT * FROM e WHERE x IN (SELECT x FROM e WHERE x > 100) UNION ALL SELECT 99 ORDER BY 1",
     "empty subquery + union"),
    # ------------------------------------------------------------ regex_range
    ("regex_range",
     ["CREATE TABLE s(v VARCHAR)",
      "INSERT INTO s VALUES ('abc'),('abd'),('xyz'),('ab'),('abcd')"],
     "SELECT v FROM s WHERE v LIKE 'ab%' ORDER BY v",
     "prefix LIKE -> range"),
    ("regex_range",
     ["CREATE TABLE s(v VARCHAR)",
      "INSERT INTO s VALUES ('a1'),('a2'),('b1'),('a10')"],
     "SELECT v FROM s WHERE v ~ '^a[0-9]$' ORDER BY v",
     "regex range"),
    ("regex_range",
     ["CREATE TABLE s(v VARCHAR)",
      "INSERT INTO s VALUES ('AB'),('ab'),('Ab'),('aB')"],
     "SELECT v FROM s WHERE v ILIKE 'a%' ORDER BY v",
     "case-insensitive prefix"),
    # ------------------------------------------------------------ sum_rewriter
    ("sum_rewriter",
     ["CREATE TABLE m(g INT, v INT)",
      "INSERT INTO m VALUES (1,10),(1,-4),(2,7),(2,-7)"],
     "SELECT g, SUM(v), SUM(CASE WHEN v>0 THEN v END) pos, SUM(CASE WHEN v<0 THEN v END) neg FROM m GROUP BY g ORDER BY g",
     "SUM decomposition + CASE"),
    ("sum_rewriter",
     ["CREATE TABLE m(g INT, v DOUBLE)",
      "INSERT INTO m VALUES (1,0.1),(1,0.2),(2,1e308),(2,-1e308)"],
     "SELECT g, SUM(v), AVG(v), SUM(v)/COUNT(*) FROM m GROUP BY g ORDER BY g",
     "float extremes"),
    # ----------------------------------------------------------------- in_clause
    ("in_clause",
     ["CREATE TABLE t(x INT)",
      "INSERT INTO t VALUES (1),(2),(3),(NULL)"],
     "SELECT x FROM t WHERE x IN (1,2,NULL,4) OR x IS NULL ORDER BY x",
     "IN list with NULL"),
    ("in_clause",
     ["CREATE TABLE t(x INT)", "CREATE TABLE u(x INT)",
      "INSERT INTO t VALUES (1),(2),(3)", "INSERT INTO u VALUES (2),(3),(NULL)"],
     "SELECT x FROM t WHERE x IN (SELECT x FROM u) ORDER BY x",
     "IN subquery with NULL source"),
    ("in_clause",
     ["CREATE TABLE t(x INT)",
      "INSERT INTO t SELECT i FROM range(50) t(i)"],
     "SELECT COUNT(*) FROM t WHERE x IN (SELECT i*2 FROM range(30) t(i))",
     "large IN subquery"),
    # -------------------------------------------------------- unnest_rewriter
    ("unnest_rewriter",
     ["CREATE TABLE t(id INT, xs INT[])",
      "INSERT INTO t VALUES (1,[1,2,3]),(2,[]),(3,NULL)"],
     "SELECT id, u.x FROM t, UNNEST(t.xs) AS u(x) ORDER BY id, u.x",
     "unnest empty+NULL lists"),
    ("unnest_rewriter",
     ["CREATE TABLE t(id INT, xs INT[])",
      "INSERT INTO t VALUES (1,[1,2]),(2,[3])"],
     "SELECT id, x FROM t CROSS JOIN LATERAL (SELECT * FROM UNNEST(t.xs)) u(x) ORDER BY id, x",
     "lateral unnest"),
    # ------------------------------------------------------ duplicate_groups
    ("duplicate_groups",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(2,1)"],
     "SELECT a, COUNT(*) c1, COUNT(*) c2, SUM(b) s1, SUM(b) s2 FROM t GROUP BY a ORDER BY a",
     "duplicate aggregates"),
    ("duplicate_groups",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(2,1)"],
     "SELECT a+b e1, a+b e2, a+b e3 FROM t GROUP BY a+b ORDER BY 1",
     "identical expressions grouped"),
    # ------------------------------------------------- limit_pushdown / top_n
    ("limit_pushdown",
     ["CREATE TABLE t(a INT, b INT)", "CREATE TABLE u(a INT)",
      "INSERT INTO t VALUES (1,10),(2,20),(3,30)", "INSERT INTO u VALUES (1),(2)"],
     "SELECT t.a FROM t JOIN u ON t.a = u.a ORDER BY t.b LIMIT 2",
     "limit through join"),
    ("limit_pushdown",
     ["CREATE TABLE t(a INT)",
      "INSERT INTO t VALUES (1),(2),(3),(4)"],
     "SELECT a FROM (SELECT a FROM t UNION ALL SELECT a FROM t) s ORDER BY a LIMIT 3",
     "limit through union"),
    ("top_n",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,5),(1,5),(2,5),(3,1)"],
     "SELECT a, b FROM t ORDER BY b DESC, a LIMIT 2 OFFSET 1",
     "top-n with ties + offset"),
    # ------------------------------------------------- join_elimination
    ("join_elimination",
     ["CREATE TABLE p(id INT PRIMARY KEY, v INT)", "CREATE TABLE c(id INT, pid INT REFERENCES p(id))",
      "INSERT INTO p VALUES (1,10),(2,20)", "INSERT INTO c VALUES (1,1),(2,2),(3,1)"],
     "SELECT c.id FROM c JOIN p ON c.pid = p.id ORDER BY c.id",
     "PK/FK join only uses one side"),
    # -------------------------------------------------- reorder_filter
    ("reorder_filter",
     ["CREATE TABLE t(a INT, b INT, c VARCHAR)",
      "INSERT INTO t VALUES (1,1,'x'),(2,2,'yy'),(3,3,'zzz'),(4,4,'x')"],
     "SELECT a FROM t WHERE a > 1 AND length(c) > 1 AND b < 4 ORDER BY a",
     "selectivity ordering"),
    # ------------------------------------------- expression_rewriter
    ("expression_rewriter",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,0),(2,5),(NULL,3)"],
     "SELECT a FROM t WHERE NOT (a < b OR a IS NULL) ORDER BY a",
     "De Morgan + NULL"),
    ("expression_rewriter",
     ["CREATE TABLE t(a INT)",
      "INSERT INTO t VALUES (0),(1),(2)"],
     "SELECT a, a*1 x1, a+0 x2, a*0 z, a/a q FROM t ORDER BY a",
     "identity arithmetic"),
    # ----------------------------------------------------- misc newer rules
    ("sampling_pushdown",
     ["CREATE TABLE t(a INT)",
      "INSERT INTO t SELECT i FROM range(100) t(i)"],
     "SELECT COUNT(*) FROM t TABLESAMPLE BERNOULLI(20 PERCENT) REPEATABLE(42) WHERE a > 50",
     "sample + filter order"),
    ("row_group_pruner",
     ["CREATE TABLE t(a INT)",
      "INSERT INTO t SELECT i FROM range(300) t(i)"],
     "SELECT COUNT(*) FROM t WHERE a BETWEEN 100 AND 110",
     "zone-map prune"),
    ("common_subplan",
     ["CREATE TABLE t(a INT)",
      "INSERT INTO t VALUES (1),(2),(3)"],
     "SELECT (SELECT MAX(a) FROM t) m1, (SELECT MAX(a) FROM t) m2, (SELECT MIN(a) FROM t) n FROM t LIMIT 1",
     "shared scalar subplans"),
]


# Feature-edge templates: under-fuzzed surface (DuckDB-specific syntax and
# feature intersections) rather than per-rule triggers. Bugs found here are
# inherently "new optimization direction" cases — the corpus predates these
# features entirely.
FEATURE_TEMPLATES: list[tuple[str, list[str], str, str]] = [
    # ------------------------------------------------- ASOF / POSITIONAL join
    ("asof_join",
     ["CREATE TABLE ev(id INT, ts INT, v INT)", "CREATE TABLE px(id INT, ts INT, p INT)",
      "INSERT INTO ev VALUES (1,5,100),(1,15,200),(2,10,300)",
      "INSERT INTO px VALUES (1,1,10),(1,9,20),(1,14,30),(2,8,40)"],
     "SELECT ev.id, ev.ts, px.p FROM ev ASOF JOIN px ON ev.id = px.id AND ev.ts >= px.ts ORDER BY ev.id, ev.ts",
     "asof join ties at boundary"),
    ("asof_join",
     ["CREATE TABLE ev(ts INT, v INT)", "CREATE TABLE px(ts INT, p INT)",
      "INSERT INTO ev VALUES (5,1),(5,2),(10,3)",
      "INSERT INTO px VALUES (5,10),(5,20),(9,30)"],
     "SELECT ev.ts, px.p FROM ev ASOF JOIN px ON ev.ts >= px.ts ORDER BY ev.ts, px.p",
     "asof duplicate boundary ts"),
    ("positional_join",
     ["CREATE TABLE a(x INT)", "CREATE TABLE b(y INT)",
      "INSERT INTO a VALUES (1),(2),(3)", "INSERT INTO b VALUES (10),(20)"],
     "SELECT a.x, b.y FROM a POSITIONAL JOIN b ORDER BY a.x",
     "positional join length mismatch"),
    # ------------------------------------------------------- PIVOT / UNPIVOT
    ("pivot",
     ["CREATE TABLE t(g VARCHAR, k VARCHAR, v INT)",
      "INSERT INTO t VALUES ('a','x',1),('a','y',2),('b','x',3),('b','x',4),('c','z',NULL)"],
     "PIVOT t ON k USING SUM(v) GROUP BY g ORDER BY g",
     "pivot with dup keys + NULL"),
    ("pivot",
     ["CREATE TABLE t(g VARCHAR, v INT)",
      "INSERT INTO t VALUES ('a',1),('a',2),('b',3)"],
     "PIVOT t ON g USING SUM(v), COUNT(*) ORDER BY 1",
     "pivot multi-aggregate"),
    ("unpivot",
     ["CREATE TABLE w(id INT, a INT, b INT)",
      "INSERT INTO w VALUES (1,10,20),(2,NULL,40),(3,50,NULL)"],
     "UNPIVOT w ON a, b INTO NAME col VALUE val ORDER BY id, col",
     "unpivot NULL columns"),
    # -------------------------------------------------------------- QUALIFY
    ("qualify",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,5),(1,5),(1,9),(2,7)"],
     "SELECT g, v, ROW_NUMBER() OVER (PARTITION BY g ORDER BY v DESC) rn FROM t QUALIFY rn = 1 ORDER BY g, v",
     "qualify with tie at rank 1"),
    ("qualify",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,5),(1,9),(2,7),(2,7)"],
     "SELECT g, v, COUNT(*) OVER (PARTITION BY g) c FROM t GROUP BY g, v QUALIFY c > 1 ORDER BY g, v",
     "qualify + group by interaction"),
    # --------------------------------------------------- grouping sets/rollup
    ("grouping_sets",
     ["CREATE TABLE t(a INT, b INT, v INT)",
      "INSERT INTO t VALUES (1,NULL,10),(NULL,NULL,20),(1,2,30)"],
     "SELECT a, b, GROUPING(a, b) g, SUM(v) FROM t GROUP BY GROUPING SETS ((a,b),(a),()) ORDER BY 1,2,3",
     "grouping id with NULL keys"),
    ("rollup",
     ["CREATE TABLE t(a INT, b INT, v INT)",
      "INSERT INTO t VALUES (1,NULL,10),(NULL,2,20),(1,2,30)"],
     "SELECT a, b, SUM(v), GROUPING_ID(a,b) gid FROM t GROUP BY ROLLUP(a,b) ORDER BY 1,2,4",
     "rollup + NULL in key"),
    ("cube",
     ["CREATE TABLE t(a INT, b INT, v INT)",
      "INSERT INTO t VALUES (1,1,10),(1,NULL,20),(NULL,1,30)"],
     "SELECT a, b, COUNT(*) FROM t GROUP BY CUBE(a,b) ORDER BY 1,2",
     "cube all-NULL combos"),
    # -------------------------------------------------------- nested types
    ("struct",
     ["CREATE TABLE t(id INT, s STRUCT(x INT, y INT))",
      "INSERT INTO t VALUES (1,{'x':1,'y':2}),(2,{'x':1,'y':3}),(3,NULL)"],
     "SELECT id FROM t WHERE s = {'x':1,'y':2} OR s.x = 2 ORDER BY id",
     "struct equality + field access"),
    ("list_lambda",
     ["CREATE TABLE t(id INT, xs INT[])",
      "INSERT INTO t VALUES (1,[1,2,3]),(2,[]),(3,[4,NULL,5]),(4,NULL)"],
     "SELECT id, list_filter(xs, x -> x > 1) f, list_count(xs) c FROM t ORDER BY id",
     "lambda on empty/NULL lists"),
    ("list_lambda",
     ["CREATE TABLE t(id INT, xs INT[])",
      "INSERT INTO t VALUES (1,[3,1,2]),(2,[5])"],
     "SELECT id, list_aggregate(xs, 'sum') s, list_transform(xs, x -> x * 2) d FROM t ORDER BY id",
     "list aggregate + transform"),
    ("unnest_struct",
     ["CREATE TABLE t(id INT, s STRUCT(x INT, y INT)[])",
      "INSERT INTO t VALUES (1,[{'x':1,'y':1},{'x':2,'y':2}]),(2,[]),(3,NULL)"],
     "SELECT id, u.unnest.x, u.unnest.y FROM t, UNNEST(t.s) u ORDER BY id, 2, 3",
     "unnest struct array"),
    ("map_type",
     ["CREATE TABLE t(id INT, m MAP(VARCHAR, INT))",
      "INSERT INTO t VALUES (1,map{'a':1,'b':2}),(2,map{}),(3,NULL)"],
     "SELECT id, m['a'] av, cardinality(m) c FROM t ORDER BY id",
     "map lookup + empty/NULL map"),
    # ------------------------------------------------- decimal/hugeint edge
    ("decimal_edge",
     ["CREATE TABLE t(v DECIMAL(38,10))",
      "INSERT INTO t VALUES (0.0000000001),(9999999999999999999999999999.9999999999),(-9999999999999999999999999999.9999999999)"],
     "SELECT v, v/3, SUM(v) OVER () FROM t ORDER BY v",
     "decimal max scale arithmetic"),
    ("hugeint_edge",
     ["CREATE TABLE t(v HUGEINT)",
      "INSERT INTO t VALUES (170141183460469231731687303715884105727),(-170141183460469231731687303715884105727),(0)"],
     "SELECT v, v-1, -v, ABS(v) FROM t ORDER BY v",
     "hugeint bounds + abs(min)"),
    ("bigint_edge",
     ["CREATE TABLE t(v BIGINT)",
      "INSERT INTO t VALUES (9223372036854775807),(-9223372036854775808),(1)"],
     "SELECT v, v*1, v/1, SUM(v) OVER (ORDER BY v) FROM t ORDER BY v",
     "int64 bounds window sum overflow"),
    # ------------------------------------------------------------- interval
    ("interval_edge",
     ["CREATE TABLE t(d DATE, iv INTERVAL)",
      "INSERT INTO t VALUES (DATE '2024-01-31', INTERVAL '1 month'),(DATE '2024-02-29', INTERVAL '1 month'),(DATE '2023-02-28', INTERVAL '12 month')"],
     "SELECT d, d + iv nxt, iv FROM t ORDER BY d",
     "month-end interval add"),
    ("interval_edge",
     ["CREATE TABLE t(a INTERVAL, b INTERVAL)",
      "INSERT INTO t VALUES (INTERVAL '1 year', INTERVAL '12 months'),(INTERVAL '90 minutes', INTERVAL '1 hour 30 minutes')"],
     "SELECT a = b eq, a IS NOT DISTINCT FROM b nulleq, a - b diff FROM t ORDER BY a",
     "interval unit equivalence"),
    # ------------------------------------------------------- window edges
    ("window_groups",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,2),(1,3),(2,1)"],
     "SELECT g, v, SUM(v) OVER (PARTITION BY g ORDER BY v GROUPS BETWEEN 1 PRECEDING AND CURRENT ROW) s FROM t ORDER BY g, v",
     "GROUPS frame with ties"),
    ("window_exclude",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,2),(1,3)"],
     "SELECT v, SUM(v) OVER (PARTITION BY g ORDER BY v ROWS BETWEEN CURRENT ROW AND CURRENT ROW) s FROM t ORDER BY v",
     "current-row frame with dup peers"),
    ("window_exclude",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,2),(1,3)"],
     "SELECT v, NTH_VALUE(v, 2) OVER (PARTITION BY g ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) n, LAG(v, 2) OVER (PARTITION BY g ORDER BY v) l FROM t ORDER BY v",
     "nth_value/lag with dup peers"),
    ("window_ignore_nulls",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,NULL),(1,NULL),(1,4)"],
     "SELECT v, LAST_VALUE(v IGNORE NULLS) OVER (PARTITION BY g ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) lv FROM t ORDER BY v",
     "IGNORE NULLS window"),
    ("window_range_multikey",
     ["CREATE TABLE t(a INT, b INT, v INT)",
      "INSERT INTO t VALUES (1,1,10),(1,2,20),(1,2,30),(1,3,40)"],
     "SELECT a, b, SUM(v) OVER (PARTITION BY a ORDER BY a, b RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) s FROM t ORDER BY a, b",
     "RANGE with two order keys"),
    # -------------------------------------------------- set ops / star sugar
    ("union_by_name",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,2)"],
     "SELECT a, b FROM t UNION BY NAME SELECT b, a FROM t ORDER BY a, b",
     "union by name reordered cols"),
    ("union_by_name",
     ["CREATE TABLE t(a INT)",
      "INSERT INTO t VALUES (1)"],
     "SELECT a, NULL b FROM t UNION BY NAME SELECT b, a FROM (VALUES (5,6)) v(b,a) ORDER BY a, b",
     "union by name disjoint cols"),
    ("star_exclude",
     ["CREATE TABLE t(a INT, b INT, c INT)",
      "INSERT INTO t VALUES (1,2,3)"],
     "SELECT * EXCLUDE (b), COLUMNS('a|c') FROM t",
     "star exclude + columns regex"),
    ("star_replace",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,2)"],
     "SELECT * REPLACE (a*10 AS a) FROM t ORDER BY a",
     "star replace expression"),
    # ------------------------------------------------- semi/anti & coalesce
    ("anti_join",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(a INT)",
      "INSERT INTO l VALUES (1),(2),(3),(NULL)", "INSERT INTO r VALUES (2),(NULL)"],
     "SELECT a FROM l ANTI JOIN r ON l.a = r.a ORDER BY a",
     "anti join with NULL keys"),
    ("semi_join",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(a INT)",
      "INSERT INTO l VALUES (1),(2),(3),(NULL)", "INSERT INTO r VALUES (2),(2),(NULL)"],
     "SELECT a FROM l SEMI JOIN r ON l.a = r.a ORDER BY a",
     "semi join dup + NULL"),
    ("all_any",
     ["CREATE TABLE t(x INT)", "CREATE TABLE u(y INT)",
      "INSERT INTO t VALUES (1),(5),(NULL)", "INSERT INTO u VALUES (3),(4),(NULL)"],
     "SELECT x, x > ALL(SELECT y FROM u) gt_all, x = ANY(SELECT y FROM u WHERE y IS NOT NULL) eq_any FROM t ORDER BY x",
     "ALL/ANY with NULLs"),
    ("coalesce_types",
     ["CREATE TABLE t(a INT, b DECIMAL(10,2), c VARCHAR)",
      "INSERT INTO t VALUES (NULL,1.5,'x'),(2,NULL,'y')"],
     "SELECT COALESCE(a, 0) i, COALESCE(b, 0) d, IFNULL(a, b) m FROM t ORDER BY i",
     "coalesce type coercion chain"),
    ("try_cast",
     ["CREATE TABLE t(s VARCHAR)",
      "INSERT INTO t VALUES ('10'),('abc'),('20'),(NULL)"],
     "SELECT s, TRY_CAST(s AS INT) i FROM t WHERE TRY_CAST(s AS INT) > 5 OR TRY_CAST(s AS INT) IS NULL ORDER BY s",
     "try_cast in predicate"),
    # ---------------------------------------------- misc DuckDB-specific
    ("string_agg",
     ["CREATE TABLE t(g INT, v VARCHAR)",
      "INSERT INTO t VALUES (1,'b'),(1,'a'),(1,'a'),(2,'c')"],
     "SELECT g, string_agg(v, ',' ORDER BY v) s, string_agg(DISTINCT v ORDER BY v) sd FROM t GROUP BY g ORDER BY g",
     "string_agg ordered + distinct"),
    ("arg_max",
     ["CREATE TABLE t(g INT, k INT, v INT)",
      "INSERT INTO t VALUES (1,5,100),(1,5,200),(1,9,50),(2,1,10)"],
     "SELECT g, arg_max(v, k) am, arg_min(v, k) an FROM t GROUP BY g ORDER BY g",
     "arg_max tie on k"),
    ("filtered_agg",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,5),(2,NULL),(2,7)"],
     "SELECT g, COUNT(*) FILTER (v > 3) c1, SUM(v) FILTER (v > 3) s1, countif(v > 3) c2 FROM t GROUP BY g ORDER BY g",
     "FILTER clause + countif equivalence"),
    ("lateral_subq",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(2,5)"],
     "SELECT t.g, s.topv FROM t CROSS JOIN LATERAL (SELECT MAX(v) topv FROM t t2 WHERE t2.g = t.g) s ORDER BY t.g, t.v",
     "lateral correlated max"),
    ("in_subq_types",
     ["CREATE TABLE t(a INT)", "CREATE TABLE u(b VARCHAR)",
      "INSERT INTO t VALUES (1),(2)", "INSERT INTO u VALUES ('1'),('x')"],
     "SELECT a FROM t WHERE a::VARCHAR IN (SELECT b FROM u) ORDER BY a",
     "IN subquery cross-type coercion"),
    ("is_distinct",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(NULL,NULL),(NULL,3)"],
     "SELECT a, b, a IS NOT DISTINCT FROM b eq1, a IS DISTINCT FROM b ne FROM t ORDER BY a, b",
     "null-safe equality chain"),
    ("natural_join",
     ["CREATE TABLE t(a INT, b INT)", "CREATE TABLE u(a INT, c INT)",
      "INSERT INTO t VALUES (1,10),(2,20)", "INSERT INTO u VALUES (1,100),(3,300)"],
     "SELECT * FROM t NATURAL JOIN u ORDER BY a",
     "natural join shared key"),
    ("case_types",
     ["CREATE TABLE t(x INT)",
      "INSERT INTO t VALUES (1),(2),(3)"],
     "SELECT x, CASE WHEN x = 1 THEN x::DECIMAL(10,2) WHEN x = 2 THEN x ELSE NULL END r FROM t ORDER BY x",
     "CASE mixed result types"),
    ("generate_series",
     ["CREATE TABLE t(id INT)",
      "INSERT INTO t VALUES (2)"],
     "SELECT g.d FROM (SELECT generate_series d FROM t, generate_series(DATE '2024-01-01', DATE '2024-01-01' + t.id * INTERVAL '1 day', INTERVAL '1 day')) g ORDER BY d",
     "generate_series date interval"),
    ("scalar_corr",
     ["CREATE TABLE t(g INT, v INT)", "CREATE TABLE u(g INT, w INT)",
      "INSERT INTO t VALUES (1,10),(2,20)", "INSERT INTO u VALUES (1,100),(2,200)"],
     "SELECT t.g, (SELECT MAX(u.w) FROM u WHERE u.g = t.g) mw, (SELECT COUNT(*) FROM u WHERE u.g <= t.g) cnt FROM t ORDER BY t.g",
     "two scalar correlated subqueries"),
    ("window_nested_expr",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(2,5)"],
     "SELECT g, SUM(SUM(v)) OVER (PARTITION BY g) gs FROM t GROUP BY g ORDER BY g",
     "window over aggregate"),
    # ---------------------------------------- order-inside-aggregate edges
    ("agg_inner_order",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,3),(1,1),(1,2),(2,5),(2,4)"],
     "SELECT g, LIST(v ORDER BY v) lv, LIST(v ORDER BY v DESC) ld FROM t GROUP BY g ORDER BY g",
     "list agg asc+desc same group"),
    ("agg_inner_order",
     ["CREATE TABLE t(g INT, v VARCHAR)",
      "INSERT INTO t VALUES (1,'b'),(1,'a'),(2,'d'),(2,'c')"],
     "SELECT g, STRING_AGG(v, '-' ORDER BY v DESC) s FROM t GROUP BY g ORDER BY g",
     "string_agg inner order"),
    ("agg_inner_order",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,3),(1,4)"],
     "SELECT g, ARRAY_AGG(v ORDER BY v) FILTER (v > 1) a, LIST(DISTINCT v ORDER BY v) d FROM t GROUP BY g ORDER BY g",
     "agg order + filter + limit inside"),
    ("quantile_edge",
     ["CREATE TABLE t(g INT, v DOUBLE)",
      "INSERT INTO t VALUES (1,0.5),(1,1.5),(1,2.5),(2,0.0),(2,10.0)"],
     "SELECT g, quantile_cont(v, 0.5) qc, quantile_disc(v, 0.5) qd, MEDIAN(v) m FROM t GROUP BY g ORDER BY g",
     "cont vs disc quantile boundary"),
    ("mode_agg",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,2),(2,3),(2,3),(2,4)"],
     "SELECT g, MODE(v) m FROM t GROUP BY g ORDER BY g",
     "mode with tied frequencies"),
    # ------------------------------------------------- multiset setops
    ("except_all",
     ["CREATE TABLE t(x INT)", "CREATE TABLE u(x INT)",
      "INSERT INTO t VALUES (1),(1),(2),(2),(2),(NULL)",
      "INSERT INTO u VALUES (1),(2),(NULL)"],
     "SELECT x FROM t EXCEPT ALL SELECT x FROM u ORDER BY x",
     "except-all multiplicity with NULL"),
    ("intersect_all",
     ["CREATE TABLE t(x INT)", "CREATE TABLE u(x INT)",
      "INSERT INTO t VALUES (1),(1),(2),(NULL),(NULL)",
      "INSERT INTO u VALUES (1),(NULL),(2)"],
     "SELECT x FROM t INTERSECT ALL SELECT x FROM u ORDER BY x",
     "intersect-all NULL multiplicity"),
    ("union_vs_distinct",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,1),(1,1),(2,NULL)"],
     "SELECT a FROM t UNION SELECT a FROM t UNION ALL SELECT a FROM t WHERE b IS NULL ORDER BY a",
     "union dedup + union all mix"),
    # -------------------------------------------- grouping/binding edges
    ("groupby_expr_types",
     ["CREATE TABLE t(v DOUBLE)",
      "INSERT INTO t VALUES (1),(1.0),(2.0),('2'::DOUBLE)"],
     "SELECT v, COUNT(*) FROM t GROUP BY v ORDER BY v",
     "numeric equality in grouping"),
    ("groupby_case",
     ["CREATE TABLE t(v INT)",
      "INSERT INTO t VALUES (1),(2),(3),(4),(NULL)"],
     "SELECT CASE WHEN v > 2 THEN 'big' ELSE 'small' END c, COUNT(*) FROM t GROUP BY 1 ORDER BY c",
     "GROUP BY ordinal over CASE"),
    ("distinct_nested",
     ["CREATE TABLE t(s STRUCT(a INT, b INT))",
      "INSERT INTO t VALUES ({'a':1,'b':2}),({'a':1,'b':2}),({'a':1,'b':3}),(NULL)"],
     "SELECT DISTINCT s FROM t ORDER BY s",
     "DISTINCT on structs with NULL"),
    ("orderby_nulls",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,NULL),(1,5),(2,3)"],
     "SELECT a, b, ROW_NUMBER() OVER (PARTITION BY a ORDER BY b NULLS FIRST) rn FROM t ORDER BY a, b",
     "NULLS FIRST window order"),
    ("join_on_expr",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(b INT)",
      "INSERT INTO l VALUES (1),(-1),(2)", "INSERT INTO r VALUES (1),(2)"],
     "SELECT l.a FROM l JOIN r ON abs(l.a) = r.b ORDER BY l.a",
     "join on computed expr"),
    ("corr_limit",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(1,30),(2,5),(2,15)"],
     "SELECT t.g, (SELECT v FROM t t2 WHERE t2.g = t.g ORDER BY v DESC LIMIT 1) mx FROM t GROUP BY g ORDER BY g",
     "correlated scalar LIMIT subquery"),
    ("corr_having_exists",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,5),(1,9),(2,7)"],
     "SELECT g, MAX(v) FROM t GROUP BY g HAVING EXISTS (SELECT 1 FROM t t2 WHERE t2.g = t.g AND t2.v < 8) ORDER BY g",
     "EXISTS inside HAVING"),
    ("named_window",
     ["CREATE TABLE t(a INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(2,30)"],
     "SELECT SUM(v) OVER w s, AVG(v) OVER w av, COUNT(*) OVER w c FROM t WINDOW w AS (PARTITION BY a) ORDER BY a, v",
     "named window three refs"),
    ("recursive_cte_window",
     ["CREATE TABLE t(x INT)",
      "INSERT INTO t VALUES (1)"],
     "WITH RECURSIVE r(n, s) AS (SELECT x, x FROM t UNION ALL SELECT n+1, s+n+1 FROM r WHERE n < 4) SELECT n, s, SUM(s) OVER (ORDER BY n) cum FROM r ORDER BY n",
     "recursive cte + running window"),
    ("in_union_subq",
     ["CREATE TABLE t(a INT)", "CREATE TABLE u(a INT)", "CREATE TABLE v(a INT)",
      "INSERT INTO t VALUES (1),(2),(3)", "INSERT INTO u VALUES (2)", "INSERT INTO v VALUES (3)"],
     "SELECT a FROM t WHERE a IN (SELECT a FROM u UNION SELECT a FROM v) ORDER BY a",
     "IN over UNION subquery"),
    ("filter_multi_agg",
     ["CREATE TABLE t(g INT, v INT, w INT)",
      "INSERT INTO t VALUES (1,1,10),(1,5,20),(2,3,30),(2,7,40)"],
     "SELECT g, SUM(v) FILTER (w > 15) s1, SUM(w) FILTER (v > 2) s2, COUNT(*) FILTER (v > w) c FROM t GROUP BY g ORDER BY g",
     "different FILTER predicates same group"),
    ("collate_edge",
     ["CREATE TABLE t(v VARCHAR)",
      "INSERT INTO t VALUES ('ABC'),('abc'),('Abc'),('abd')"],
     "SELECT v, v = 'abc' eq, v COLLATE NOCASE = 'abc' nce FROM t ORDER BY v COLLATE NOCASE, v",
     "collation equality vs binary"),
    ("collate_edge",
     ["CREATE TABLE t(v VARCHAR)", "CREATE TABLE u(v VARCHAR)",
      "INSERT INTO t VALUES ('A'),('b'),('C')", "INSERT INTO u VALUES ('a'),('B')"],
     "SELECT t.v, u.v FROM t JOIN u ON t.v COLLATE NOCASE = u.v COLLATE NOCASE ORDER BY t.v, u.v",
     "collation join key"),
    ("bitstring_edge",
     ["CREATE TABLE t(b BITSTRING)",
      "INSERT INTO t VALUES ('1010'),('0101'),('1111')"],
     "SELECT b, bit_count(b) bc, b & '1100' masked FROM t ORDER BY b",
     "bit ops in projection"),
    ("enum_edge",
     ["CREATE TYPE mood AS ENUM ('sad','ok','happy')",
      "CREATE TABLE t(id INT, m mood)",
      "INSERT INTO t VALUES (1,'sad'),(2,'ok'),(3,'happy'),(4,'ok')"],
     "SELECT m, COUNT(*) FROM t GROUP BY m ORDER BY m",
     "enum ordering + group by"),
    ("union_type",
     ["CREATE TABLE t(id INT, u UNION(num INT, txt VARCHAR))",
      "INSERT INTO t VALUES (1,union_value(num := 5)),(2,union_value(txt := 'x'))"],
     "SELECT id, u.num n, u.txt s FROM t ORDER BY id",
     "union type member access"),
    # -------------------------------------------------- batch 3: deep edges
    ("full_outer",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(a INT)",
      "INSERT INTO l VALUES (1),(2),(NULL)", "INSERT INTO r VALUES (2),(3),(NULL)"],
     "SELECT l.a la, r.a ra FROM l FULL OUTER JOIN r ON l.a = r.a ORDER BY la, ra",
     "full outer + NULL keys both sides"),
    ("window_frame_equiv",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,3),(2,5)"],
     "SELECT g, v, SUM(v) OVER (PARTITION BY g ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) rs FROM t ORDER BY g, v",
     "ROWS running sum"),
    ("window_frame_equiv",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,2),(1,3)"],
     "SELECT g, v, SUM(v) OVER (PARTITION BY g ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) rs, SUM(v) OVER (PARTITION BY g ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) ws FROM t ORDER BY g, v",
     "RANGE vs ROWS on peer ties"),
    ("cume_dist",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,2),(1,3)"],
     "SELECT v, CUME_DIST() OVER (PARTITION BY g ORDER BY v) cd, PERCENT_RANK() OVER (PARTITION BY g ORDER BY v) pr FROM t ORDER BY v",
     "cume_dist/percent_rank with peers"),
    ("ntile_edge",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,3),(1,4),(1,5)"],
     "SELECT v, NTILE(3) OVER (PARTITION BY g ORDER BY v) n3, NTILE(10) OVER (PARTITION BY g ORDER BY v) n10 FROM t ORDER BY v",
     "ntile bigger than group"),
    ("like_escape",
     ["CREATE TABLE t(v VARCHAR)",
      "INSERT INTO t VALUES ('a_b'),('axb'),('a%b'),('abc')"],
     "SELECT v FROM t WHERE v LIKE 'a\\_b' ORDER BY v",
     "LIKE escape underscore"),
    ("like_escape",
     ["CREATE TABLE t(v VARCHAR)",
      "INSERT INTO t VALUES ('a_b'),('axb'),('a%b')"],
     "SELECT v FROM t WHERE v LIKE 'a!_b' ESCAPE '!' ORDER BY v",
     "LIKE custom escape"),
    ("between_null",
     ["CREATE TABLE t(v INT)",
      "INSERT INTO t VALUES (1),(5),(10),(NULL)"],
     "SELECT v, v BETWEEN 3 AND 7 b1, NOT (v BETWEEN 3 AND 7) nb FROM t ORDER BY v",
     "BETWEEN with NULL (3VL)"),
    ("case_in_join",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(b INT)",
      "INSERT INTO l VALUES (1),(2),(3)", "INSERT INTO r VALUES (1),(4)"],
     "SELECT l.a FROM l JOIN r ON CASE WHEN l.a < 3 THEN l.a ELSE -1 END = r.b ORDER BY l.a",
     "CASE expression in join key"),
    ("exists_in_case",
     ["CREATE TABLE t(g INT)", "CREATE TABLE u(g INT)",
      "INSERT INTO t VALUES (1),(2),(3)", "INSERT INTO u VALUES (2)"],
     "SELECT g, CASE WHEN EXISTS (SELECT 1 FROM u WHERE u.g = t.g) THEN 'y' ELSE 'n' END e FROM t ORDER BY g",
     "EXISTS inside CASE"),
    ("subq_orderby",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(2,5)"],
     "SELECT g FROM t GROUP BY g ORDER BY (SELECT MAX(v) FROM t t2 WHERE t2.g = t.g) DESC, g",
     "correlated scalar in ORDER BY"),
    ("window_range_null",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,NULL),(1,3),(1,NULL)"],
     "SELECT v, SUM(v) OVER (PARTITION BY g ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) s FROM t ORDER BY v",
     "RANGE frame over NULL order keys"),
    ("pivot_enum",
     ["CREATE TYPE k AS ENUM ('x','y','z')",
      "CREATE TABLE t(g INT, k k, v INT)",
      "INSERT INTO t VALUES (1,'x',10),(1,'y',20),(2,'z',30),(2,'x',40)"],
     "PIVOT t ON k USING SUM(v) GROUP BY g ORDER BY g",
     "pivot over enum column order"),
    ("list_concat_null",
     ["CREATE TABLE t(id INT, a INT[], b INT[])",
      "INSERT INTO t VALUES (1,[1,2],NULL),(2,NULL,[3]),(3,[],[4])"],
     "SELECT id, list_concat(a,b) c, a || b cat FROM t ORDER BY id",
     "list concat NULL semantics"),
    ("range_tablefn",
     ["CREATE TABLE t(n INT)",
      "INSERT INTO t VALUES (0),(3)"],
     "SELECT r.i FROM t, range(t.n) r(i) ORDER BY t.n, r.i",
     "range() with 0 and correlated arg"),
    ("struct_chain",
     ["CREATE TABLE t(id INT, s STRUCT(a INT, b STRUCT(c INT)))",
      "INSERT INTO t VALUES (1,{'a':1,'b':{'c':10}}),(2,{'a':2,'b':NULL}),(3,NULL)"],
     "SELECT id, s.b.c bc, s.a sa FROM t ORDER BY id",
     "nested struct field through NULL"),
    ("values_exprs",
     ["CREATE TABLE t(x INT)",
      "INSERT INTO t VALUES (5)"],
     "SELECT v.a, v.a + t.x s FROM (VALUES (1),(2)) v(a), t ORDER BY v.a",
     "VALUES list + cross product"),
    ("having_window",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,9),(2,5),(2,5)"],
     "SELECT g, v, ROW_NUMBER() OVER (PARTITION BY g ORDER BY v) rn FROM t GROUP BY g, v HAVING COUNT(*) >= 1 QUALIFY rn <= 2 ORDER BY g, v",
     "group+having+qualify+window stack"),
    # ------------------------------------------------- batch 4: ASOF/IEJOIN
    ("asof_left",
     ["CREATE TABLE ev(ts INT, v INT)", "CREATE TABLE px(ts INT, p INT)",
      "INSERT INTO ev VALUES (5,1),(7,2),(10,3)",
      "INSERT INTO px VALUES (6,10),(5,20)"],
     "SELECT ev.ts, px.p FROM ev ASOF LEFT JOIN px ON ev.ts >= px.ts ORDER BY ev.ts",
     "asof left: no-match rows keep left side"),
    ("asof_eq_ineq",
     ["CREATE TABLE ev(id INT, ts INT)", "CREATE TABLE px(id INT, ts INT, p INT)",
      "INSERT INTO ev VALUES (1,5),(1,9),(2,5)",
      "INSERT INTO px VALUES (1,5,10),(1,5,20),(1,8,30),(2,4,40)"],
     "SELECT ev.id, ev.ts, px.p FROM ev ASOF JOIN px ON ev.id = px.id AND ev.ts >= px.ts ORDER BY ev.id, ev.ts, px.p",
     "asof eq-key + tied ts"),
    ("asof_subq",
     ["CREATE TABLE ev(ts INT)", "CREATE TABLE px(ts INT, p INT)",
      "INSERT INTO ev VALUES (5),(10)",
      "INSERT INTO px VALUES (4,10),(5,20),(9,30)"],
     "SELECT ev.ts, s.p FROM ev ASOF JOIN (SELECT * FROM px WHERE p > 5) s ON ev.ts >= s.ts ORDER BY ev.ts",
     "asof over filtered subquery"),
    ("asof_null_key",
     ["CREATE TABLE ev(ts INT)", "CREATE TABLE px(ts INT, p INT)",
      "INSERT INTO ev VALUES (5),(NULL),(10)",
      "INSERT INTO px VALUES (5,10),(NULL,99),(9,30)"],
     "SELECT ev.ts, px.p FROM ev ASOF JOIN px ON ev.ts >= px.ts ORDER BY ev.ts",
     "asof NULL keys"),
    ("iejoin_lt",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(b INT)",
      "INSERT INTO l VALUES (1),(5),(9)", "INSERT INTO r VALUES (3),(6),(8)"],
     "SELECT l.a, r.b FROM l JOIN r ON l.a < r.b ORDER BY l.a, r.b",
     "pure inequality join"),
    ("iejoin_range",
     ["CREATE TABLE l(a INT, b INT)", "CREATE TABLE r(x INT, y INT)",
      "INSERT INTO l VALUES (1,10),(2,20)", "INSERT INTO r VALUES (5,15),(8,25)"],
     "SELECT l.a, r.x FROM l JOIN r ON l.a < r.x AND l.b > r.y ORDER BY l.a, r.x",
     "two-sided range join"),
    ("iejoin_mixed",
     ["CREATE TABLE l(id INT, v INT)", "CREATE TABLE r(id INT, w INT)",
      "INSERT INTO l VALUES (1,5),(2,10)", "INSERT INTO r VALUES (1,7),(1,3),(2,20)"],
     "SELECT l.id, l.v, r.w FROM l JOIN r ON l.id = r.id AND l.v < r.w ORDER BY l.id, l.v, r.w",
     "equality + inequality join"),
    ("positional_filter",
     ["CREATE TABLE a(x INT)", "CREATE TABLE b(y INT)",
      "INSERT INTO a VALUES (1),(2),(3)", "INSERT INTO b VALUES (10),(20),(30)"],
     "SELECT a.x, b.y FROM a POSITIONAL JOIN b WHERE a.x <> 2 ORDER BY a.x",
     "positional + filter"),
    ("window_dup_part2",
     ["CREATE TABLE t(a INT, b INT, v INT)",
      "INSERT INTO t VALUES (1,1,10),(1,2,20),(2,1,30)"],
     "SELECT SUM(v) OVER (PARTITION BY a, a, b) s1, AVG(v) OVER (PARTITION BY a) s2 FROM t ORDER BY a, b",
     "dup key in 3-col partition"),
    ("window_dup_part2",
     ["CREATE TABLE t(a INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(2,30)"],
     "SELECT SUM(v) OVER (PARTITION BY a, a) s1, COUNT(*) OVER (PARTITION BY a, v) s2, MIN(v) OVER (PARTITION BY a) s3 FROM t ORDER BY a, v",
     "dup-partition + different second window"),
    ("corr_in_select_agg",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(2,5)"],
     "SELECT g, (SELECT COUNT(*) FROM t t2 WHERE t2.g = t.g AND t2.v > 8) c, SUM(v) FROM t GROUP BY g ORDER BY g",
     "correlated scalar + group agg same level"),
    # ------------------------------------------------------------ batch 5
    # Executor-variant stressors: shapes chosen to exercise the new
    # executor-level interventions (perfect_ht, prefer_range_joins,
    # late_materialization, window modes, insertion order).
    ("groupby_struct_key",
     ["CREATE TABLE t(s STRUCT(x INT, y INT), v INT)",
      "INSERT INTO t VALUES ({x:1,y:1},10),({x:1,y:1},20),({x:2,y:1},5)"],
     "SELECT s, SUM(v) FROM t GROUP BY s ORDER BY s.x, s.y",
     "group by STRUCT key (hash path)"),
    ("groupby_list_key",
     ["CREATE TABLE t(l INT[], v INT)",
      "INSERT INTO t VALUES ([1,2],10),([1,2],20),([3],5)"],
     "SELECT l, COUNT(*) c, SUM(v) s FROM t GROUP BY l ORDER BY l",
     "group by LIST key"),
    ("groupby_many_keys",
     ["CREATE TABLE t(a INT, b INT, c INT, d INT, v INT)",
      "INSERT INTO t SELECT i%3, i%5, i%7, i%11, i FROM range(200) s(i)"],
     "SELECT a, b, c, d, COUNT(*) FROM t GROUP BY a, b, c, d ORDER BY a, b, c, d",
     "wide group key (perfect_ht vs radix)"),
    ("distinct_agg_struct",
     ["CREATE TABLE t(g INT, s STRUCT(x INT))",
      "INSERT INTO t VALUES (1,{x:1}),(1,{x:1}),(1,{x:2}),(2,{x:1})"],
     "SELECT g, COUNT(DISTINCT s) FROM t GROUP BY g ORDER BY g",
     "DISTINCT over struct values"),
    ("range_join_pure",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(b INT)",
      "INSERT INTO l SELECT i FROM range(50) s(i)",
      "INSERT INTO r SELECT i*3 FROM range(30) s(i)"],
     "SELECT COUNT(*) FROM l JOIN r ON l.a < r.b",
     "pure inequality join (range_join path)"),
    ("range_join_eq_plus",
     ["CREATE TABLE l(id INT, a INT)", "CREATE TABLE r(id INT, b INT)",
      "INSERT INTO l SELECT i%4, i FROM range(80) s(i)",
      "INSERT INTO r SELECT i%4, i*2 FROM range(40) s(i)"],
     "SELECT l.id, COUNT(*) c FROM l JOIN r ON l.id = r.id AND l.a <= r.b GROUP BY l.id ORDER BY l.id",
     "equality+inequality join (iejoin vs nlj)"),
    ("window_mixed_frames",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,3),(2,1),(2,2)"],
     "SELECT g, v, SUM(v) OVER (PARTITION BY g ORDER BY v ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) a, "
     "SUM(v) OVER (PARTITION BY g ORDER BY v RANGE BETWEEN 1 PRECEDING AND CURRENT ROW) b "
     "FROM t ORDER BY g, v",
     "ROWS vs RANGE same query"),
    ("window_exclude_clause",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(1,3),(2,1)"],
     "SELECT g, v, SUM(v) OVER (PARTITION BY g ORDER BY v GROUPS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE CURRENT ROW) s "
     "FROM t ORDER BY g, v",
     "GROUPS frame + EXCLUDE"),
    ("late_mat_wide",
     ["CREATE TABLE t(a INT, b VARCHAR, c DOUBLE, d INT)",
      "INSERT INTO t SELECT i, 'x'||i::VARCHAR, i*1.5, i%7 FROM range(300) s(i)"],
     "SELECT a, b, c FROM t WHERE d = 3 ORDER BY a LIMIT 10",
     "filter + limit over wide rows (late mat)"),
    ("union_by_name_mismatch",
     ["CREATE TABLE t(a INT, b INT)", "CREATE TABLE u(b INT, c INT)",
      "INSERT INTO t VALUES (1,2)", "INSERT INTO u VALUES (3,4)"],
     "SELECT * FROM t UNION BY NAME SELECT * FROM u ORDER BY a NULLS LAST, b, c",
     "UNION BY NAME asymmetric columns"),
    ("qualify_ntile",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(1,30),(2,5),(2,15)"],
     "SELECT g, v, NTILE(2) OVER (PARTITION BY g ORDER BY v) nt FROM t QUALIFY nt = 1 ORDER BY g, v",
     "QUALIFY on NTILE"),
    ("pivot_multi_agg",
     ["CREATE TABLE t(g INT, k VARCHAR, v INT)",
      "INSERT INTO t VALUES (1,'a',10),(1,'b',20),(2,'a',5),(2,'b',15),(1,'a',30)"],
     "PIVOT t ON k USING SUM(v) s, COUNT(*) c GROUP BY g ORDER BY g",
     "PIVOT with two aggregates"),
    ("pivot_null_keys",
     ["CREATE TABLE t(g INT, k VARCHAR, v INT)",
      "INSERT INTO t VALUES (1,'a',10),(1,NULL,20),(2,'a',5)"],
     "PIVOT t ON k USING SUM(v) GROUP BY g ORDER BY g",
     "PIVOT with NULL pivot key"),
    ("unpivot_basic",
     ["CREATE TABLE t(id INT, a INT, b INT)",
      "INSERT INTO t VALUES (1,10,100),(2,20,200)"],
     "UNPIVOT t ON a, b INTO NAME col VALUE val ORDER BY id, col",
     "UNPIVOT basic"),
    ("list_lambda_filter",
     ["CREATE TABLE t(l INT[])",
      "INSERT INTO t VALUES ([1,2,3]),([4,5]),([])"],
     "SELECT l, list_filter(l, x -> x > 2) f, list_transform(l, x -> x * 10) tr FROM t ORDER BY len(l)",
     "lambda over lists incl empty"),
    ("struct_pack_access",
     ["CREATE TABLE t(a INT, b VARCHAR)",
      "INSERT INTO t VALUES (1,'x'),(2,'y')"],
     "SELECT struct_pack(x := a, y := b).x, (struct_pack(x := a, y := b)).y FROM t ORDER BY a",
     "struct_pack then field access"),
    ("map_lookup_agg",
     ["CREATE TABLE t(g INT, m MAP(VARCHAR, INT))",
      "INSERT INTO t VALUES (1,map{'k':1}),(1,map{'k':2,'j':5}),(2,map{'k':9})"],
     "SELECT g, SUM(m['k']) FROM t GROUP BY g ORDER BY g",
     "map key lookup + aggregate"),
    ("interval_boundary",
     ["CREATE TABLE t(d DATE)",
      "INSERT INTO t VALUES (DATE '2024-01-31'),(DATE '2024-02-29'),(DATE '2023-02-28')"],
     "SELECT d, d + INTERVAL '1 month' d1, d + INTERVAL '30 days' d2 FROM t ORDER BY d",
     "month vs day interval on month-end"),
    ("timestamp_epoch",
     ["CREATE TABLE t(ts TIMESTAMP)",
      "INSERT INTO t VALUES (TIMESTAMP '1970-01-01 00:00:00'),(TIMESTAMP '1969-12-31 23:59:59')"],
     "SELECT ts, epoch(ts) e, ts + INTERVAL '1 second' p FROM t ORDER BY ts",
     "epoch boundary timestamps"),
    ("hugeint_bounds",
     ["CREATE TABLE t(v HUGEINT)",
      "INSERT INTO t VALUES (170141183460469231731687303715884105727),(-170141183460469231731687303715884105728),(0)"],
     "SELECT v, v / 2 h, v % 3 m FROM t ORDER BY v",
     "HUGEINT min/max arithmetic"),
    ("decimal_div_prec",
     ["CREATE TABLE t(a DECIMAL(38,10), b DECIMAL(20,5))",
      "INSERT INTO t VALUES (1.0, 3.0),(2.0, 7.0),(10.0, 4.0)"],
     "SELECT a, a / b q FROM t ORDER BY a",
     "decimal division precision"),
    ("nested_correlated_list",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,2),(2,3)"],
     "SELECT g, (SELECT list(v ORDER BY v) FROM t t2 WHERE t2.g = t1.g) l FROM t t1 GROUP BY g ORDER BY g",
     "correlated list aggregate in group query"),
    ("semi_join_null_probe",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(b INT)",
      "INSERT INTO l VALUES (1),(2),(NULL)", "INSERT INTO r VALUES (1),(NULL)"],
     "SELECT a FROM l WHERE a IN (SELECT b FROM r) ORDER BY a",
     "semi join with NULLs both sides"),
    ("anti_join_null_probe",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(b INT)",
      "INSERT INTO l VALUES (1),(2),(NULL)", "INSERT INTO r VALUES (1),(NULL)"],
     "SELECT a FROM l WHERE a NOT IN (SELECT b FROM r) ORDER BY a",
     "anti join with NULLs both sides"),
    ("exists_double_corr",
     ["CREATE TABLE l(a INT, b INT)", "CREATE TABLE r(x INT, y INT)",
      "INSERT INTO l VALUES (1,10),(2,20)", "INSERT INTO r VALUES (1,5),(1,15),(2,25)"],
     "SELECT a FROM l WHERE EXISTS (SELECT 1 FROM r WHERE r.x = l.a AND r.y < l.b) ORDER BY a",
     "double-correlated EXISTS"),
    ("rollup_grouping",
     ["CREATE TABLE t(a INT, b INT, v INT)",
      "INSERT INTO t VALUES (1,1,10),(1,2,20),(2,1,5)"],
     "SELECT a, b, SUM(v) s, GROUPING(a, b) g2 FROM t GROUP BY ROLLUP(a, b) ORDER BY a NULLS LAST, b NULLS LAST",
     "ROLLUP + GROUPING()"),
    ("cube_grouping_id",
     ["CREATE TABLE t(a INT, b INT, v INT)",
      "INSERT INTO t VALUES (1,1,10),(2,2,20)"],
     "SELECT a, b, SUM(v), GROUPING_ID(a, b) gid FROM t GROUP BY CUBE(a, b) ORDER BY a NULLS LAST, b NULLS LAST, gid",
     "CUBE + GROUPING_ID"),
    ("grouping_sets_mixed",
     ["CREATE TABLE t(a INT, b INT, v INT)",
      "INSERT INTO t VALUES (1,1,10),(1,2,20),(2,NULL,5)"],
     "SELECT a, b, SUM(v) s FROM t GROUP BY GROUPING SETS ((a),(a,b),()) ORDER BY a NULLS LAST, b NULLS LAST",
     "GROUPING SETS with NULL col"),
    ("case_in_join_key",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(b INT, w INT)",
      "INSERT INTO l VALUES (1),(2),(3)", "INSERT INTO r VALUES (1,10),(4,40)"],
     "SELECT l.a, r.w FROM l LEFT JOIN r ON CASE WHEN l.a < 3 THEN l.a ELSE 4 END = r.b ORDER BY l.a",
     "CASE expression in join key"),
    ("or_join_predicate",
     ["CREATE TABLE l(a INT)", "CREATE TABLE r(b INT)",
      "INSERT INTO l VALUES (1),(2)", "INSERT INTO r VALUES (1),(3)"],
     "SELECT l.a, r.b FROM l JOIN r ON l.a = r.b OR l.a + 2 = r.b ORDER BY l.a, r.b",
     "OR in join predicate (dynamic_or filter)"),
    ("positional_join_offset",
     ["CREATE TABLE a(x INT)", "CREATE TABLE b(y INT)",
      "INSERT INTO a VALUES (1),(2),(3)", "INSERT INTO b VALUES (10),(20)"],
     "SELECT x, y FROM a POSITIONAL JOIN b ORDER BY x",
     "positional join length mismatch"),
    ("window_reuse_spec",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,10),(1,20),(2,5)"],
     "SELECT SUM(v) OVER w a, MAX(v) OVER w b, ROW_NUMBER() OVER w r FROM t WINDOW w AS (PARTITION BY g ORDER BY v) ORDER BY g, r",
     "named WINDOW shared by 3 functions"),
    ("agg_filter_order",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,1),(1,5),(1,9),(2,2)"],
     "SELECT g, ARRAY_AGG(v ORDER BY v DESC) FILTER (v > 3) a, COUNT(*) FILTER (v > 3) c FROM t GROUP BY g ORDER BY g",
     "FILTER + ORDER BY inside aggregate"),
    ("distinct_on",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,9),(1,5),(2,7),(2,1)"],
     "SELECT DISTINCT ON (a) a, b FROM t ORDER BY a, b",
     "DISTINCT ON with deterministic order"),
]
# idempotent queries; re-executing UPDATE/DELETE changes table state and
# self-produces differences. A DML oracle must snapshot/compare state, not
# replay the same statement.



def as_seeds() -> list[dict]:
    """Emit corpus-format seed dicts."""
    out = []
    for i, (rule, setup, query, note) in enumerate(RULE_TEMPLATES + FEATURE_TEMPLATES):
        out.append({
            "setup_sqls": list(setup),
            "query": query,
            "source": f"rule_target:{rule}#{i}",
            "engine": "duckdb",
            "tags": ["rule_target", rule, note],
        })
    return out
