"""SQLite-native seed templates — stress the newer / less-fuzzed SQLite
code paths (3.33-3.51 additions) while staying portable where the SQL
standard overlaps, so duckdb/postgres/datafusion can vote.

Targets: RIGHT/FULL OUTER JOIN (3.39) incl. mixed-direction chains and
USING/NATURAL dedup; UPDATE..FROM (3.33); RETURNING (3.35); STRICT (3.37);
JSON/JSONB (3.45/3.51); generated columns; UPSERT; IS DISTINCT FROM (3.39);
window RANGE/GROUPS/EXCLUDE frames; MATERIALIZED CTE hints (3.35);
collation-aware compound SELECTs; WITHOUT ROWID + expression/partial
indexes in setup.

Every query is deterministic: ORDER BY present whenever LIMIT/window
order-dependence exists; window ORDER BY keys unique inside partitions.
"""

from __future__ import annotations

# (name, setup_sqls, query)
SQLITE_TEMPLATES: list[tuple[str, list[str], str]] = [
    # ================= RIGHT / FULL OUTER JOIN (3.39) =================
    ("rj_basic",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20),(NULL,99)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,200),(3,300),(NULL,88)"],
     "SELECT a.x, a.y, b.x, b.z FROM a RIGHT JOIN b ON a.x=b.x ORDER BY b.x NULLS FIRST, b.z"),
    ("rj_null_key_no_match",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (NULL,10),(NULL,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (NULL,30)"],
     "SELECT count(*) FROM a RIGHT JOIN b ON a.x=b.x"),
    ("rj_where_left_null",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,200),(3,300)"],
     "SELECT b.x, b.z FROM a RIGHT JOIN b ON a.x=b.x WHERE a.x IS NULL ORDER BY b.x"),
    ("rj_left_right_chain",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5)",
      "CREATE TABLE c(x INT, w INT)",
      "INSERT INTO c VALUES (2,50),(4,40)"],
     "SELECT a.x, a.y, b.z, c.x, c.w FROM a LEFT JOIN b ON a.x=b.x RIGHT JOIN c ON a.x=c.x ORDER BY 4, 5"),
    ("fj_null_keys",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(NULL,99)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (1,50),(NULL,88)"],
     "SELECT a.x, a.y, b.x, b.z FROM a FULL JOIN b ON a.x=b.x ORDER BY 1 NULLS LAST, 3 NULLS LAST"),
    ("fj_where_or",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5),(3,7)"],
     "SELECT coalesce(a.x, b.x) FROM a FULL JOIN b ON a.x=b.x WHERE a.y>15 OR b.z>6 ORDER BY 1"),
    ("fj_coalesce_group",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5),(3,7)"],
     "SELECT coalesce(a.x,b.x) k, count(*) FROM a FULL JOIN b ON a.x=b.x GROUP BY 1 ORDER BY 1"),
    ("fj_using_star",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(NULL,99)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (1,50),(NULL,88)"],
     "SELECT * FROM a FULL JOIN b USING(x) ORDER BY 1 NULLS LAST, 2 NULLS LAST, 3 NULLS LAST"),
    ("rj_using_star",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5),(3,7),(4,9)"],
     "SELECT * FROM a RIGHT JOIN b USING(x) ORDER BY 1"),
    ("nj_right",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5),(3,7)"],
     "SELECT * FROM a NATURAL RIGHT JOIN b ORDER BY 1"),
    ("nj_full",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(3,30)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (1,50),(2,70)"],
     "SELECT * FROM a NATURAL FULL JOIN b ORDER BY 1 NULLS LAST"),
    ("nj_two_common",
     ["CREATE TABLE a(x INT, y INT, p INT)",
      "INSERT INTO a VALUES (1,10,100),(1,20,200),(2,10,300)",
      "CREATE TABLE b(x INT, y INT, q INT)",
      "INSERT INTO b VALUES (1,10,7),(1,30,8)"],
     "SELECT * FROM a NATURAL JOIN b ORDER BY 1,2,3"),
    ("nj_no_common_cols",
     ["CREATE TABLE a(x INT)",
      "INSERT INTO a VALUES (1),(2)",
      "CREATE TABLE b(z INT)",
      "INSERT INTO b VALUES (7),(8),(9)"],
     "SELECT count(*) FROM a NATURAL JOIN b"),
    # mirror invariant: a LEFT JOIN b == b RIGHT JOIN a (sym diff empty)
    ("rj_mirror_left",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20),(NULL,99)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,200),(3,300)"],
     "SELECT count(*) FROM ("
      "SELECT a.x ax, a.y ay, b.x bx, b.z bz FROM a LEFT JOIN b ON a.x=b.x "
      "EXCEPT "
      "SELECT a.x, a.y, b.x, b.z FROM b RIGHT JOIN a ON a.x=b.x)"),
    # inner join matching NULLs via IS NOT DISTINCT FROM (3.39)
    ("ij_is_not_distinct",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(NULL,99)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (1,50),(NULL,88),(NULL,77)"],
     "SELECT a.y, b.z FROM a JOIN b ON a.x IS NOT DISTINCT FROM b.x ORDER BY a.y, b.z"),
    ("fj_is_not_distinct",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(NULL,99)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (1,50),(NULL,88)"],
     "SELECT a.y, b.z FROM a FULL JOIN b ON a.x IS NOT DISTINCT FROM b.x ORDER BY a.y NULLS LAST, b.z NULLS LAST"),
    ("rj_subquery_rhs",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5),(3,7)"],
     "SELECT s.z, b.x FROM (SELECT x, z FROM b WHERE z > 6) s RIGHT JOIN b ON s.x = b.x ORDER BY b.x"),
    ("rj_on_expr",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (3,5),(4,7)"],
     "SELECT b.x FROM a RIGHT JOIN b ON a.x + 1 = b.x ORDER BY b.x"),
    ("rj_where_or_mixed",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5),(3,7),(4,9)"],
     "SELECT b.x FROM a RIGHT JOIN b ON a.x=b.x WHERE a.y > 15 OR b.z > 8 ORDER BY b.x"),
    ("lj_then_inner",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5)",
      "CREATE TABLE c(x INT, w INT)",
      "INSERT INTO c VALUES (1,1),(2,2)"],
     "SELECT a.x, b.z, c.w FROM a LEFT JOIN b ON a.x=b.x JOIN c ON a.x=c.x ORDER BY a.x"),
    # USING-join followed by RIGHT JOIN; right table shares the merged name
    # (qualified refs only — unqualified 'x' is legitimately ambiguous here)
    ("rj_after_using",
     ["CREATE TABLE a(x INT, y INT)",
      "INSERT INTO a VALUES (1,10),(2,20)",
      "CREATE TABLE b(x INT, z INT)",
      "INSERT INTO b VALUES (2,5),(3,7)",
      "CREATE TABLE c(x INT, w INT)",
      "INSERT INTO c VALUES (2,9),(3,8)"],
     "SELECT a.y, c.w FROM a JOIN b USING(x) RIGHT JOIN c ON a.y = c.w ORDER BY c.w"),
    ("fj_using_coalesce",
     ["CREATE TABLE t1(id INT, a INT)",
      "INSERT INTO t1 VALUES (1,10),(NULL,99)",
      "CREATE TABLE t2(id INT, b INT)",
      "INSERT INTO t2 VALUES (2,50),(NULL,88)"],
     "SELECT id, a, b FROM t1 FULL JOIN t2 USING(id) ORDER BY id NULLS LAST, a NULLS LAST, b NULLS LAST"),
    # ================= UPDATE..FROM / RETURNING / INSERT..SELECT =================
    ("uf_basic",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE u(k INT, v INT)",
      "INSERT INTO u VALUES (1,100),(3,300)"],
     "UPDATE t SET v = u.v + 1 FROM u WHERE t.k = u.k RETURNING t.k, t.v"),
    ("uf_self_alias",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20),(3,30)"],
     "UPDATE t SET v = t2.v + 1 FROM t t2 WHERE t.k = t2.k + 1 RETURNING t.k, t.v"),
    ("uf_no_match_keeps",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE u(k INT, v INT)",
      "INSERT INTO u VALUES (1,100)"],
     "UPDATE t SET v = 0 FROM u WHERE t.k = u.k RETURNING t.k, t.v"),
    ("uf_correlated_set",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE u(k INT, v INT)",
      "INSERT INTO u VALUES (1,100),(3,300)"],
     "UPDATE t SET v = (SELECT u.v FROM u WHERE u.k = t.k) RETURNING k, v"),
    ("upd_returning_expr",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20)"],
     "UPDATE t SET v = v * 2 RETURNING k, v, v + 1"),
    ("del_returning",
     ["CREATE TABLE t(k INT, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20),(3,30)"],
     "DELETE FROM t WHERE k > 1 RETURNING k, v"),
    ("del_returning_in",
     ["CREATE TABLE t(k INT, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE u(k INT)",
      "INSERT INTO u VALUES (1),(3)"],
     "DELETE FROM t WHERE k IN (SELECT k FROM u) RETURNING k"),
    ("with_delete_returning",
     ["CREATE TABLE t(k INT, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20),(3,30)",
      "CREATE TABLE u(k INT)",
      "INSERT INTO u VALUES (2)"],
     "WITH s AS (SELECT k FROM u) DELETE FROM t WHERE k IN (SELECT k FROM s) RETURNING k, v"),
    ("ins_select_returning",
     ["CREATE TABLE t(k INT, v INT)",
      "INSERT INTO t VALUES (9,9)",
      "CREATE TABLE u(k INT, v INT)",
      "INSERT INTO u VALUES (1,10),(2,20),(3,30)"],
     "INSERT INTO t SELECT k, v FROM u WHERE k > 1 RETURNING k, v"),
    ("ins_select_limit",
     ["CREATE TABLE t(k INT)",
      "CREATE TABLE u(k INT)",
      "INSERT INTO u VALUES (1),(2),(3),(4)"],
     "INSERT INTO t SELECT k FROM u ORDER BY k LIMIT 2 RETURNING k"),
    ("ins_select_upsert",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20)",
      "CREATE TABLE u(k INT, v INT)",
      "INSERT INTO u VALUES (1,100),(3,300)"],
     "INSERT INTO t SELECT k, v FROM u WHERE true ON CONFLICT(k) DO UPDATE SET v = excluded.v RETURNING k, v"),
    # ================= STRICT tables (3.37) =================
    ("strict_lossless_text",
     ["CREATE TABLE t(a INT, b TEXT) STRICT",
      "INSERT INTO t VALUES ('1','x'),('007','y')"],
     "SELECT a, typeof(a), b FROM t ORDER BY b"),
    ("strict_int_to_real",
     ["CREATE TABLE t(a REAL) STRICT",
      "INSERT INTO t VALUES (1),(2.5)"],
     "SELECT a, typeof(a) FROM t ORDER BY a"),
    ("strict_any_keeps",
     ["CREATE TABLE t(a ANY, b INT) STRICT",
      "INSERT INTO t VALUES ('1',1),(2,2),(x'33',3)"],
     "SELECT typeof(a), typeof(b) FROM t ORDER BY b"),
    ("strict_generated",
     ["CREATE TABLE t(a INT, b INT GENERATED ALWAYS AS (a*2) STORED) STRICT",
      "INSERT INTO t(a) VALUES (1),(2),(3)"],
     "SELECT a, b, typeof(b) FROM t ORDER BY a"),
    ("strict_any_coerce",
     ["CREATE TABLE t(a ANY) STRICT",
      "INSERT INTO t VALUES ('5'),(6)"],
     "SELECT count(*) FROM t WHERE a = 5"),
    # ================= JSON / JSONB =================
    ("j_arrow_text",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1,\"b\":[2,3]}'),(2,'{\"a\":9}'),(3,'{}'),(4,NULL)"],
     "SELECT id, j->>'a', j->'b' FROM j ORDER BY id"),
    ("j_arrow_chain",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":{\"b\":{\"c\":7}}}'),(2,'{\"a\":{\"b\":5}}')"],
     "SELECT id, j->'a'->'b'->>'c', j->'a'->>'b' FROM j ORDER BY id"),
    ("j_arrow_idx",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'[10,20,30]'),(2,'[1]'),(3,'[]')"],
     "SELECT id, j->>0, j->>1, j->>5 FROM j ORDER BY id"),
    ("j_arrow_cast_cmp",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1}'),(2,'{\"a\":20}'),(3,'{}')"],
     "SELECT id FROM j WHERE CAST(j->>'a' AS INT) > 5 ORDER BY id"),
    ("j_extract_deep",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":{\"b\":[7,8,9]}}'),(2,'{\"a\":{\"b\":[]}}'),(3,'{}')"],
     "SELECT id, json_extract(j,'$.a.b[1]'), json_type(j,'$.a.b') FROM j ORDER BY id"),
    ("j_extract_missing",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1}'),(2,'{\"b\":{\"c\":null}}')"],
     "SELECT id, json_extract(j,'$.zzz'), json_type(j,'$.b.c'), json_type(j,'$.b.d') FROM j ORDER BY id"),
    ("j_extract_multiarg",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1,\"b\":[2,3]}'),(2,'{\"a\":9}')"],
     "SELECT id, json_extract(j,'$.a','$.b','$.c') FROM j ORDER BY id"),
    ("j_valid_mixed",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1}'),(2,'{\"a\":1,'),(3,'[1,2]'),(4,''),(5,'01'),(6,' 1 ')"],
     "SELECT id, json_valid(j) FROM j ORDER BY id"),
    ("j_patch_merge",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1,\"b\":2}'),(2,'{\"a\":{\"x\":1}}')"],
     "SELECT id, json_patch(j,'{\"a\":null,\"c\":9}') FROM j ORDER BY id"),
    ("j_remove_multi",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1,\"b\":2,\"c\":3}'),(2,'{\"a\":1}')"],
     "SELECT id, json_remove(j,'$.a','$.b') FROM j ORDER BY id"),
    ("j_quote_types",
     [],
     "SELECT json_quote(NULL), json_quote(1.0), json_quote('x'), json_quote(7)"),
    ("j_each_tv",
     [],
     "SELECT key, value, type FROM json_each('{\"a\":1,\"b\":[2]}') ORDER BY key"),
    ("jb_roundtrip",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1}'),(2,'{\"a\":1.0}'),(3,'[1,2]')"],
     "SELECT id, json(jsonb(j)) FROM j ORDER BY id"),
    ("jb_arrow",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1,\"b\":{\"x\":2}}'),(2,'[5,6]')"],
     "SELECT id, jsonb(j)->'a', jsonb(j)->>'a', jsonb(j)->0 FROM j ORDER BY id"),
    ("jb_extract_scalar",
     ["CREATE TABLE j(id INT, j TEXT)",
      "INSERT INTO j VALUES (1,'{\"a\":1}'),(2,'{\"a\":2.5}'),(3,'{}')"],
     "SELECT id, jsonb_extract(j,'$.a'), typeof(jsonb_extract(j,'$.a')) FROM j ORDER BY id"),
    # ================= generated columns =================
    ("gen_virtual_stored",
     ["CREATE TABLE g(a INT, b INT GENERATED ALWAYS AS (a*2) VIRTUAL, c INT GENERATED ALWAYS AS (a+1) STORED)",
      "INSERT INTO g(a) VALUES (1),(2),(NULL)"],
     "SELECT a, b, c FROM g ORDER BY a NULLS LAST"),
    ("gen_update_recompute",
     ["CREATE TABLE g(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g(a) VALUES (1),(2)"],
     "UPDATE g SET a = a * 10 RETURNING a, b"),
    ("gen_insert_select",
     ["CREATE TABLE g(a INT, b INT GENERATED ALWAYS AS (a*3) VIRTUAL)",
      "CREATE TABLE u(a INT)",
      "INSERT INTO u VALUES (2),(4)",
      "INSERT INTO g(a) SELECT a FROM u"],
     "SELECT a, b FROM g ORDER BY a"),
    ("gen_indexed_upsert",
     ["CREATE TABLE g(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g(a) VALUES (1),(2)",
      "CREATE UNIQUE INDEX gi ON g(b)"],
     "INSERT INTO g(a) VALUES (1) ON CONFLICT(b) DO UPDATE SET a = a + 100 RETURNING a, b"),
    ("gen_join",
     ["CREATE TABLE g(a INT, b INT GENERATED ALWAYS AS (a*2) STORED)",
      "INSERT INTO g(a) VALUES (1),(2),(3)",
      "CREATE TABLE h(b INT)",
      "INSERT INTO h VALUES (4),(6)"],
     "SELECT g.a FROM g JOIN h ON g.b = h.b ORDER BY g.a"),
    # ================= UPSERT =================
    ("upsert_where_guard",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10),(2,20)"],
     "INSERT INTO t VALUES (1,5),(2,99) ON CONFLICT(k) DO UPDATE SET v = excluded.v WHERE excluded.v > t.v RETURNING k, v"),
    ("upsert_accumulate",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10)"],
     "INSERT INTO t VALUES (1,5) ON CONFLICT(k) DO UPDATE SET v = t.v + excluded.v RETURNING k, v"),
    ("upsert_worowid",
     ["CREATE TABLE w(a INT PRIMARY KEY, b INT) WITHOUT ROWID",
      "INSERT INTO w VALUES (1,10),(2,20)"],
     "INSERT INTO w VALUES (2,99),(3,30) ON CONFLICT(a) DO UPDATE SET b = excluded.b RETURNING a, b"),
    ("upsert_do_nothing",
     ["CREATE TABLE t(k INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (1,10)"],
     "INSERT INTO t VALUES (1,99),(2,20) ON CONFLICT(k) DO NOTHING RETURNING k, v"),
    # ================= IS [NOT] DISTINCT FROM =================
    ("distinct_from_pairs",
     ["CREATE TABLE t(x INT, y INT)",
      "INSERT INTO t VALUES (1,1),(NULL,NULL),(NULL,1),(1,NULL),(2,3)"],
     "SELECT x, y, CASE WHEN x IS DISTINCT FROM y THEN 1 ELSE 0 END d, CASE WHEN x IS NOT DISTINCT FROM y THEN 1 ELSE 0 END n FROM t ORDER BY x NULLS LAST, y NULLS LAST"),
    ("distinct_from_indexed",
     ["CREATE TABLE t(x INT, y INT)",
      "INSERT INTO t VALUES (1,10),(NULL,20),(2,30)",
      "CREATE INDEX i ON t(x)"],
     "SELECT y FROM t WHERE x IS DISTINCT FROM 1 ORDER BY y"),
    # ================= window functions =================
    ("win_range_offset",
     ["CREATE TABLE w(g INT, v INT)",
      "INSERT INTO w VALUES (1,10),(1,20),(1,30),(2,100)"],
     "SELECT g, v, sum(v) OVER (ORDER BY v RANGE BETWEEN 15 PRECEDING AND 15 FOLLOWING) s FROM w ORDER BY v"),
    ("win_groups_exclude",
     ["CREATE TABLE w(v INT)",
      "INSERT INTO w VALUES (10),(20),(30),(40)"],
     "SELECT v, sum(v) OVER (ORDER BY v GROUPS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE GROUP) s FROM w ORDER BY v"),
    ("win_exclude_current",
     ["CREATE TABLE w(g INT, v INT)",
      "INSERT INTO w VALUES (1,10),(1,20),(2,30)"],
     "SELECT g, v, sum(v) OVER (PARTITION BY g ORDER BY v ROWS UNBOUNDED PRECEDING EXCLUDE CURRENT ROW) s FROM w ORDER BY g, v"),
    ("win_nth_value",
     ["CREATE TABLE w(v INT)",
      "INSERT INTO w VALUES (10),(20),(30)"],
     "SELECT v, nth_value(v,2) OVER (ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) n FROM w ORDER BY v"),
    ("win_lead_lag_default",
     ["CREATE TABLE w(v INT)",
      "INSERT INTO w VALUES (10),(20),(30)"],
     "SELECT v, lag(v,1,-1) OVER (ORDER BY v) l, lead(v,2,0) OVER (ORDER BY v) d FROM w ORDER BY v"),
    ("win_ntile_edges",
     ["CREATE TABLE w(v INT)",
      "INSERT INTO w VALUES (10),(20),(30)"],
     "SELECT v, ntile(4) OVER (ORDER BY v) n4, ntile(1) OVER (ORDER BY v) n1 FROM w ORDER BY v"),
    ("win_empty_frame",
     ["CREATE TABLE w(v INT)",
      "INSERT INTO w VALUES (10),(20),(30)"],
     "SELECT v, sum(v) OVER (ORDER BY v ROWS BETWEEN 2 FOLLOWING AND 1 FOLLOWING) s, count(v) OVER (ORDER BY v ROWS BETWEEN 2 FOLLOWING AND 1 FOLLOWING) c FROM w ORDER BY v"),
    ("win_last_value_default",
     ["CREATE TABLE w(v INT)",
      "INSERT INTO w VALUES (10),(20),(30)"],
     "SELECT v, last_value(v) OVER (ORDER BY v) lv, last_value(v) OVER (ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) lf FROM w ORDER BY v"),
    ("win_filter",
     ["CREATE TABLE w(g INT, v INT)",
      "INSERT INTO w VALUES (1,5),(1,20),(2,30)"],
     "SELECT g, v, sum(v) FILTER (WHERE v > 10) OVER (PARTITION BY g) s FROM w ORDER BY g, v"),
    ("win_named",
     ["CREATE TABLE w(g INT, v INT)",
      "INSERT INTO w VALUES (1,10),(1,20),(2,30)"],
     "SELECT g, v, sum(v) OVER w1, count(*) OVER w2 FROM w WINDOW w1 AS (PARTITION BY g), w2 AS (ORDER BY v) ORDER BY g, v"),
    # named-window variants of the frame tests (same semantics, WINDOW clause)
    ("winw_range_offset",
     ["CREATE TABLE w(g INT, v INT)",
      "INSERT INTO w VALUES (1,10),(1,20),(1,30),(2,100)"],
     "SELECT g, v, sum(v) OVER w s FROM w WINDOW w AS (ORDER BY v RANGE BETWEEN 15 PRECEDING AND 15 FOLLOWING) ORDER BY v"),
    ("winw_groups_exclude",
     ["CREATE TABLE w(v INT)",
      "INSERT INTO w VALUES (10),(20),(30),(40)"],
     "SELECT v, sum(v) OVER w s FROM w WINDOW w AS (ORDER BY v GROUPS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE GROUP) ORDER BY v"),
    ("winw_excl_current",
     ["CREATE TABLE w(g INT, v INT)",
      "INSERT INTO w VALUES (1,10),(1,20),(2,30)"],
     "SELECT g, v, sum(v) OVER w s FROM w WINDOW w AS (PARTITION BY g ORDER BY v ROWS UNBOUNDED PRECEDING EXCLUDE CURRENT ROW) ORDER BY g, v"),
    ("winw_nth_full_frame",
     ["CREATE TABLE w(v INT)",
      "INSERT INTO w VALUES (10),(20),(30)"],
     "SELECT v, nth_value(v,2) OVER w n, last_value(v) OVER w l FROM w WINDOW w AS (ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) ORDER BY v"),
    # ================= CTE hints / misc CTE =================
    ("cte_mat_selfjoin",
     ["CREATE TABLE c1(a INT, b INT)",
      "INSERT INTO c1 VALUES (1,10),(1,20),(2,30)"],
     "WITH s AS MATERIALIZED (SELECT a, sum(b) t FROM c1 GROUP BY a) SELECT s1.a, s1.t, s2.t FROM s s1 JOIN s s2 ON s1.a = s2.a ORDER BY s1.a"),
    ("cte_notmat_selfjoin",
     ["CREATE TABLE c1(a INT, b INT)",
      "INSERT INTO c1 VALUES (1,10),(2,30)"],
     "WITH s AS NOT MATERIALIZED (SELECT a, b FROM c1) SELECT s1.a, s1.b, s2.b FROM s s1 JOIN s s2 ON s1.a = s2.a AND s1.b < s2.b ORDER BY s1.a"),
    ("cte_named_cols",
     [],
     "WITH c(x, y) AS (VALUES (1,10),(2,20)) SELECT sum(x*y) FROM c"),
    ("cte_recursive_depth",
     ["CREATE TABLE r(id INT, p INT)",
      "INSERT INTO r VALUES (1,NULL),(2,1),(3,2),(4,3)"],
     "WITH RECURSIVE tr(id, d) AS (SELECT id, 0 FROM r WHERE p IS NULL UNION ALL SELECT r.id, tr.d+1 FROM r JOIN tr ON r.p = tr.id) SELECT max(d), count(*) FROM tr"),
    # ================= compound SELECT + collation =================
    ("union_nocase_dedup",
     ["CREATE TABLE t(s TEXT)",
      "INSERT INTO t VALUES ('a'),('B')",
      "CREATE TABLE u(s TEXT)",
      "INSERT INTO u VALUES ('A'),('c')"],
     "SELECT count(*) FROM (SELECT s COLLATE NOCASE FROM t UNION SELECT s COLLATE NOCASE FROM u)"),
    ("union_rtrim_dedup",
     ["CREATE TABLE t(s TEXT)",
      "INSERT INTO t VALUES ('a'),('ab ')",
      "CREATE TABLE u(s TEXT)",
      "INSERT INTO u VALUES ('a '),('ab')"],
     "SELECT count(*) FROM (SELECT s COLLATE RTRIM FROM t UNION SELECT s COLLATE RTRIM FROM u)"),
    ("compound_precedence",
     ["CREATE TABLE t(x INT)",
      "INSERT INTO t VALUES (1),(2)",
      "CREATE TABLE u(x INT)",
      "INSERT INTO u VALUES (2),(3)",
      "CREATE TABLE v(x INT)",
      "INSERT INTO v VALUES (2),(4)"],
     "SELECT x FROM t UNION ALL SELECT x FROM u INTERSECT SELECT x FROM v ORDER BY x"),
    ("except_nulls",
     ["CREATE TABLE t(x INT)",
      "INSERT INTO t VALUES (1),(NULL),(NULL)",
      "CREATE TABLE u(x INT)",
      "INSERT INTO u VALUES (NULL),(2)"],
     "SELECT x, count(*) c FROM (SELECT x FROM t EXCEPT SELECT x FROM u) s GROUP BY x ORDER BY x NULLS LAST"),
    # ================= WITHOUT ROWID / indexes / misc =================
    ("worowid_range",
     ["CREATE TABLE w(a INT PRIMARY KEY, b INT) WITHOUT ROWID",
      "INSERT INTO w VALUES (1,10),(2,20),(3,30)"],
     "SELECT a, b FROM w WHERE a >= 2 ORDER BY a"),
    ("worowid_composite",
     ["CREATE TABLE w(a INT, b INT, v INT, PRIMARY KEY (a,b)) WITHOUT ROWID",
      "INSERT INTO w VALUES (1,1,10),(1,2,20),(2,1,30)"],
     "SELECT v FROM w WHERE a=1 AND b=2"),
    ("rowid_pk_allows_null",
     ["CREATE TABLE t(a INT PRIMARY KEY, v INT)",
      "INSERT INTO t VALUES (NULL,1)"],
     "SELECT count(*), count(a) FROM t"),
    ("expr_index",
     ["CREATE TABLE t(a INT, s TEXT)",
      "INSERT INTO t VALUES (1,'x'),(2,'y'),(3,'x')",
      "CREATE INDEX i ON t((a+1))"],
     "SELECT a FROM t WHERE a+1 IN (2,3) ORDER BY a"),
    ("partial_index",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,NULL),(2,5),(3,7),(4,NULL)",
      "CREATE INDEX i ON t(a) WHERE b IS NOT NULL"],
     "SELECT a, b FROM t WHERE a > 1 AND b IS NOT NULL ORDER BY a"),
    ("desc_index_order",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,10),(2,NULL),(3,30)",
      "CREATE INDEX i ON t(a DESC)"],
     "SELECT a FROM t ORDER BY a DESC NULLS LAST"),
    ("collate_index_nocase",
     ["CREATE TABLE t(s TEXT)",
      "INSERT INTO t VALUES ('Apple'),('banana'),('APPLE ')",
      "CREATE INDEX i ON t(s COLLATE NOCASE)"],
     "SELECT s FROM t WHERE s COLLATE NOCASE = 'apple' ORDER BY s"),
    ("values_derived",
     [],
     "SELECT column1, column2 FROM (VALUES (1,'a'),(2,'b')) v ORDER BY column1"),
    ("row_value_cmp",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,5),(1,9),(2,1)"],
     "SELECT a, b FROM t WHERE (a,b) > (1,5) ORDER BY a, b"),
    ("row_value_in",
     ["CREATE TABLE t(a INT, b INT)",
      "INSERT INTO t VALUES (1,5),(1,9),(2,1)",
      "CREATE TABLE u(a INT, b INT)",
      "INSERT INTO u VALUES (1,9),(2,1)"],
     "SELECT a, b FROM t WHERE (a,b) IN (SELECT a, b FROM u) ORDER BY a, b"),
    ("concat_null",
     [],
     "SELECT concat('a', 1, NULL, 'b'), concat_ws('-', 'a', NULL, 'b')"),
    ("group_concat_orderby",
     ["CREATE TABLE t(g INT, v INT)",
      "INSERT INTO t VALUES (1,30),(1,10),(1,20),(2,5)"],
     "SELECT g, group_concat(v, ',' ORDER BY v) FROM t GROUP BY g ORDER BY g"),
    ("fts5_match",
     ["CREATE VIRTUAL TABLE f USING fts5(x)",
      "INSERT INTO f VALUES ('hello world'),('other row'),('hello again')"],
     "SELECT rowid FROM f WHERE f MATCH 'hello' ORDER BY rowid"),
    ("ins_default_returning",
     ["CREATE TABLE t(a INT DEFAULT 7, b INT DEFAULT 42)"],
     "INSERT INTO t DEFAULT VALUES RETURNING a, b"),
]


def as_seeds():
    return [{"setup_sqls": s, "query": q,
             "source": f"sqlite_target:{n}#{i}", "engine": "sqlite"}
            for i, (n, s, q) in enumerate(SQLITE_TEMPLATES)]
